// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace AdaptiveScale.Adaptive
{
    [AdaptiveResourceType("adaptive:index:Authorization")]
    public partial class Authorization : global::Pulumi.CustomResource
    {
        /// <summary>
        /// An optional description of the authorization object.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The name of the authorization object.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The permission policy. The required format depends on resource_type: structured YAML for postgres/mysql/sqlserver/cockroachdb/yugabytedb (an `allow:` list of database/privileges/objects) and for kubernetes (an RBAC Role manifest); a free-form string for mongodb, ssh, and elasticsearch. Note: the SQL and kubernetes types are validated as YAML server-side, so a bare value like "SELECT" is rejected.
        /// </summary>
        [Output("permissions")]
        public Output<string> Permissions { get; private set; } = null!;

        /// <summary>
        /// Resource type to grant permission on, e.g. postgres, mysql, mongodb, kubernetes, ssh.
        /// </summary>
        [Output("resourceType")]
        public Output<string> ResourceType { get; private set; } = null!;

        /// <summary>
        /// Current lifecycle status of the authorization.
        /// </summary>
        [Output("status")]
        public Output<string?> Status { get; private set; } = null!;


        /// <summary>
        /// Create a Authorization resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Authorization(string name, AuthorizationArgs args, CustomResourceOptions? options = null)
            : base("adaptive:index:Authorization", name, args ?? new AuthorizationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Authorization(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("adaptive:index:Authorization", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/adaptive-scale/pulumi-adaptive",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Authorization resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Authorization Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Authorization(name, id, options);
        }
    }

    public sealed class AuthorizationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// An optional description of the authorization object.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The name of the authorization object.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The permission policy. The required format depends on resource_type: structured YAML for postgres/mysql/sqlserver/cockroachdb/yugabytedb (an `allow:` list of database/privileges/objects) and for kubernetes (an RBAC Role manifest); a free-form string for mongodb, ssh, and elasticsearch. Note: the SQL and kubernetes types are validated as YAML server-side, so a bare value like "SELECT" is rejected.
        /// </summary>
        [Input("permissions", required: true)]
        public Input<string> Permissions { get; set; } = null!;

        /// <summary>
        /// Resource type to grant permission on, e.g. postgres, mysql, mongodb, kubernetes, ssh.
        /// </summary>
        [Input("resourceType", required: true)]
        public Input<string> ResourceType { get; set; } = null!;

        public AuthorizationArgs()
        {
        }
        public static new AuthorizationArgs Empty => new AuthorizationArgs();
    }
}
