// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace AdaptiveScale.Adaptive
{
    [AdaptiveResourceType("adaptive:index:DataProtection")]
    public partial class DataProtection : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Name of the generated masking authorization (masked_&lt;resource&gt;). Attach it to an Endpoint's `authorization` to serve masked sessions.
        /// </summary>
        [Output("authorizationName")]
        public Output<string?> AuthorizationName { get; private set; } = null!;

        /// <summary>
        /// Last time the policy was applied to the target database.
        /// </summary>
        [Output("lastAppliedAt")]
        public Output<string?> LastAppliedAt { get; private set; } = null!;

        /// <summary>
        /// Masking rules, grouped per database and table.
        /// </summary>
        [Output("masks")]
        public Output<ImmutableArray<Outputs.DataProtectionMask>> Masks { get; private set; } = null!;

        /// <summary>
        /// Name of the resource (integration) this masking policy protects. Cannot be changed after creation. Note: creating a policy for a resource that already has one (e.g. configured in the UI) adopts and overwrites it.
        /// </summary>
        [Output("resource")]
        public Output<string> Resource { get; private set; } = null!;

        /// <summary>
        /// When true (the default), session users only see the generated masked views. When false, users see everything except the raw masked tables (requires synced metadata).
        /// </summary>
        [Output("scoped")]
        public Output<bool?> Scoped { get; private set; } = null!;

        /// <summary>
        /// Provisioning status of the policy. Masked views are created lazily at session start.
        /// </summary>
        [Output("status")]
        public Output<string?> Status { get; private set; } = null!;


        /// <summary>
        /// Create a DataProtection resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DataProtection(string name, DataProtectionArgs args, CustomResourceOptions? options = null)
            : base("adaptive:index:DataProtection", name, args ?? new DataProtectionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DataProtection(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("adaptive:index:DataProtection", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/adaptive-scale/pulumi-adaptive",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DataProtection resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DataProtection Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new DataProtection(name, id, options);
        }
    }

    public sealed class DataProtectionArgs : global::Pulumi.ResourceArgs
    {
        [Input("masks")]
        private InputList<Inputs.DataProtectionMaskArgs>? _masks;

        /// <summary>
        /// Masking rules, grouped per database and table.
        /// </summary>
        public InputList<Inputs.DataProtectionMaskArgs> Masks
        {
            get => _masks ?? (_masks = new InputList<Inputs.DataProtectionMaskArgs>());
            set => _masks = value;
        }

        /// <summary>
        /// Name of the resource (integration) this masking policy protects. Cannot be changed after creation. Note: creating a policy for a resource that already has one (e.g. configured in the UI) adopts and overwrites it.
        /// </summary>
        [Input("resource", required: true)]
        public Input<string> Resource { get; set; } = null!;

        /// <summary>
        /// When true (the default), session users only see the generated masked views. When false, users see everything except the raw masked tables (requires synced metadata).
        /// </summary>
        [Input("scoped")]
        public Input<bool>? Scoped { get; set; }

        public DataProtectionArgs()
        {
        }
        public static new DataProtectionArgs Empty => new DataProtectionArgs();
    }
}
