// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace AdaptiveScale.Adaptive
{
    [AdaptiveResourceType("adaptive:index:Endpoint")]
    public partial class Endpoint : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The authorization (by name) to apply to this endpoint.
        /// </summary>
        [Output("authorization")]
        public Output<string?> Authorization { get; private set; } = null!;

        /// <summary>
        /// Automatically approve Just-In-Time access requests.
        /// </summary>
        [Output("autoApproval")]
        public Output<bool?> AutoApproval { get; private set; } = null!;

        [Output("cluster")]
        public Output<string?> Cluster { get; private set; } = null!;

        [Output("cpu")]
        public Output<string?> Cpu { get; private set; } = null!;

        /// <summary>
        /// Hide Data Studio for this endpoint (cli endpoints only).
        /// </summary>
        [Output("disableDataStudio")]
        public Output<bool?> DisableDataStudio { get; private set; } = null!;

        /// <summary>
        /// Do not retain terminal output for this endpoint. The effective value is OR'd with the workspace-level setting: an endpoint cannot re-enable capture that the workspace disabled.
        /// </summary>
        [Output("disableOutputCapture")]
        public Output<bool?> DisableOutputCapture { get; private set; } = null!;

        /// <summary>
        /// Hide 'Connect via Web CLI' for this endpoint (cli endpoints only).
        /// </summary>
        [Output("disableWebCli")]
        public Output<bool?> DisableWebCli { get; private set; } = null!;

        /// <summary>
        /// Provisioning status of the service exposure.
        /// </summary>
        [Output("exposeStatus")]
        public Output<string?> ExposeStatus { get; private set; } = null!;

        /// <summary>
        /// How the endpoint is exposed (e.g. LoadBalancer).
        /// </summary>
        [Output("exposeType")]
        public Output<string?> ExposeType { get; private set; } = null!;

        /// <summary>
        /// Whether the endpoint is exposed as a service.
        /// </summary>
        [Output("exposed")]
        public Output<bool?> Exposed { get; private set; } = null!;

        [Output("groups")]
        public Output<ImmutableArray<string>> Groups { get; private set; } = null!;

        [Output("idleTimeout")]
        public Output<string?> IdleTimeout { get; private set; } = null!;

        /// <summary>
        /// Whether Just-In-Time access approval is enabled.
        /// </summary>
        [Output("isJitEnabled")]
        public Output<bool?> IsJitEnabled { get; private set; } = null!;

        /// <summary>
        /// Emails of users who can approve Just-In-Time access requests.
        /// </summary>
        [Output("jitApprovers")]
        public Output<ImmutableArray<string>> JitApprovers { get; private set; } = null!;

        /// <summary>
        /// Which access paths require Just-In-Time approval: session, script, or both.
        /// </summary>
        [Output("jitMode")]
        public Output<string?> JitMode { get; private set; } = null!;

        /// <summary>
        /// Require multiple approvers for Just-In-Time access requests.
        /// </summary>
        [Output("jitMultiApprover")]
        public Output<bool?> JitMultiApprover { get; private set; } = null!;

        /// <summary>
        /// Number of approvals required when multi-approver is enabled.
        /// </summary>
        [Output("jitTotalApprovers")]
        public Output<int?> JitTotalApprovers { get; private set; } = null!;

        [Output("memory")]
        public Output<string?> Memory { get; private set; } = null!;

        /// <summary>
        /// The name of the endpoint to create.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("pauseTimeout")]
        public Output<string?> PauseTimeout { get; private set; } = null!;

        /// <summary>
        /// The resource (by name) this endpoint grants access to.
        /// </summary>
        [Output("resource")]
        public Output<string> Resource { get; private set; } = null!;

        /// <summary>
        /// Whether the endpoint is only accessible via script.
        /// </summary>
        [Output("scriptOnlyAccess")]
        public Output<bool?> ScriptOnlyAccess { get; private set; } = null!;

        /// <summary>
        /// Current lifecycle status of the endpoint.
        /// </summary>
        [Output("status")]
        public Output<string?> Status { get; private set; } = null!;

        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        /// <summary>
        /// Time-to-live for the endpoint, e.g. 8h, 7d, 90d.
        /// </summary>
        [Output("ttl")]
        public Output<string?> Ttl { get; private set; } = null!;

        /// <summary>
        /// The type of session: direct, client, cli, or services.
        /// </summary>
        [Output("type")]
        public Output<string?> Type { get; private set; } = null!;

        [Output("users")]
        public Output<ImmutableArray<string>> Users { get; private set; } = null!;


        /// <summary>
        /// Create a Endpoint resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Endpoint(string name, EndpointArgs args, CustomResourceOptions? options = null)
            : base("adaptive:index:Endpoint", name, args ?? new EndpointArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Endpoint(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("adaptive:index:Endpoint", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/adaptive-scale/pulumi-adaptive",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Endpoint resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Endpoint Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Endpoint(name, id, options);
        }
    }

    public sealed class EndpointArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The authorization (by name) to apply to this endpoint.
        /// </summary>
        [Input("authorization")]
        public Input<string>? Authorization { get; set; }

        /// <summary>
        /// Automatically approve Just-In-Time access requests.
        /// </summary>
        [Input("autoApproval")]
        public Input<bool>? AutoApproval { get; set; }

        [Input("cluster")]
        public Input<string>? Cluster { get; set; }

        [Input("cpu")]
        public Input<string>? Cpu { get; set; }

        /// <summary>
        /// Hide Data Studio for this endpoint (cli endpoints only).
        /// </summary>
        [Input("disableDataStudio")]
        public Input<bool>? DisableDataStudio { get; set; }

        /// <summary>
        /// Do not retain terminal output for this endpoint. The effective value is OR'd with the workspace-level setting: an endpoint cannot re-enable capture that the workspace disabled.
        /// </summary>
        [Input("disableOutputCapture")]
        public Input<bool>? DisableOutputCapture { get; set; }

        /// <summary>
        /// Hide 'Connect via Web CLI' for this endpoint (cli endpoints only).
        /// </summary>
        [Input("disableWebCli")]
        public Input<bool>? DisableWebCli { get; set; }

        [Input("groups")]
        private InputList<string>? _groups;
        public InputList<string> Groups
        {
            get => _groups ?? (_groups = new InputList<string>());
            set => _groups = value;
        }

        [Input("idleTimeout")]
        public Input<string>? IdleTimeout { get; set; }

        /// <summary>
        /// Whether Just-In-Time access approval is enabled.
        /// </summary>
        [Input("isJitEnabled")]
        public Input<bool>? IsJitEnabled { get; set; }

        [Input("jitApprovers")]
        private InputList<string>? _jitApprovers;

        /// <summary>
        /// Emails of users who can approve Just-In-Time access requests.
        /// </summary>
        public InputList<string> JitApprovers
        {
            get => _jitApprovers ?? (_jitApprovers = new InputList<string>());
            set => _jitApprovers = value;
        }

        /// <summary>
        /// Which access paths require Just-In-Time approval: session, script, or both.
        /// </summary>
        [Input("jitMode")]
        public Input<string>? JitMode { get; set; }

        /// <summary>
        /// Require multiple approvers for Just-In-Time access requests.
        /// </summary>
        [Input("jitMultiApprover")]
        public Input<bool>? JitMultiApprover { get; set; }

        /// <summary>
        /// Number of approvals required when multi-approver is enabled.
        /// </summary>
        [Input("jitTotalApprovers")]
        public Input<int>? JitTotalApprovers { get; set; }

        [Input("memory")]
        public Input<string>? Memory { get; set; }

        /// <summary>
        /// The name of the endpoint to create.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("pauseTimeout")]
        public Input<string>? PauseTimeout { get; set; }

        /// <summary>
        /// The resource (by name) this endpoint grants access to.
        /// </summary>
        [Input("resource", required: true)]
        public Input<string> Resource { get; set; } = null!;

        /// <summary>
        /// Whether the endpoint is only accessible via script.
        /// </summary>
        [Input("scriptOnlyAccess")]
        public Input<bool>? ScriptOnlyAccess { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// Time-to-live for the endpoint, e.g. 8h, 7d, 90d.
        /// </summary>
        [Input("ttl")]
        public Input<string>? Ttl { get; set; }

        /// <summary>
        /// The type of session: direct, client, cli, or services.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("users")]
        private InputList<string>? _users;
        public InputList<string> Users
        {
            get => _users ?? (_users = new InputList<string>());
            set => _users = value;
        }

        public EndpointArgs()
        {
            Type = "direct";
        }
        public static new EndpointArgs Empty => new EndpointArgs();
    }
}
