// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace AdaptiveScale.Adaptive
{
    [AdaptiveResourceType("adaptive:index:Resource")]
    public partial class Resource : global::Pulumi.CustomResource
    {
        [Output("accessKeyId")]
        public Output<string?> AccessKeyId { get; private set; } = null!;

        [Output("annotations")]
        public Output<string?> Annotations { get; private set; } = null!;

        [Output("apiClientId")]
        public Output<string?> ApiClientId { get; private set; } = null!;

        [Output("apiClientSecret")]
        public Output<string?> ApiClientSecret { get; private set; } = null!;

        [Output("apiKey")]
        public Output<string?> ApiKey { get; private set; } = null!;

        [Output("apiServer")]
        public Output<string?> ApiServer { get; private set; } = null!;

        [Output("apiToken")]
        public Output<string?> ApiToken { get; private set; } = null!;

        [Output("appId")]
        public Output<string?> AppId { get; private set; } = null!;

        [Output("appKey")]
        public Output<string?> AppKey { get; private set; } = null!;

        [Output("applicationId")]
        public Output<string?> ApplicationId { get; private set; } = null!;

        [Output("applicationName")]
        public Output<string?> ApplicationName { get; private set; } = null!;

        [Output("arn")]
        public Output<string?> Arn { get; private set; } = null!;

        [Output("awsArn")]
        public Output<string?> AwsArn { get; private set; } = null!;

        [Output("awsRegionName")]
        public Output<string?> AwsRegionName { get; private set; } = null!;

        [Output("clientId")]
        public Output<string?> ClientId { get; private set; } = null!;

        [Output("clientSecret")]
        public Output<string?> ClientSecret { get; private set; } = null!;

        [Output("clientcert")]
        public Output<string?> Clientcert { get; private set; } = null!;

        [Output("clusterCert")]
        public Output<string?> ClusterCert { get; private set; } = null!;

        [Output("clusterToken")]
        public Output<string?> ClusterToken { get; private set; } = null!;

        [Output("createIfNotExists")]
        public Output<bool?> CreateIfNotExists { get; private set; } = null!;

        [Output("databaseAccount")]
        public Output<string?> DatabaseAccount { get; private set; } = null!;

        [Output("databaseName")]
        public Output<string?> DatabaseName { get; private set; } = null!;

        [Output("databasePassword")]
        public Output<string?> DatabasePassword { get; private set; } = null!;

        [Output("databaseUsername")]
        public Output<string?> DatabaseUsername { get; private set; } = null!;

        [Output("ddApiKey")]
        public Output<string?> DdApiKey { get; private set; } = null!;

        [Output("ddSite")]
        public Output<string?> DdSite { get; private set; } = null!;

        /// <summary>
        /// The default cluster the resource is deployed to.
        /// </summary>
        [Output("defaultCluster")]
        public Output<string?> DefaultCluster { get; private set; } = null!;

        [Output("defaultUser")]
        public Output<string?> DefaultUser { get; private set; } = null!;

        [Output("domain")]
        public Output<string?> Domain { get; private set; } = null!;

        [Output("host")]
        public Output<string?> Host { get; private set; } = null!;

        [Output("hostname")]
        public Output<string?> Hostname { get; private set; } = null!;

        [Output("hosts")]
        public Output<ImmutableArray<string>> Hosts { get; private set; } = null!;

        [Output("image")]
        public Output<string?> Image { get; private set; } = null!;

        [Output("index")]
        public Output<string?> Index { get; private set; } = null!;

        [Output("key")]
        public Output<string?> Key { get; private set; } = null!;

        [Output("keyFile")]
        public Output<string?> KeyFile { get; private set; } = null!;

        [Output("loginUrl")]
        public Output<string?> LoginUrl { get; private set; } = null!;

        /// <summary>
        /// Name of the Adaptive resource.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("namespace")]
        public Output<string?> Namespace { get; private set; } = null!;

        [Output("networkId")]
        public Output<string?> NetworkId { get; private set; } = null!;

        [Output("nodeAffinity")]
        public Output<string?> NodeAffinity { get; private set; } = null!;

        [Output("nodeSelector")]
        public Output<string?> NodeSelector { get; private set; } = null!;

        [Output("organizationId")]
        public Output<string?> OrganizationId { get; private set; } = null!;

        [Output("password")]
        public Output<string?> Password { get; private set; } = null!;

        [Output("port")]
        public Output<string?> Port { get; private set; } = null!;

        [Output("privateKey")]
        public Output<string?> PrivateKey { get; private set; } = null!;

        [Output("projectId")]
        public Output<string?> ProjectId { get; private set; } = null!;

        [Output("protocol")]
        public Output<string?> Protocol { get; private set; } = null!;

        [Output("publicKey")]
        public Output<string?> PublicKey { get; private set; } = null!;

        [Output("region")]
        public Output<string?> Region { get; private set; } = null!;

        [Output("regionName")]
        public Output<string?> RegionName { get; private set; } = null!;

        [Output("role")]
        public Output<string?> Role { get; private set; } = null!;

        [Output("rootCert")]
        public Output<string?> RootCert { get; private set; } = null!;

        [Output("schema")]
        public Output<string?> Schema { get; private set; } = null!;

        [Output("secretAccessKey")]
        public Output<string?> SecretAccessKey { get; private set; } = null!;

        [Output("secretId")]
        public Output<string?> SecretId { get; private set; } = null!;

        [Output("serviceAccountName")]
        public Output<string?> ServiceAccountName { get; private set; } = null!;

        [Output("sharedSecret")]
        public Output<string?> SharedSecret { get; private set; } = null!;

        [Output("sslMode")]
        public Output<string?> SslMode { get; private set; } = null!;

        [Output("subSystemName")]
        public Output<string?> SubSystemName { get; private set; } = null!;

        /// <summary>
        /// Optional tags.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        [Output("tenantId")]
        public Output<string?> TenantId { get; private set; } = null!;

        [Output("tlsCertFile")]
        public Output<string?> TlsCertFile { get; private set; } = null!;

        [Output("tlsKeyFile")]
        public Output<string?> TlsKeyFile { get; private set; } = null!;

        [Output("tlsRootCert")]
        public Output<string?> TlsRootCert { get; private set; } = null!;

        [Output("tokenId")]
        public Output<string?> TokenId { get; private set; } = null!;

        [Output("tolerations")]
        public Output<string?> Tolerations { get; private set; } = null!;

        /// <summary>
        /// Type of the Adaptive resource (integration), e.g. postgres, mysql, mongodb, ssh, kubernetes, aws, gcp, azure, snowflake.
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        [Output("uri")]
        public Output<string?> Uri { get; private set; } = null!;

        [Output("url")]
        public Output<string?> Url { get; private set; } = null!;

        [Output("urls")]
        public Output<string?> Urls { get; private set; } = null!;

        [Output("useProxy")]
        public Output<bool?> UseProxy { get; private set; } = null!;

        [Output("useServiceAccount")]
        public Output<bool?> UseServiceAccount { get; private set; } = null!;

        [Output("useTenant")]
        public Output<bool?> UseTenant { get; private set; } = null!;

        [Output("username")]
        public Output<string?> Username { get; private set; } = null!;

        [Output("version")]
        public Output<string?> Version { get; private set; } = null!;

        [Output("warehouse")]
        public Output<string?> Warehouse { get; private set; } = null!;

        [Output("webhookUrl")]
        public Output<string?> WebhookUrl { get; private set; } = null!;

        [Output("webuiPort")]
        public Output<string?> WebuiPort { get; private set; } = null!;


        /// <summary>
        /// Create a Resource resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Resource(string name, ResourceArgs args, CustomResourceOptions? options = null)
            : base("adaptive:index:Resource", name, args ?? new ResourceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Resource(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("adaptive:index:Resource", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/adaptive-scale/pulumi-adaptive",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Resource resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Resource Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Resource(name, id, options);
        }
    }

    public sealed class ResourceArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessKeyId")]
        public Input<string>? AccessKeyId { get; set; }

        [Input("annotations")]
        public Input<string>? Annotations { get; set; }

        [Input("apiClientId")]
        public Input<string>? ApiClientId { get; set; }

        [Input("apiClientSecret")]
        public Input<string>? ApiClientSecret { get; set; }

        [Input("apiKey")]
        public Input<string>? ApiKey { get; set; }

        [Input("apiServer")]
        public Input<string>? ApiServer { get; set; }

        [Input("apiToken")]
        public Input<string>? ApiToken { get; set; }

        [Input("appId")]
        public Input<string>? AppId { get; set; }

        [Input("appKey")]
        public Input<string>? AppKey { get; set; }

        [Input("applicationId")]
        public Input<string>? ApplicationId { get; set; }

        [Input("applicationName")]
        public Input<string>? ApplicationName { get; set; }

        [Input("arn")]
        public Input<string>? Arn { get; set; }

        [Input("awsArn")]
        public Input<string>? AwsArn { get; set; }

        [Input("awsRegionName")]
        public Input<string>? AwsRegionName { get; set; }

        [Input("clientId")]
        public Input<string>? ClientId { get; set; }

        [Input("clientSecret")]
        public Input<string>? ClientSecret { get; set; }

        [Input("clientcert")]
        public Input<string>? Clientcert { get; set; }

        [Input("clusterCert")]
        public Input<string>? ClusterCert { get; set; }

        [Input("clusterToken")]
        public Input<string>? ClusterToken { get; set; }

        [Input("createIfNotExists")]
        public Input<bool>? CreateIfNotExists { get; set; }

        [Input("databaseAccount")]
        public Input<string>? DatabaseAccount { get; set; }

        [Input("databaseName")]
        public Input<string>? DatabaseName { get; set; }

        [Input("databasePassword")]
        public Input<string>? DatabasePassword { get; set; }

        [Input("databaseUsername")]
        public Input<string>? DatabaseUsername { get; set; }

        [Input("ddApiKey")]
        public Input<string>? DdApiKey { get; set; }

        [Input("ddSite")]
        public Input<string>? DdSite { get; set; }

        /// <summary>
        /// The default cluster the resource is deployed to.
        /// </summary>
        [Input("defaultCluster")]
        public Input<string>? DefaultCluster { get; set; }

        [Input("defaultUser")]
        public Input<string>? DefaultUser { get; set; }

        [Input("domain")]
        public Input<string>? Domain { get; set; }

        [Input("host")]
        public Input<string>? Host { get; set; }

        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        [Input("hosts")]
        private InputList<string>? _hosts;
        public InputList<string> Hosts
        {
            get => _hosts ?? (_hosts = new InputList<string>());
            set => _hosts = value;
        }

        [Input("image")]
        public Input<string>? Image { get; set; }

        [Input("index")]
        public Input<string>? Index { get; set; }

        [Input("key")]
        public Input<string>? Key { get; set; }

        [Input("keyFile")]
        public Input<string>? KeyFile { get; set; }

        [Input("loginUrl")]
        public Input<string>? LoginUrl { get; set; }

        /// <summary>
        /// Name of the Adaptive resource.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        [Input("networkId")]
        public Input<string>? NetworkId { get; set; }

        [Input("nodeAffinity")]
        public Input<string>? NodeAffinity { get; set; }

        [Input("nodeSelector")]
        public Input<string>? NodeSelector { get; set; }

        [Input("organizationId")]
        public Input<string>? OrganizationId { get; set; }

        [Input("password")]
        public Input<string>? Password { get; set; }

        [Input("port")]
        public Input<string>? Port { get; set; }

        [Input("privateKey")]
        public Input<string>? PrivateKey { get; set; }

        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        [Input("protocol")]
        public Input<string>? Protocol { get; set; }

        [Input("publicKey")]
        public Input<string>? PublicKey { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("regionName")]
        public Input<string>? RegionName { get; set; }

        [Input("role")]
        public Input<string>? Role { get; set; }

        [Input("rootCert")]
        public Input<string>? RootCert { get; set; }

        [Input("schema")]
        public Input<string>? Schema { get; set; }

        [Input("secretAccessKey")]
        public Input<string>? SecretAccessKey { get; set; }

        [Input("secretId")]
        public Input<string>? SecretId { get; set; }

        [Input("serviceAccountName")]
        public Input<string>? ServiceAccountName { get; set; }

        [Input("sharedSecret")]
        public Input<string>? SharedSecret { get; set; }

        [Input("sslMode")]
        public Input<string>? SslMode { get; set; }

        [Input("subSystemName")]
        public Input<string>? SubSystemName { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Optional tags.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        [Input("tlsCertFile")]
        public Input<string>? TlsCertFile { get; set; }

        [Input("tlsKeyFile")]
        public Input<string>? TlsKeyFile { get; set; }

        [Input("tlsRootCert")]
        public Input<string>? TlsRootCert { get; set; }

        [Input("tokenId")]
        public Input<string>? TokenId { get; set; }

        [Input("tolerations")]
        public Input<string>? Tolerations { get; set; }

        /// <summary>
        /// Type of the Adaptive resource (integration), e.g. postgres, mysql, mongodb, ssh, kubernetes, aws, gcp, azure, snowflake.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        [Input("uri")]
        public Input<string>? Uri { get; set; }

        [Input("url")]
        public Input<string>? Url { get; set; }

        [Input("urls")]
        public Input<string>? Urls { get; set; }

        [Input("useProxy")]
        public Input<bool>? UseProxy { get; set; }

        [Input("useServiceAccount")]
        public Input<bool>? UseServiceAccount { get; set; }

        [Input("useTenant")]
        public Input<bool>? UseTenant { get; set; }

        [Input("username")]
        public Input<string>? Username { get; set; }

        [Input("version")]
        public Input<string>? Version { get; set; }

        [Input("warehouse")]
        public Input<string>? Warehouse { get; set; }

        [Input("webhookUrl")]
        public Input<string>? WebhookUrl { get; set; }

        [Input("webuiPort")]
        public Input<string>? WebuiPort { get; set; }

        public ResourceArgs()
        {
        }
        public static new ResourceArgs Empty => new ResourceArgs();
    }
}
