// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace AdaptiveScale.Adaptive
{
    [AdaptiveResourceType("adaptive:index:Schedule")]
    public partial class Schedule : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether the schedule covers the whole day (start/end times are ignored).
        /// </summary>
        [Output("allDay")]
        public Output<bool?> AllDay { get; private set; } = null!;

        /// <summary>
        /// An optional description of the schedule.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Day of month (1-31) the window closes, for monthly schedules.
        /// </summary>
        [Output("endDay")]
        public Output<int?> EndDay { get; private set; } = null!;

        /// <summary>
        /// Hour (0-23) the window closes.
        /// </summary>
        [Output("endHour")]
        public Output<int?> EndHour { get; private set; } = null!;

        /// <summary>
        /// Minute (0-59) the window closes.
        /// </summary>
        [Output("endMinute")]
        public Output<int?> EndMinute { get; private set; } = null!;

        /// <summary>
        /// Names of endpoints the schedule applies to.
        /// </summary>
        [Output("endpoints")]
        public Output<ImmutableArray<string>> Endpoints { get; private set; } = null!;

        /// <summary>
        /// RFC3339 timestamp after which the schedule no longer applies.
        /// </summary>
        [Output("expiresAt")]
        public Output<string?> ExpiresAt { get; private set; } = null!;

        /// <summary>
        /// Whether the schedule is active.
        /// </summary>
        [Output("isActive")]
        public Output<bool?> IsActive { get; private set; } = null!;

        /// <summary>
        /// Maximum access duration in minutes granted by an auto-approval.
        /// </summary>
        [Output("maxAccessTime")]
        public Output<int?> MaxAccessTime { get; private set; } = null!;

        /// <summary>
        /// Name of the schedule. Note: the Adaptive API upserts schedules by name, so creating a schedule whose name already exists adopts the existing schedule.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// What the schedule does inside its window: autoapprove or autoreject.
        /// </summary>
        [Output("operationType")]
        public Output<string?> OperationType { get; private set; } = null!;

        /// <summary>
        /// The schedule pattern: weekdays, weekends, everyday, monthly, specific, or custom.
        /// </summary>
        [Output("scheduleType")]
        public Output<string> ScheduleType { get; private set; } = null!;

        /// <summary>
        /// RFC3339 dates for a specific-dates schedule.
        /// </summary>
        [Output("specificDates")]
        public Output<ImmutableArray<string>> SpecificDates { get; private set; } = null!;

        /// <summary>
        /// Day of month (1-31) the window opens, for monthly schedules.
        /// </summary>
        [Output("startDay")]
        public Output<int?> StartDay { get; private set; } = null!;

        /// <summary>
        /// Hour (0-23) the window opens.
        /// </summary>
        [Output("startHour")]
        public Output<int?> StartHour { get; private set; } = null!;

        /// <summary>
        /// Minute (0-59) the window opens.
        /// </summary>
        [Output("startMinute")]
        public Output<int?> StartMinute { get; private set; } = null!;

        /// <summary>
        /// Names of groups the schedule applies to.
        /// </summary>
        [Output("teams")]
        public Output<ImmutableArray<string>> Teams { get; private set; } = null!;

        /// <summary>
        /// IANA timezone for the schedule window. Empty inherits the workspace default.
        /// </summary>
        [Output("timezone")]
        public Output<string?> Timezone { get; private set; } = null!;

        /// <summary>
        /// Last time the schedule was modified.
        /// </summary>
        [Output("updatedAt")]
        public Output<string?> UpdatedAt { get; private set; } = null!;

        /// <summary>
        /// Emails of users the schedule applies to.
        /// </summary>
        [Output("users")]
        public Output<ImmutableArray<string>> Users { get; private set; } = null!;

        /// <summary>
        /// Weekday names for a custom schedule (e.g. monday, tuesday).
        /// </summary>
        [Output("weekdays")]
        public Output<ImmutableArray<string>> Weekdays { get; private set; } = null!;


        /// <summary>
        /// Create a Schedule resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Schedule(string name, ScheduleArgs args, CustomResourceOptions? options = null)
            : base("adaptive:index:Schedule", name, args ?? new ScheduleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Schedule(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("adaptive:index:Schedule", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/adaptive-scale/pulumi-adaptive",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Schedule resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Schedule Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Schedule(name, id, options);
        }
    }

    public sealed class ScheduleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the schedule covers the whole day (start/end times are ignored).
        /// </summary>
        [Input("allDay")]
        public Input<bool>? AllDay { get; set; }

        /// <summary>
        /// An optional description of the schedule.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Day of month (1-31) the window closes, for monthly schedules.
        /// </summary>
        [Input("endDay")]
        public Input<int>? EndDay { get; set; }

        /// <summary>
        /// Hour (0-23) the window closes.
        /// </summary>
        [Input("endHour")]
        public Input<int>? EndHour { get; set; }

        /// <summary>
        /// Minute (0-59) the window closes.
        /// </summary>
        [Input("endMinute")]
        public Input<int>? EndMinute { get; set; }

        [Input("endpoints")]
        private InputList<string>? _endpoints;

        /// <summary>
        /// Names of endpoints the schedule applies to.
        /// </summary>
        public InputList<string> Endpoints
        {
            get => _endpoints ?? (_endpoints = new InputList<string>());
            set => _endpoints = value;
        }

        /// <summary>
        /// RFC3339 timestamp after which the schedule no longer applies.
        /// </summary>
        [Input("expiresAt")]
        public Input<string>? ExpiresAt { get; set; }

        /// <summary>
        /// Whether the schedule is active.
        /// </summary>
        [Input("isActive")]
        public Input<bool>? IsActive { get; set; }

        /// <summary>
        /// Maximum access duration in minutes granted by an auto-approval.
        /// </summary>
        [Input("maxAccessTime")]
        public Input<int>? MaxAccessTime { get; set; }

        /// <summary>
        /// Name of the schedule. Note: the Adaptive API upserts schedules by name, so creating a schedule whose name already exists adopts the existing schedule.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// What the schedule does inside its window: autoapprove or autoreject.
        /// </summary>
        [Input("operationType")]
        public Input<string>? OperationType { get; set; }

        /// <summary>
        /// The schedule pattern: weekdays, weekends, everyday, monthly, specific, or custom.
        /// </summary>
        [Input("scheduleType", required: true)]
        public Input<string> ScheduleType { get; set; } = null!;

        [Input("specificDates")]
        private InputList<string>? _specificDates;

        /// <summary>
        /// RFC3339 dates for a specific-dates schedule.
        /// </summary>
        public InputList<string> SpecificDates
        {
            get => _specificDates ?? (_specificDates = new InputList<string>());
            set => _specificDates = value;
        }

        /// <summary>
        /// Day of month (1-31) the window opens, for monthly schedules.
        /// </summary>
        [Input("startDay")]
        public Input<int>? StartDay { get; set; }

        /// <summary>
        /// Hour (0-23) the window opens.
        /// </summary>
        [Input("startHour")]
        public Input<int>? StartHour { get; set; }

        /// <summary>
        /// Minute (0-59) the window opens.
        /// </summary>
        [Input("startMinute")]
        public Input<int>? StartMinute { get; set; }

        [Input("teams")]
        private InputList<string>? _teams;

        /// <summary>
        /// Names of groups the schedule applies to.
        /// </summary>
        public InputList<string> Teams
        {
            get => _teams ?? (_teams = new InputList<string>());
            set => _teams = value;
        }

        /// <summary>
        /// IANA timezone for the schedule window. Empty inherits the workspace default.
        /// </summary>
        [Input("timezone")]
        public Input<string>? Timezone { get; set; }

        [Input("users")]
        private InputList<string>? _users;

        /// <summary>
        /// Emails of users the schedule applies to.
        /// </summary>
        public InputList<string> Users
        {
            get => _users ?? (_users = new InputList<string>());
            set => _users = value;
        }

        [Input("weekdays")]
        private InputList<string>? _weekdays;

        /// <summary>
        /// Weekday names for a custom schedule (e.g. monday, tuesday).
        /// </summary>
        public InputList<string> Weekdays
        {
            get => _weekdays ?? (_weekdays = new InputList<string>());
            set => _weekdays = value;
        }

        public ScheduleArgs()
        {
            OperationType = "autoapprove";
        }
        public static new ScheduleArgs Empty => new ScheduleArgs();
    }
}
