// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace AdaptiveScale.Adaptive
{
    public static class Config
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("adaptive");

        private static readonly __Value<string?> _serviceToken = new __Value<string?>(() => __config.Get("serviceToken") ?? Utilities.GetEnv("ADAPTIVE_SVC_TOKEN") ?? "");
        /// <summary>
        /// Service account token for authenticating with the Adaptive service. If not provided, the provider reads the token from the default adaptive-cli location (~/.adaptive/token).
        /// </summary>
        public static string? ServiceToken
        {
            get => _serviceToken.Get();
            set => _serviceToken.Set(value);
        }

        private static readonly __Value<string?> _workspaceUrl = new __Value<string?>(() => __config.Get("workspaceUrl") ?? Utilities.GetEnv("ADAPTIVE_URL") ?? "https://app.adaptive.live");
        /// <summary>
        /// The Adaptive workspace URL. Defaults to https://app.adaptive.live.
        /// </summary>
        public static string? WorkspaceUrl
        {
            get => _workspaceUrl.Get();
            set => _workspaceUrl.Set(value);
        }

    }
}
