// *** WARNING: this file was generated by pulumi-adaptive-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("adaptive");

/**
 * Service account token for authenticating with the Adaptive service. If not provided, the provider reads the token from the default adaptive-cli location (~/.adaptive/token).
 */
export declare const serviceToken: string;
Object.defineProperty(exports, "serviceToken", {
    get() {
        return __config.get("serviceToken") ?? (utilities.getEnv("ADAPTIVE_SVC_TOKEN") || "");
    },
    enumerable: true,
});

/**
 * The Adaptive workspace URL. Defaults to https://app.adaptive.live.
 */
export declare const workspaceUrl: string;
Object.defineProperty(exports, "workspaceUrl", {
    get() {
        return __config.get("workspaceUrl") ?? (utilities.getEnv("ADAPTIVE_URL") || "https://app.adaptive.live");
    },
    enumerable: true,
});

