// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace AdaptiveScale.Adaptive.Outputs
{

    [OutputType]
    public sealed class DataProtectionColumnMask
    {
        public readonly string ColumnName;
        public readonly string MaskingType;

        [OutputConstructor]
        private DataProtectionColumnMask(
            string columnName,

            string maskingType)
        {
            ColumnName = columnName;
            MaskingType = maskingType;
        }
    }
}
