// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace AdaptiveScale.Adaptive.Outputs
{

    [OutputType]
    public sealed class DataProtectionMask
    {
        public readonly string DatabaseName;
        public readonly ImmutableArray<Outputs.DataProtectionTable> Tables;

        [OutputConstructor]
        private DataProtectionMask(
            string databaseName,

            ImmutableArray<Outputs.DataProtectionTable> tables)
        {
            DatabaseName = databaseName;
            Tables = tables;
        }
    }
}
