// Code generated by pulumi-adaptive-gen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package adaptive

import (
	"context"
	"reflect"

	"errors"
	"github.com/adaptive-scale/pulumi-adaptive/sdk/go/adaptive/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type MSTeamsWorkflow struct {
	pulumi.CustomResourceState

	// Name of the MS Teams workflow integration.
	Name pulumi.StringOutput `pulumi:"name"`
	// The webhook URL for the MS Teams workflow.
	WebhookUrl pulumi.StringOutput `pulumi:"webhookUrl"`
}

// NewMSTeamsWorkflow registers a new resource with the given unique name, arguments, and options.
func NewMSTeamsWorkflow(ctx *pulumi.Context,
	name string, args *MSTeamsWorkflowArgs, opts ...pulumi.ResourceOption) (*MSTeamsWorkflow, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.WebhookUrl == nil {
		return nil, errors.New("invalid value for required argument 'WebhookUrl'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource MSTeamsWorkflow
	err := ctx.RegisterResource("adaptive:index:MSTeamsWorkflow", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMSTeamsWorkflow gets an existing MSTeamsWorkflow resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMSTeamsWorkflow(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MSTeamsWorkflowState, opts ...pulumi.ResourceOption) (*MSTeamsWorkflow, error) {
	var resource MSTeamsWorkflow
	err := ctx.ReadResource("adaptive:index:MSTeamsWorkflow", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering MSTeamsWorkflow resources.
type msteamsWorkflowState struct {
}

type MSTeamsWorkflowState struct {
}

func (MSTeamsWorkflowState) ElementType() reflect.Type {
	return reflect.TypeOf((*msteamsWorkflowState)(nil)).Elem()
}

type msteamsWorkflowArgs struct {
	// Name of the MS Teams workflow integration.
	Name string `pulumi:"name"`
	// The webhook URL for the MS Teams workflow.
	WebhookUrl string `pulumi:"webhookUrl"`
}

// The set of arguments for constructing a MSTeamsWorkflow resource.
type MSTeamsWorkflowArgs struct {
	// Name of the MS Teams workflow integration.
	Name pulumi.StringInput
	// The webhook URL for the MS Teams workflow.
	WebhookUrl pulumi.StringInput
}

func (MSTeamsWorkflowArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*msteamsWorkflowArgs)(nil)).Elem()
}

type MSTeamsWorkflowInput interface {
	pulumi.Input

	ToMSTeamsWorkflowOutput() MSTeamsWorkflowOutput
	ToMSTeamsWorkflowOutputWithContext(ctx context.Context) MSTeamsWorkflowOutput
}

func (*MSTeamsWorkflow) ElementType() reflect.Type {
	return reflect.TypeOf((**MSTeamsWorkflow)(nil)).Elem()
}

func (i *MSTeamsWorkflow) ToMSTeamsWorkflowOutput() MSTeamsWorkflowOutput {
	return i.ToMSTeamsWorkflowOutputWithContext(context.Background())
}

func (i *MSTeamsWorkflow) ToMSTeamsWorkflowOutputWithContext(ctx context.Context) MSTeamsWorkflowOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MSTeamsWorkflowOutput)
}

// MSTeamsWorkflowArrayInput is an input type that accepts MSTeamsWorkflowArray and MSTeamsWorkflowArrayOutput values.
// You can construct a concrete instance of `MSTeamsWorkflowArrayInput` via:
//
//	MSTeamsWorkflowArray{ MSTeamsWorkflowArgs{...} }
type MSTeamsWorkflowArrayInput interface {
	pulumi.Input

	ToMSTeamsWorkflowArrayOutput() MSTeamsWorkflowArrayOutput
	ToMSTeamsWorkflowArrayOutputWithContext(context.Context) MSTeamsWorkflowArrayOutput
}

type MSTeamsWorkflowArray []MSTeamsWorkflowInput

func (MSTeamsWorkflowArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MSTeamsWorkflow)(nil)).Elem()
}

func (i MSTeamsWorkflowArray) ToMSTeamsWorkflowArrayOutput() MSTeamsWorkflowArrayOutput {
	return i.ToMSTeamsWorkflowArrayOutputWithContext(context.Background())
}

func (i MSTeamsWorkflowArray) ToMSTeamsWorkflowArrayOutputWithContext(ctx context.Context) MSTeamsWorkflowArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MSTeamsWorkflowArrayOutput)
}

// MSTeamsWorkflowMapInput is an input type that accepts MSTeamsWorkflowMap and MSTeamsWorkflowMapOutput values.
// You can construct a concrete instance of `MSTeamsWorkflowMapInput` via:
//
//	MSTeamsWorkflowMap{ "key": MSTeamsWorkflowArgs{...} }
type MSTeamsWorkflowMapInput interface {
	pulumi.Input

	ToMSTeamsWorkflowMapOutput() MSTeamsWorkflowMapOutput
	ToMSTeamsWorkflowMapOutputWithContext(context.Context) MSTeamsWorkflowMapOutput
}

type MSTeamsWorkflowMap map[string]MSTeamsWorkflowInput

func (MSTeamsWorkflowMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MSTeamsWorkflow)(nil)).Elem()
}

func (i MSTeamsWorkflowMap) ToMSTeamsWorkflowMapOutput() MSTeamsWorkflowMapOutput {
	return i.ToMSTeamsWorkflowMapOutputWithContext(context.Background())
}

func (i MSTeamsWorkflowMap) ToMSTeamsWorkflowMapOutputWithContext(ctx context.Context) MSTeamsWorkflowMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MSTeamsWorkflowMapOutput)
}

type MSTeamsWorkflowOutput struct{ *pulumi.OutputState }

func (MSTeamsWorkflowOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**MSTeamsWorkflow)(nil)).Elem()
}

func (o MSTeamsWorkflowOutput) ToMSTeamsWorkflowOutput() MSTeamsWorkflowOutput {
	return o
}

func (o MSTeamsWorkflowOutput) ToMSTeamsWorkflowOutputWithContext(ctx context.Context) MSTeamsWorkflowOutput {
	return o
}

// Name of the MS Teams workflow integration.
func (o MSTeamsWorkflowOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *MSTeamsWorkflow) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The webhook URL for the MS Teams workflow.
func (o MSTeamsWorkflowOutput) WebhookUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *MSTeamsWorkflow) pulumi.StringOutput { return v.WebhookUrl }).(pulumi.StringOutput)
}

type MSTeamsWorkflowArrayOutput struct{ *pulumi.OutputState }

func (MSTeamsWorkflowArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MSTeamsWorkflow)(nil)).Elem()
}

func (o MSTeamsWorkflowArrayOutput) ToMSTeamsWorkflowArrayOutput() MSTeamsWorkflowArrayOutput {
	return o
}

func (o MSTeamsWorkflowArrayOutput) ToMSTeamsWorkflowArrayOutputWithContext(ctx context.Context) MSTeamsWorkflowArrayOutput {
	return o
}

func (o MSTeamsWorkflowArrayOutput) Index(i pulumi.IntInput) MSTeamsWorkflowOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *MSTeamsWorkflow {
		return vs[0].([]*MSTeamsWorkflow)[vs[1].(int)]
	}).(MSTeamsWorkflowOutput)
}

type MSTeamsWorkflowMapOutput struct{ *pulumi.OutputState }

func (MSTeamsWorkflowMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MSTeamsWorkflow)(nil)).Elem()
}

func (o MSTeamsWorkflowMapOutput) ToMSTeamsWorkflowMapOutput() MSTeamsWorkflowMapOutput {
	return o
}

func (o MSTeamsWorkflowMapOutput) ToMSTeamsWorkflowMapOutputWithContext(ctx context.Context) MSTeamsWorkflowMapOutput {
	return o
}

func (o MSTeamsWorkflowMapOutput) MapIndex(k pulumi.StringInput) MSTeamsWorkflowOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *MSTeamsWorkflow {
		return vs[0].(map[string]*MSTeamsWorkflow)[vs[1].(string)]
	}).(MSTeamsWorkflowOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MSTeamsWorkflowInput)(nil)).Elem(), &MSTeamsWorkflow{})
	pulumi.RegisterInputType(reflect.TypeOf((*MSTeamsWorkflowArrayInput)(nil)).Elem(), MSTeamsWorkflowArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*MSTeamsWorkflowMapInput)(nil)).Elem(), MSTeamsWorkflowMap{})
	pulumi.RegisterOutputType(MSTeamsWorkflowOutput{})
	pulumi.RegisterOutputType(MSTeamsWorkflowArrayOutput{})
	pulumi.RegisterOutputType(MSTeamsWorkflowMapOutput{})
}
