// Code generated by pulumi-adaptive-gen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package adaptive

import (
	"context"
	"reflect"

	"github.com/adaptive-scale/pulumi-adaptive/sdk/go/adaptive/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Provider struct {
	pulumi.ProviderResourceState

	// Service account token for authenticating with the Adaptive service. If not provided, the provider reads the token from the default adaptive-cli location (~/.adaptive/token).
	ServiceToken pulumi.StringPtrOutput `pulumi:"serviceToken"`
	// The Adaptive workspace URL. Defaults to https://app.adaptive.live.
	WorkspaceUrl pulumi.StringPtrOutput `pulumi:"workspaceUrl"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.ServiceToken == nil {
		if d := internal.GetEnvOrDefault("", nil, "ADAPTIVE_SVC_TOKEN"); d != nil {
			args.ServiceToken = pulumi.StringPtr(d.(string))
		}
	}
	if args.WorkspaceUrl == nil {
		if d := internal.GetEnvOrDefault("https://app.adaptive.live", nil, "ADAPTIVE_URL"); d != nil {
			args.WorkspaceUrl = pulumi.StringPtr(d.(string))
		}
	}
	if args.ServiceToken != nil {
		args.ServiceToken = pulumi.ToSecret(args.ServiceToken).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"serviceToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:adaptive", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// Service account token for authenticating with the Adaptive service. If not provided, the provider reads the token from the default adaptive-cli location (~/.adaptive/token).
	ServiceToken *string `pulumi:"serviceToken"`
	// The Adaptive workspace URL. Defaults to https://app.adaptive.live.
	WorkspaceUrl *string `pulumi:"workspaceUrl"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// Service account token for authenticating with the Adaptive service. If not provided, the provider reads the token from the default adaptive-cli location (~/.adaptive/token).
	ServiceToken pulumi.StringPtrInput
	// The Adaptive workspace URL. Defaults to https://app.adaptive.live.
	WorkspaceUrl pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// Service account token for authenticating with the Adaptive service. If not provided, the provider reads the token from the default adaptive-cli location (~/.adaptive/token).
func (o ProviderOutput) ServiceToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ServiceToken }).(pulumi.StringPtrOutput)
}

// The Adaptive workspace URL. Defaults to https://app.adaptive.live.
func (o ProviderOutput) WorkspaceUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.WorkspaceUrl }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
