// Code generated by pulumi-adaptive-gen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package adaptive

import (
	"context"
	"reflect"

	"github.com/adaptive-scale/pulumi-adaptive/sdk/go/adaptive/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type DataProtectionColumnMask struct {
	ColumnName  string `pulumi:"columnName"`
	MaskingType string `pulumi:"maskingType"`
}

// DataProtectionColumnMaskInput is an input type that accepts DataProtectionColumnMaskArgs and DataProtectionColumnMaskOutput values.
// You can construct a concrete instance of `DataProtectionColumnMaskInput` via:
//
//	DataProtectionColumnMaskArgs{...}
type DataProtectionColumnMaskInput interface {
	pulumi.Input

	ToDataProtectionColumnMaskOutput() DataProtectionColumnMaskOutput
	ToDataProtectionColumnMaskOutputWithContext(context.Context) DataProtectionColumnMaskOutput
}

type DataProtectionColumnMaskArgs struct {
	ColumnName  pulumi.StringInput `pulumi:"columnName"`
	MaskingType pulumi.StringInput `pulumi:"maskingType"`
}

func (DataProtectionColumnMaskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DataProtectionColumnMask)(nil)).Elem()
}

func (i DataProtectionColumnMaskArgs) ToDataProtectionColumnMaskOutput() DataProtectionColumnMaskOutput {
	return i.ToDataProtectionColumnMaskOutputWithContext(context.Background())
}

func (i DataProtectionColumnMaskArgs) ToDataProtectionColumnMaskOutputWithContext(ctx context.Context) DataProtectionColumnMaskOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataProtectionColumnMaskOutput)
}

// DataProtectionColumnMaskArrayInput is an input type that accepts DataProtectionColumnMaskArray and DataProtectionColumnMaskArrayOutput values.
// You can construct a concrete instance of `DataProtectionColumnMaskArrayInput` via:
//
//	DataProtectionColumnMaskArray{ DataProtectionColumnMaskArgs{...} }
type DataProtectionColumnMaskArrayInput interface {
	pulumi.Input

	ToDataProtectionColumnMaskArrayOutput() DataProtectionColumnMaskArrayOutput
	ToDataProtectionColumnMaskArrayOutputWithContext(context.Context) DataProtectionColumnMaskArrayOutput
}

type DataProtectionColumnMaskArray []DataProtectionColumnMaskInput

func (DataProtectionColumnMaskArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DataProtectionColumnMask)(nil)).Elem()
}

func (i DataProtectionColumnMaskArray) ToDataProtectionColumnMaskArrayOutput() DataProtectionColumnMaskArrayOutput {
	return i.ToDataProtectionColumnMaskArrayOutputWithContext(context.Background())
}

func (i DataProtectionColumnMaskArray) ToDataProtectionColumnMaskArrayOutputWithContext(ctx context.Context) DataProtectionColumnMaskArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataProtectionColumnMaskArrayOutput)
}

type DataProtectionColumnMaskOutput struct{ *pulumi.OutputState }

func (DataProtectionColumnMaskOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DataProtectionColumnMask)(nil)).Elem()
}

func (o DataProtectionColumnMaskOutput) ToDataProtectionColumnMaskOutput() DataProtectionColumnMaskOutput {
	return o
}

func (o DataProtectionColumnMaskOutput) ToDataProtectionColumnMaskOutputWithContext(ctx context.Context) DataProtectionColumnMaskOutput {
	return o
}

func (o DataProtectionColumnMaskOutput) ColumnName() pulumi.StringOutput {
	return o.ApplyT(func(v DataProtectionColumnMask) string { return v.ColumnName }).(pulumi.StringOutput)
}

func (o DataProtectionColumnMaskOutput) MaskingType() pulumi.StringOutput {
	return o.ApplyT(func(v DataProtectionColumnMask) string { return v.MaskingType }).(pulumi.StringOutput)
}

type DataProtectionColumnMaskArrayOutput struct{ *pulumi.OutputState }

func (DataProtectionColumnMaskArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DataProtectionColumnMask)(nil)).Elem()
}

func (o DataProtectionColumnMaskArrayOutput) ToDataProtectionColumnMaskArrayOutput() DataProtectionColumnMaskArrayOutput {
	return o
}

func (o DataProtectionColumnMaskArrayOutput) ToDataProtectionColumnMaskArrayOutputWithContext(ctx context.Context) DataProtectionColumnMaskArrayOutput {
	return o
}

func (o DataProtectionColumnMaskArrayOutput) Index(i pulumi.IntInput) DataProtectionColumnMaskOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) DataProtectionColumnMask {
		return vs[0].([]DataProtectionColumnMask)[vs[1].(int)]
	}).(DataProtectionColumnMaskOutput)
}

type DataProtectionMask struct {
	DatabaseName string                `pulumi:"databaseName"`
	Tables       []DataProtectionTable `pulumi:"tables"`
}

// DataProtectionMaskInput is an input type that accepts DataProtectionMaskArgs and DataProtectionMaskOutput values.
// You can construct a concrete instance of `DataProtectionMaskInput` via:
//
//	DataProtectionMaskArgs{...}
type DataProtectionMaskInput interface {
	pulumi.Input

	ToDataProtectionMaskOutput() DataProtectionMaskOutput
	ToDataProtectionMaskOutputWithContext(context.Context) DataProtectionMaskOutput
}

type DataProtectionMaskArgs struct {
	DatabaseName pulumi.StringInput            `pulumi:"databaseName"`
	Tables       DataProtectionTableArrayInput `pulumi:"tables"`
}

func (DataProtectionMaskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DataProtectionMask)(nil)).Elem()
}

func (i DataProtectionMaskArgs) ToDataProtectionMaskOutput() DataProtectionMaskOutput {
	return i.ToDataProtectionMaskOutputWithContext(context.Background())
}

func (i DataProtectionMaskArgs) ToDataProtectionMaskOutputWithContext(ctx context.Context) DataProtectionMaskOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataProtectionMaskOutput)
}

// DataProtectionMaskArrayInput is an input type that accepts DataProtectionMaskArray and DataProtectionMaskArrayOutput values.
// You can construct a concrete instance of `DataProtectionMaskArrayInput` via:
//
//	DataProtectionMaskArray{ DataProtectionMaskArgs{...} }
type DataProtectionMaskArrayInput interface {
	pulumi.Input

	ToDataProtectionMaskArrayOutput() DataProtectionMaskArrayOutput
	ToDataProtectionMaskArrayOutputWithContext(context.Context) DataProtectionMaskArrayOutput
}

type DataProtectionMaskArray []DataProtectionMaskInput

func (DataProtectionMaskArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DataProtectionMask)(nil)).Elem()
}

func (i DataProtectionMaskArray) ToDataProtectionMaskArrayOutput() DataProtectionMaskArrayOutput {
	return i.ToDataProtectionMaskArrayOutputWithContext(context.Background())
}

func (i DataProtectionMaskArray) ToDataProtectionMaskArrayOutputWithContext(ctx context.Context) DataProtectionMaskArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataProtectionMaskArrayOutput)
}

type DataProtectionMaskOutput struct{ *pulumi.OutputState }

func (DataProtectionMaskOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DataProtectionMask)(nil)).Elem()
}

func (o DataProtectionMaskOutput) ToDataProtectionMaskOutput() DataProtectionMaskOutput {
	return o
}

func (o DataProtectionMaskOutput) ToDataProtectionMaskOutputWithContext(ctx context.Context) DataProtectionMaskOutput {
	return o
}

func (o DataProtectionMaskOutput) DatabaseName() pulumi.StringOutput {
	return o.ApplyT(func(v DataProtectionMask) string { return v.DatabaseName }).(pulumi.StringOutput)
}

func (o DataProtectionMaskOutput) Tables() DataProtectionTableArrayOutput {
	return o.ApplyT(func(v DataProtectionMask) []DataProtectionTable { return v.Tables }).(DataProtectionTableArrayOutput)
}

type DataProtectionMaskArrayOutput struct{ *pulumi.OutputState }

func (DataProtectionMaskArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DataProtectionMask)(nil)).Elem()
}

func (o DataProtectionMaskArrayOutput) ToDataProtectionMaskArrayOutput() DataProtectionMaskArrayOutput {
	return o
}

func (o DataProtectionMaskArrayOutput) ToDataProtectionMaskArrayOutputWithContext(ctx context.Context) DataProtectionMaskArrayOutput {
	return o
}

func (o DataProtectionMaskArrayOutput) Index(i pulumi.IntInput) DataProtectionMaskOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) DataProtectionMask {
		return vs[0].([]DataProtectionMask)[vs[1].(int)]
	}).(DataProtectionMaskOutput)
}

type DataProtectionTable struct {
	Masked        *bool                      `pulumi:"masked"`
	MaskedColumns []DataProtectionColumnMask `pulumi:"maskedColumns"`
	Schema        *string                    `pulumi:"schema"`
	TableName     string                     `pulumi:"tableName"`
}

// DataProtectionTableInput is an input type that accepts DataProtectionTableArgs and DataProtectionTableOutput values.
// You can construct a concrete instance of `DataProtectionTableInput` via:
//
//	DataProtectionTableArgs{...}
type DataProtectionTableInput interface {
	pulumi.Input

	ToDataProtectionTableOutput() DataProtectionTableOutput
	ToDataProtectionTableOutputWithContext(context.Context) DataProtectionTableOutput
}

type DataProtectionTableArgs struct {
	Masked        pulumi.BoolPtrInput                `pulumi:"masked"`
	MaskedColumns DataProtectionColumnMaskArrayInput `pulumi:"maskedColumns"`
	Schema        pulumi.StringPtrInput              `pulumi:"schema"`
	TableName     pulumi.StringInput                 `pulumi:"tableName"`
}

func (DataProtectionTableArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DataProtectionTable)(nil)).Elem()
}

func (i DataProtectionTableArgs) ToDataProtectionTableOutput() DataProtectionTableOutput {
	return i.ToDataProtectionTableOutputWithContext(context.Background())
}

func (i DataProtectionTableArgs) ToDataProtectionTableOutputWithContext(ctx context.Context) DataProtectionTableOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataProtectionTableOutput)
}

// DataProtectionTableArrayInput is an input type that accepts DataProtectionTableArray and DataProtectionTableArrayOutput values.
// You can construct a concrete instance of `DataProtectionTableArrayInput` via:
//
//	DataProtectionTableArray{ DataProtectionTableArgs{...} }
type DataProtectionTableArrayInput interface {
	pulumi.Input

	ToDataProtectionTableArrayOutput() DataProtectionTableArrayOutput
	ToDataProtectionTableArrayOutputWithContext(context.Context) DataProtectionTableArrayOutput
}

type DataProtectionTableArray []DataProtectionTableInput

func (DataProtectionTableArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DataProtectionTable)(nil)).Elem()
}

func (i DataProtectionTableArray) ToDataProtectionTableArrayOutput() DataProtectionTableArrayOutput {
	return i.ToDataProtectionTableArrayOutputWithContext(context.Background())
}

func (i DataProtectionTableArray) ToDataProtectionTableArrayOutputWithContext(ctx context.Context) DataProtectionTableArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DataProtectionTableArrayOutput)
}

type DataProtectionTableOutput struct{ *pulumi.OutputState }

func (DataProtectionTableOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DataProtectionTable)(nil)).Elem()
}

func (o DataProtectionTableOutput) ToDataProtectionTableOutput() DataProtectionTableOutput {
	return o
}

func (o DataProtectionTableOutput) ToDataProtectionTableOutputWithContext(ctx context.Context) DataProtectionTableOutput {
	return o
}

func (o DataProtectionTableOutput) Masked() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v DataProtectionTable) *bool { return v.Masked }).(pulumi.BoolPtrOutput)
}

func (o DataProtectionTableOutput) MaskedColumns() DataProtectionColumnMaskArrayOutput {
	return o.ApplyT(func(v DataProtectionTable) []DataProtectionColumnMask { return v.MaskedColumns }).(DataProtectionColumnMaskArrayOutput)
}

func (o DataProtectionTableOutput) Schema() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DataProtectionTable) *string { return v.Schema }).(pulumi.StringPtrOutput)
}

func (o DataProtectionTableOutput) TableName() pulumi.StringOutput {
	return o.ApplyT(func(v DataProtectionTable) string { return v.TableName }).(pulumi.StringOutput)
}

type DataProtectionTableArrayOutput struct{ *pulumi.OutputState }

func (DataProtectionTableArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DataProtectionTable)(nil)).Elem()
}

func (o DataProtectionTableArrayOutput) ToDataProtectionTableArrayOutput() DataProtectionTableArrayOutput {
	return o
}

func (o DataProtectionTableArrayOutput) ToDataProtectionTableArrayOutputWithContext(ctx context.Context) DataProtectionTableArrayOutput {
	return o
}

func (o DataProtectionTableArrayOutput) Index(i pulumi.IntInput) DataProtectionTableOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) DataProtectionTable {
		return vs[0].([]DataProtectionTable)[vs[1].(int)]
	}).(DataProtectionTableOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DataProtectionColumnMaskInput)(nil)).Elem(), DataProtectionColumnMaskArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DataProtectionColumnMaskArrayInput)(nil)).Elem(), DataProtectionColumnMaskArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DataProtectionMaskInput)(nil)).Elem(), DataProtectionMaskArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DataProtectionMaskArrayInput)(nil)).Elem(), DataProtectionMaskArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DataProtectionTableInput)(nil)).Elem(), DataProtectionTableArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DataProtectionTableArrayInput)(nil)).Elem(), DataProtectionTableArray{})
	pulumi.RegisterOutputType(DataProtectionColumnMaskOutput{})
	pulumi.RegisterOutputType(DataProtectionColumnMaskArrayOutput{})
	pulumi.RegisterOutputType(DataProtectionMaskOutput{})
	pulumi.RegisterOutputType(DataProtectionMaskArrayOutput{})
	pulumi.RegisterOutputType(DataProtectionTableOutput{})
	pulumi.RegisterOutputType(DataProtectionTableArrayOutput{})
}
