// Code generated by pulumi-adaptive-gen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package adaptive

import (
	"context"
	"reflect"

	"errors"
	"github.com/adaptive-scale/pulumi-adaptive/sdk/go/adaptive/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Schedule struct {
	pulumi.CustomResourceState

	// Whether the schedule covers the whole day (start/end times are ignored).
	AllDay pulumi.BoolPtrOutput `pulumi:"allDay"`
	// An optional description of the schedule.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Day of month (1-31) the window closes, for monthly schedules.
	EndDay pulumi.IntPtrOutput `pulumi:"endDay"`
	// Hour (0-23) the window closes.
	EndHour pulumi.IntPtrOutput `pulumi:"endHour"`
	// Minute (0-59) the window closes.
	EndMinute pulumi.IntPtrOutput `pulumi:"endMinute"`
	// Names of endpoints the schedule applies to.
	Endpoints pulumi.StringArrayOutput `pulumi:"endpoints"`
	// RFC3339 timestamp after which the schedule no longer applies.
	ExpiresAt pulumi.StringPtrOutput `pulumi:"expiresAt"`
	// Whether the schedule is active.
	IsActive pulumi.BoolPtrOutput `pulumi:"isActive"`
	// Maximum access duration in minutes granted by an auto-approval.
	MaxAccessTime pulumi.IntPtrOutput `pulumi:"maxAccessTime"`
	// Name of the schedule. Note: the Adaptive API upserts schedules by name, so creating a schedule whose name already exists adopts the existing schedule.
	Name pulumi.StringOutput `pulumi:"name"`
	// What the schedule does inside its window: autoapprove or autoreject.
	OperationType pulumi.StringPtrOutput `pulumi:"operationType"`
	// The schedule pattern: weekdays, weekends, everyday, monthly, specific, or custom.
	ScheduleType pulumi.StringOutput `pulumi:"scheduleType"`
	// RFC3339 dates for a specific-dates schedule.
	SpecificDates pulumi.StringArrayOutput `pulumi:"specificDates"`
	// Day of month (1-31) the window opens, for monthly schedules.
	StartDay pulumi.IntPtrOutput `pulumi:"startDay"`
	// Hour (0-23) the window opens.
	StartHour pulumi.IntPtrOutput `pulumi:"startHour"`
	// Minute (0-59) the window opens.
	StartMinute pulumi.IntPtrOutput `pulumi:"startMinute"`
	// Names of groups the schedule applies to.
	Teams pulumi.StringArrayOutput `pulumi:"teams"`
	// IANA timezone for the schedule window. Empty inherits the workspace default.
	Timezone pulumi.StringPtrOutput `pulumi:"timezone"`
	// Last time the schedule was modified.
	UpdatedAt pulumi.StringPtrOutput `pulumi:"updatedAt"`
	// Emails of users the schedule applies to.
	Users pulumi.StringArrayOutput `pulumi:"users"`
	// Weekday names for a custom schedule (e.g. monday, tuesday).
	Weekdays pulumi.StringArrayOutput `pulumi:"weekdays"`
}

// NewSchedule registers a new resource with the given unique name, arguments, and options.
func NewSchedule(ctx *pulumi.Context,
	name string, args *ScheduleArgs, opts ...pulumi.ResourceOption) (*Schedule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.ScheduleType == nil {
		return nil, errors.New("invalid value for required argument 'ScheduleType'")
	}
	if args.OperationType == nil {
		args.OperationType = pulumi.StringPtr("autoapprove")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Schedule
	err := ctx.RegisterResource("adaptive:index:Schedule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSchedule gets an existing Schedule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSchedule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ScheduleState, opts ...pulumi.ResourceOption) (*Schedule, error) {
	var resource Schedule
	err := ctx.ReadResource("adaptive:index:Schedule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Schedule resources.
type scheduleState struct {
}

type ScheduleState struct {
}

func (ScheduleState) ElementType() reflect.Type {
	return reflect.TypeOf((*scheduleState)(nil)).Elem()
}

type scheduleArgs struct {
	// Whether the schedule covers the whole day (start/end times are ignored).
	AllDay *bool `pulumi:"allDay"`
	// An optional description of the schedule.
	Description *string `pulumi:"description"`
	// Day of month (1-31) the window closes, for monthly schedules.
	EndDay *int `pulumi:"endDay"`
	// Hour (0-23) the window closes.
	EndHour *int `pulumi:"endHour"`
	// Minute (0-59) the window closes.
	EndMinute *int `pulumi:"endMinute"`
	// Names of endpoints the schedule applies to.
	Endpoints []string `pulumi:"endpoints"`
	// RFC3339 timestamp after which the schedule no longer applies.
	ExpiresAt *string `pulumi:"expiresAt"`
	// Whether the schedule is active.
	IsActive *bool `pulumi:"isActive"`
	// Maximum access duration in minutes granted by an auto-approval.
	MaxAccessTime *int `pulumi:"maxAccessTime"`
	// Name of the schedule. Note: the Adaptive API upserts schedules by name, so creating a schedule whose name already exists adopts the existing schedule.
	Name string `pulumi:"name"`
	// What the schedule does inside its window: autoapprove or autoreject.
	OperationType *string `pulumi:"operationType"`
	// The schedule pattern: weekdays, weekends, everyday, monthly, specific, or custom.
	ScheduleType string `pulumi:"scheduleType"`
	// RFC3339 dates for a specific-dates schedule.
	SpecificDates []string `pulumi:"specificDates"`
	// Day of month (1-31) the window opens, for monthly schedules.
	StartDay *int `pulumi:"startDay"`
	// Hour (0-23) the window opens.
	StartHour *int `pulumi:"startHour"`
	// Minute (0-59) the window opens.
	StartMinute *int `pulumi:"startMinute"`
	// Names of groups the schedule applies to.
	Teams []string `pulumi:"teams"`
	// IANA timezone for the schedule window. Empty inherits the workspace default.
	Timezone *string `pulumi:"timezone"`
	// Emails of users the schedule applies to.
	Users []string `pulumi:"users"`
	// Weekday names for a custom schedule (e.g. monday, tuesday).
	Weekdays []string `pulumi:"weekdays"`
}

// The set of arguments for constructing a Schedule resource.
type ScheduleArgs struct {
	// Whether the schedule covers the whole day (start/end times are ignored).
	AllDay pulumi.BoolPtrInput
	// An optional description of the schedule.
	Description pulumi.StringPtrInput
	// Day of month (1-31) the window closes, for monthly schedules.
	EndDay pulumi.IntPtrInput
	// Hour (0-23) the window closes.
	EndHour pulumi.IntPtrInput
	// Minute (0-59) the window closes.
	EndMinute pulumi.IntPtrInput
	// Names of endpoints the schedule applies to.
	Endpoints pulumi.StringArrayInput
	// RFC3339 timestamp after which the schedule no longer applies.
	ExpiresAt pulumi.StringPtrInput
	// Whether the schedule is active.
	IsActive pulumi.BoolPtrInput
	// Maximum access duration in minutes granted by an auto-approval.
	MaxAccessTime pulumi.IntPtrInput
	// Name of the schedule. Note: the Adaptive API upserts schedules by name, so creating a schedule whose name already exists adopts the existing schedule.
	Name pulumi.StringInput
	// What the schedule does inside its window: autoapprove or autoreject.
	OperationType pulumi.StringPtrInput
	// The schedule pattern: weekdays, weekends, everyday, monthly, specific, or custom.
	ScheduleType pulumi.StringInput
	// RFC3339 dates for a specific-dates schedule.
	SpecificDates pulumi.StringArrayInput
	// Day of month (1-31) the window opens, for monthly schedules.
	StartDay pulumi.IntPtrInput
	// Hour (0-23) the window opens.
	StartHour pulumi.IntPtrInput
	// Minute (0-59) the window opens.
	StartMinute pulumi.IntPtrInput
	// Names of groups the schedule applies to.
	Teams pulumi.StringArrayInput
	// IANA timezone for the schedule window. Empty inherits the workspace default.
	Timezone pulumi.StringPtrInput
	// Emails of users the schedule applies to.
	Users pulumi.StringArrayInput
	// Weekday names for a custom schedule (e.g. monday, tuesday).
	Weekdays pulumi.StringArrayInput
}

func (ScheduleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*scheduleArgs)(nil)).Elem()
}

type ScheduleInput interface {
	pulumi.Input

	ToScheduleOutput() ScheduleOutput
	ToScheduleOutputWithContext(ctx context.Context) ScheduleOutput
}

func (*Schedule) ElementType() reflect.Type {
	return reflect.TypeOf((**Schedule)(nil)).Elem()
}

func (i *Schedule) ToScheduleOutput() ScheduleOutput {
	return i.ToScheduleOutputWithContext(context.Background())
}

func (i *Schedule) ToScheduleOutputWithContext(ctx context.Context) ScheduleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScheduleOutput)
}

// ScheduleArrayInput is an input type that accepts ScheduleArray and ScheduleArrayOutput values.
// You can construct a concrete instance of `ScheduleArrayInput` via:
//
//	ScheduleArray{ ScheduleArgs{...} }
type ScheduleArrayInput interface {
	pulumi.Input

	ToScheduleArrayOutput() ScheduleArrayOutput
	ToScheduleArrayOutputWithContext(context.Context) ScheduleArrayOutput
}

type ScheduleArray []ScheduleInput

func (ScheduleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Schedule)(nil)).Elem()
}

func (i ScheduleArray) ToScheduleArrayOutput() ScheduleArrayOutput {
	return i.ToScheduleArrayOutputWithContext(context.Background())
}

func (i ScheduleArray) ToScheduleArrayOutputWithContext(ctx context.Context) ScheduleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScheduleArrayOutput)
}

// ScheduleMapInput is an input type that accepts ScheduleMap and ScheduleMapOutput values.
// You can construct a concrete instance of `ScheduleMapInput` via:
//
//	ScheduleMap{ "key": ScheduleArgs{...} }
type ScheduleMapInput interface {
	pulumi.Input

	ToScheduleMapOutput() ScheduleMapOutput
	ToScheduleMapOutputWithContext(context.Context) ScheduleMapOutput
}

type ScheduleMap map[string]ScheduleInput

func (ScheduleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Schedule)(nil)).Elem()
}

func (i ScheduleMap) ToScheduleMapOutput() ScheduleMapOutput {
	return i.ToScheduleMapOutputWithContext(context.Background())
}

func (i ScheduleMap) ToScheduleMapOutputWithContext(ctx context.Context) ScheduleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScheduleMapOutput)
}

type ScheduleOutput struct{ *pulumi.OutputState }

func (ScheduleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Schedule)(nil)).Elem()
}

func (o ScheduleOutput) ToScheduleOutput() ScheduleOutput {
	return o
}

func (o ScheduleOutput) ToScheduleOutputWithContext(ctx context.Context) ScheduleOutput {
	return o
}

// Whether the schedule covers the whole day (start/end times are ignored).
func (o ScheduleOutput) AllDay() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.BoolPtrOutput { return v.AllDay }).(pulumi.BoolPtrOutput)
}

// An optional description of the schedule.
func (o ScheduleOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Day of month (1-31) the window closes, for monthly schedules.
func (o ScheduleOutput) EndDay() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.IntPtrOutput { return v.EndDay }).(pulumi.IntPtrOutput)
}

// Hour (0-23) the window closes.
func (o ScheduleOutput) EndHour() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.IntPtrOutput { return v.EndHour }).(pulumi.IntPtrOutput)
}

// Minute (0-59) the window closes.
func (o ScheduleOutput) EndMinute() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.IntPtrOutput { return v.EndMinute }).(pulumi.IntPtrOutput)
}

// Names of endpoints the schedule applies to.
func (o ScheduleOutput) Endpoints() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringArrayOutput { return v.Endpoints }).(pulumi.StringArrayOutput)
}

// RFC3339 timestamp after which the schedule no longer applies.
func (o ScheduleOutput) ExpiresAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringPtrOutput { return v.ExpiresAt }).(pulumi.StringPtrOutput)
}

// Whether the schedule is active.
func (o ScheduleOutput) IsActive() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.BoolPtrOutput { return v.IsActive }).(pulumi.BoolPtrOutput)
}

// Maximum access duration in minutes granted by an auto-approval.
func (o ScheduleOutput) MaxAccessTime() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.IntPtrOutput { return v.MaxAccessTime }).(pulumi.IntPtrOutput)
}

// Name of the schedule. Note: the Adaptive API upserts schedules by name, so creating a schedule whose name already exists adopts the existing schedule.
func (o ScheduleOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// What the schedule does inside its window: autoapprove or autoreject.
func (o ScheduleOutput) OperationType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringPtrOutput { return v.OperationType }).(pulumi.StringPtrOutput)
}

// The schedule pattern: weekdays, weekends, everyday, monthly, specific, or custom.
func (o ScheduleOutput) ScheduleType() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.ScheduleType }).(pulumi.StringOutput)
}

// RFC3339 dates for a specific-dates schedule.
func (o ScheduleOutput) SpecificDates() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringArrayOutput { return v.SpecificDates }).(pulumi.StringArrayOutput)
}

// Day of month (1-31) the window opens, for monthly schedules.
func (o ScheduleOutput) StartDay() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.IntPtrOutput { return v.StartDay }).(pulumi.IntPtrOutput)
}

// Hour (0-23) the window opens.
func (o ScheduleOutput) StartHour() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.IntPtrOutput { return v.StartHour }).(pulumi.IntPtrOutput)
}

// Minute (0-59) the window opens.
func (o ScheduleOutput) StartMinute() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.IntPtrOutput { return v.StartMinute }).(pulumi.IntPtrOutput)
}

// Names of groups the schedule applies to.
func (o ScheduleOutput) Teams() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringArrayOutput { return v.Teams }).(pulumi.StringArrayOutput)
}

// IANA timezone for the schedule window. Empty inherits the workspace default.
func (o ScheduleOutput) Timezone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringPtrOutput { return v.Timezone }).(pulumi.StringPtrOutput)
}

// Last time the schedule was modified.
func (o ScheduleOutput) UpdatedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringPtrOutput { return v.UpdatedAt }).(pulumi.StringPtrOutput)
}

// Emails of users the schedule applies to.
func (o ScheduleOutput) Users() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringArrayOutput { return v.Users }).(pulumi.StringArrayOutput)
}

// Weekday names for a custom schedule (e.g. monday, tuesday).
func (o ScheduleOutput) Weekdays() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringArrayOutput { return v.Weekdays }).(pulumi.StringArrayOutput)
}

type ScheduleArrayOutput struct{ *pulumi.OutputState }

func (ScheduleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Schedule)(nil)).Elem()
}

func (o ScheduleArrayOutput) ToScheduleArrayOutput() ScheduleArrayOutput {
	return o
}

func (o ScheduleArrayOutput) ToScheduleArrayOutputWithContext(ctx context.Context) ScheduleArrayOutput {
	return o
}

func (o ScheduleArrayOutput) Index(i pulumi.IntInput) ScheduleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Schedule {
		return vs[0].([]*Schedule)[vs[1].(int)]
	}).(ScheduleOutput)
}

type ScheduleMapOutput struct{ *pulumi.OutputState }

func (ScheduleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Schedule)(nil)).Elem()
}

func (o ScheduleMapOutput) ToScheduleMapOutput() ScheduleMapOutput {
	return o
}

func (o ScheduleMapOutput) ToScheduleMapOutputWithContext(ctx context.Context) ScheduleMapOutput {
	return o
}

func (o ScheduleMapOutput) MapIndex(k pulumi.StringInput) ScheduleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Schedule {
		return vs[0].(map[string]*Schedule)[vs[1].(string)]
	}).(ScheduleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ScheduleInput)(nil)).Elem(), &Schedule{})
	pulumi.RegisterInputType(reflect.TypeOf((*ScheduleArrayInput)(nil)).Elem(), ScheduleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ScheduleMapInput)(nil)).Elem(), ScheduleMap{})
	pulumi.RegisterOutputType(ScheduleOutput{})
	pulumi.RegisterOutputType(ScheduleArrayOutput{})
	pulumi.RegisterOutputType(ScheduleMapOutput{})
}
