# coding=utf-8
# *** WARNING: this file was generated by pulumi-adaptive-gen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .authorization import *
from .endpoint import *
from .group import *
from .ms_teams_workflow import *
from .provider import *
from .resource import *
from .schedule import *
from .script import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_adaptive.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_adaptive.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "adaptive",
  "mod": "index",
  "fqn": "pulumi_adaptive",
  "classes": {
   "adaptive:index:Authorization": "Authorization",
   "adaptive:index:Endpoint": "Endpoint",
   "adaptive:index:Group": "Group",
   "adaptive:index:MSTeamsWorkflow": "MSTeamsWorkflow",
   "adaptive:index:Resource": "Resource",
   "adaptive:index:Schedule": "Schedule",
   "adaptive:index:Script": "Script"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "adaptive",
  "token": "pulumi:providers:adaptive",
  "fqn": "pulumi_adaptive",
  "class": "Provider"
 }
]
"""
)
