# coding=utf-8
# *** WARNING: this file was generated by pulumi-adaptive-gen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'DataProtectionColumnMaskArgs',
    'DataProtectionColumnMaskArgsDict',
    'DataProtectionMaskArgs',
    'DataProtectionMaskArgsDict',
    'DataProtectionTableArgs',
    'DataProtectionTableArgsDict',
]

class DataProtectionColumnMaskArgsDict(TypedDict):
    column_name: pulumi.Input[_builtins.str]
    masking_type: pulumi.Input[_builtins.str]

@pulumi.input_type
class DataProtectionColumnMaskArgs:
    def __init__(__self__, *,
                 column_name: pulumi.Input[_builtins.str],
                 masking_type: pulumi.Input[_builtins.str]):
        pulumi.set(__self__, "column_name", column_name)
        pulumi.set(__self__, "masking_type", masking_type)

    @_builtins.property
    @pulumi.getter(name="columnName")
    def column_name(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "column_name")

    @column_name.setter
    def column_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "column_name", value)

    @_builtins.property
    @pulumi.getter(name="maskingType")
    def masking_type(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "masking_type")

    @masking_type.setter
    def masking_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "masking_type", value)


class DataProtectionMaskArgsDict(TypedDict):
    database_name: pulumi.Input[_builtins.str]
    tables: NotRequired[pulumi.Input[Sequence[pulumi.Input['DataProtectionTableArgsDict']]]]

@pulumi.input_type
class DataProtectionMaskArgs:
    def __init__(__self__, *,
                 database_name: pulumi.Input[_builtins.str],
                 tables: Optional[pulumi.Input[Sequence[pulumi.Input['DataProtectionTableArgs']]]] = None):
        pulumi.set(__self__, "database_name", database_name)
        if tables is not None:
            pulumi.set(__self__, "tables", tables)

    @_builtins.property
    @pulumi.getter(name="databaseName")
    def database_name(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "database_name")

    @database_name.setter
    def database_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "database_name", value)

    @_builtins.property
    @pulumi.getter
    def tables(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['DataProtectionTableArgs']]]]:
        return pulumi.get(self, "tables")

    @tables.setter
    def tables(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['DataProtectionTableArgs']]]]):
        pulumi.set(self, "tables", value)


class DataProtectionTableArgsDict(TypedDict):
    table_name: pulumi.Input[_builtins.str]
    masked: NotRequired[pulumi.Input[_builtins.bool]]
    masked_columns: NotRequired[pulumi.Input[Sequence[pulumi.Input['DataProtectionColumnMaskArgsDict']]]]
    schema: NotRequired[pulumi.Input[_builtins.str]]

@pulumi.input_type
class DataProtectionTableArgs:
    def __init__(__self__, *,
                 table_name: pulumi.Input[_builtins.str],
                 masked: Optional[pulumi.Input[_builtins.bool]] = None,
                 masked_columns: Optional[pulumi.Input[Sequence[pulumi.Input['DataProtectionColumnMaskArgs']]]] = None,
                 schema: Optional[pulumi.Input[_builtins.str]] = None):
        pulumi.set(__self__, "table_name", table_name)
        if masked is not None:
            pulumi.set(__self__, "masked", masked)
        if masked_columns is not None:
            pulumi.set(__self__, "masked_columns", masked_columns)
        if schema is not None:
            pulumi.set(__self__, "schema", schema)

    @_builtins.property
    @pulumi.getter(name="tableName")
    def table_name(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "table_name")

    @table_name.setter
    def table_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "table_name", value)

    @_builtins.property
    @pulumi.getter
    def masked(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "masked")

    @masked.setter
    def masked(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "masked", value)

    @_builtins.property
    @pulumi.getter(name="maskedColumns")
    def masked_columns(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['DataProtectionColumnMaskArgs']]]]:
        return pulumi.get(self, "masked_columns")

    @masked_columns.setter
    def masked_columns(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['DataProtectionColumnMaskArgs']]]]):
        pulumi.set(self, "masked_columns", value)

    @_builtins.property
    @pulumi.getter
    def schema(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "schema")

    @schema.setter
    def schema(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "schema", value)


