# coding=utf-8
# *** WARNING: this file was generated by pulumi-adaptive-gen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['DataProtectionArgs', 'DataProtection']

@pulumi.input_type
class DataProtectionArgs:
    def __init__(__self__, *,
                 resource: pulumi.Input[_builtins.str],
                 masks: Optional[pulumi.Input[Sequence[pulumi.Input['DataProtectionMaskArgs']]]] = None,
                 scoped: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a DataProtection resource.

        :param pulumi.Input[_builtins.str] resource: Name of the resource (integration) this masking policy protects. Cannot be changed after creation. Note: creating a policy for a resource that already has one (e.g. configured in the UI) adopts and overwrites it.
        :param pulumi.Input[Sequence[pulumi.Input['DataProtectionMaskArgs']]] masks: Masking rules, grouped per database and table.
        :param pulumi.Input[_builtins.bool] scoped: When true (the default), session users only see the generated masked views. When false, users see everything except the raw masked tables (requires synced metadata).
        """
        pulumi.set(__self__, "resource", resource)
        if masks is not None:
            pulumi.set(__self__, "masks", masks)
        if scoped is not None:
            pulumi.set(__self__, "scoped", scoped)

    @_builtins.property
    @pulumi.getter
    def resource(self) -> pulumi.Input[_builtins.str]:
        """
        Name of the resource (integration) this masking policy protects. Cannot be changed after creation. Note: creating a policy for a resource that already has one (e.g. configured in the UI) adopts and overwrites it.
        """
        return pulumi.get(self, "resource")

    @resource.setter
    def resource(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "resource", value)

    @_builtins.property
    @pulumi.getter
    def masks(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['DataProtectionMaskArgs']]]]:
        """
        Masking rules, grouped per database and table.
        """
        return pulumi.get(self, "masks")

    @masks.setter
    def masks(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['DataProtectionMaskArgs']]]]):
        pulumi.set(self, "masks", value)

    @_builtins.property
    @pulumi.getter
    def scoped(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        When true (the default), session users only see the generated masked views. When false, users see everything except the raw masked tables (requires synced metadata).
        """
        return pulumi.get(self, "scoped")

    @scoped.setter
    def scoped(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "scoped", value)


@pulumi.type_token("adaptive:index:DataProtection")
class DataProtection(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 masks: Optional[pulumi.Input[Sequence[pulumi.Input[Union['DataProtectionMaskArgs', 'DataProtectionMaskArgsDict']]]]] = None,
                 resource: Optional[pulumi.Input[_builtins.str]] = None,
                 scoped: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        """
        Create a DataProtection resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['DataProtectionMaskArgs', 'DataProtectionMaskArgsDict']]]] masks: Masking rules, grouped per database and table.
        :param pulumi.Input[_builtins.str] resource: Name of the resource (integration) this masking policy protects. Cannot be changed after creation. Note: creating a policy for a resource that already has one (e.g. configured in the UI) adopts and overwrites it.
        :param pulumi.Input[_builtins.bool] scoped: When true (the default), session users only see the generated masked views. When false, users see everything except the raw masked tables (requires synced metadata).
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DataProtectionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a DataProtection resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param DataProtectionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DataProtectionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 masks: Optional[pulumi.Input[Sequence[pulumi.Input[Union['DataProtectionMaskArgs', 'DataProtectionMaskArgsDict']]]]] = None,
                 resource: Optional[pulumi.Input[_builtins.str]] = None,
                 scoped: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DataProtectionArgs.__new__(DataProtectionArgs)

            __props__.__dict__["masks"] = masks
            if resource is None and not opts.urn:
                raise TypeError("Missing required property 'resource'")
            __props__.__dict__["resource"] = resource
            __props__.__dict__["scoped"] = scoped
            __props__.__dict__["authorization_name"] = None
            __props__.__dict__["last_applied_at"] = None
            __props__.__dict__["status"] = None
        super(DataProtection, __self__).__init__(
            'adaptive:index:DataProtection',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'DataProtection':
        """
        Get an existing DataProtection resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = DataProtectionArgs.__new__(DataProtectionArgs)

        __props__.__dict__["authorization_name"] = None
        __props__.__dict__["last_applied_at"] = None
        __props__.__dict__["masks"] = None
        __props__.__dict__["resource"] = None
        __props__.__dict__["scoped"] = None
        __props__.__dict__["status"] = None
        return DataProtection(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="authorizationName")
    def authorization_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Name of the generated masking authorization (masked_<resource>). Attach it to an Endpoint's `authorization` to serve masked sessions.
        """
        return pulumi.get(self, "authorization_name")

    @_builtins.property
    @pulumi.getter(name="lastAppliedAt")
    def last_applied_at(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Last time the policy was applied to the target database.
        """
        return pulumi.get(self, "last_applied_at")

    @_builtins.property
    @pulumi.getter
    def masks(self) -> pulumi.Output[Optional[Sequence['outputs.DataProtectionMask']]]:
        """
        Masking rules, grouped per database and table.
        """
        return pulumi.get(self, "masks")

    @_builtins.property
    @pulumi.getter
    def resource(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the resource (integration) this masking policy protects. Cannot be changed after creation. Note: creating a policy for a resource that already has one (e.g. configured in the UI) adopts and overwrites it.
        """
        return pulumi.get(self, "resource")

    @_builtins.property
    @pulumi.getter
    def scoped(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        When true (the default), session users only see the generated masked views. When false, users see everything except the raw masked tables (requires synced metadata).
        """
        return pulumi.get(self, "scoped")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Provisioning status of the policy. Masked views are created lazily at session start.
        """
        return pulumi.get(self, "status")

