# coding=utf-8
# *** WARNING: this file was generated by pulumi-adaptive-gen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['EndpointArgs', 'Endpoint']

@pulumi.input_type
class EndpointArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 resource: pulumi.Input[_builtins.str],
                 authorization: Optional[pulumi.Input[_builtins.str]] = None,
                 auto_approval: Optional[pulumi.Input[_builtins.bool]] = None,
                 cluster: Optional[pulumi.Input[_builtins.str]] = None,
                 cpu: Optional[pulumi.Input[_builtins.str]] = None,
                 disable_data_studio: Optional[pulumi.Input[_builtins.bool]] = None,
                 disable_output_capture: Optional[pulumi.Input[_builtins.bool]] = None,
                 disable_web_cli: Optional[pulumi.Input[_builtins.bool]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 idle_timeout: Optional[pulumi.Input[_builtins.str]] = None,
                 is_jit_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 jit_approvers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 jit_mode: Optional[pulumi.Input[_builtins.str]] = None,
                 jit_multi_approver: Optional[pulumi.Input[_builtins.bool]] = None,
                 jit_total_approvers: Optional[pulumi.Input[_builtins.int]] = None,
                 memory: Optional[pulumi.Input[_builtins.str]] = None,
                 pause_timeout: Optional[pulumi.Input[_builtins.str]] = None,
                 script_only_access: Optional[pulumi.Input[_builtins.bool]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ttl: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a Endpoint resource.

        :param pulumi.Input[_builtins.str] name: The name of the endpoint to create.
        :param pulumi.Input[_builtins.str] resource: The resource (by name) this endpoint grants access to.
        :param pulumi.Input[_builtins.str] authorization: The authorization (by name) to apply to this endpoint.
        :param pulumi.Input[_builtins.bool] auto_approval: Automatically approve Just-In-Time access requests.
        :param pulumi.Input[_builtins.bool] disable_data_studio: Hide Data Studio for this endpoint (cli endpoints only).
        :param pulumi.Input[_builtins.bool] disable_output_capture: Do not retain terminal output for this endpoint. The effective value is OR'd with the workspace-level setting: an endpoint cannot re-enable capture that the workspace disabled.
        :param pulumi.Input[_builtins.bool] disable_web_cli: Hide 'Connect via Web CLI' for this endpoint (cli endpoints only).
        :param pulumi.Input[_builtins.bool] is_jit_enabled: Whether Just-In-Time access approval is enabled.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] jit_approvers: Emails of users who can approve Just-In-Time access requests.
        :param pulumi.Input[_builtins.str] jit_mode: Which access paths require Just-In-Time approval: session, script, or both.
        :param pulumi.Input[_builtins.bool] jit_multi_approver: Require multiple approvers for Just-In-Time access requests.
        :param pulumi.Input[_builtins.int] jit_total_approvers: Number of approvals required when multi-approver is enabled.
        :param pulumi.Input[_builtins.bool] script_only_access: Whether the endpoint is only accessible via script.
        :param pulumi.Input[_builtins.str] ttl: Time-to-live for the endpoint, e.g. 8h, 7d, 90d.
        :param pulumi.Input[_builtins.str] type: The type of session: direct, client, cli, or services.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "resource", resource)
        if authorization is not None:
            pulumi.set(__self__, "authorization", authorization)
        if auto_approval is not None:
            pulumi.set(__self__, "auto_approval", auto_approval)
        if cluster is not None:
            pulumi.set(__self__, "cluster", cluster)
        if cpu is not None:
            pulumi.set(__self__, "cpu", cpu)
        if disable_data_studio is not None:
            pulumi.set(__self__, "disable_data_studio", disable_data_studio)
        if disable_output_capture is not None:
            pulumi.set(__self__, "disable_output_capture", disable_output_capture)
        if disable_web_cli is not None:
            pulumi.set(__self__, "disable_web_cli", disable_web_cli)
        if groups is not None:
            pulumi.set(__self__, "groups", groups)
        if idle_timeout is not None:
            pulumi.set(__self__, "idle_timeout", idle_timeout)
        if is_jit_enabled is not None:
            pulumi.set(__self__, "is_jit_enabled", is_jit_enabled)
        if jit_approvers is not None:
            pulumi.set(__self__, "jit_approvers", jit_approvers)
        if jit_mode is not None:
            pulumi.set(__self__, "jit_mode", jit_mode)
        if jit_multi_approver is not None:
            pulumi.set(__self__, "jit_multi_approver", jit_multi_approver)
        if jit_total_approvers is not None:
            pulumi.set(__self__, "jit_total_approvers", jit_total_approvers)
        if memory is not None:
            pulumi.set(__self__, "memory", memory)
        if pause_timeout is not None:
            pulumi.set(__self__, "pause_timeout", pause_timeout)
        if script_only_access is not None:
            pulumi.set(__self__, "script_only_access", script_only_access)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if ttl is not None:
            pulumi.set(__self__, "ttl", ttl)
        if type is None:
            type = 'direct'
        if type is not None:
            pulumi.set(__self__, "type", type)
        if users is not None:
            pulumi.set(__self__, "users", users)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The name of the endpoint to create.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def resource(self) -> pulumi.Input[_builtins.str]:
        """
        The resource (by name) this endpoint grants access to.
        """
        return pulumi.get(self, "resource")

    @resource.setter
    def resource(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "resource", value)

    @_builtins.property
    @pulumi.getter
    def authorization(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The authorization (by name) to apply to this endpoint.
        """
        return pulumi.get(self, "authorization")

    @authorization.setter
    def authorization(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "authorization", value)

    @_builtins.property
    @pulumi.getter(name="autoApproval")
    def auto_approval(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Automatically approve Just-In-Time access requests.
        """
        return pulumi.get(self, "auto_approval")

    @auto_approval.setter
    def auto_approval(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "auto_approval", value)

    @_builtins.property
    @pulumi.getter
    def cluster(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "cluster")

    @cluster.setter
    def cluster(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cluster", value)

    @_builtins.property
    @pulumi.getter
    def cpu(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "cpu")

    @cpu.setter
    def cpu(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cpu", value)

    @_builtins.property
    @pulumi.getter(name="disableDataStudio")
    def disable_data_studio(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Hide Data Studio for this endpoint (cli endpoints only).
        """
        return pulumi.get(self, "disable_data_studio")

    @disable_data_studio.setter
    def disable_data_studio(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "disable_data_studio", value)

    @_builtins.property
    @pulumi.getter(name="disableOutputCapture")
    def disable_output_capture(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Do not retain terminal output for this endpoint. The effective value is OR'd with the workspace-level setting: an endpoint cannot re-enable capture that the workspace disabled.
        """
        return pulumi.get(self, "disable_output_capture")

    @disable_output_capture.setter
    def disable_output_capture(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "disable_output_capture", value)

    @_builtins.property
    @pulumi.getter(name="disableWebCli")
    def disable_web_cli(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Hide 'Connect via Web CLI' for this endpoint (cli endpoints only).
        """
        return pulumi.get(self, "disable_web_cli")

    @disable_web_cli.setter
    def disable_web_cli(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "disable_web_cli", value)

    @_builtins.property
    @pulumi.getter
    def groups(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "groups")

    @groups.setter
    def groups(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "groups", value)

    @_builtins.property
    @pulumi.getter(name="idleTimeout")
    def idle_timeout(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "idle_timeout")

    @idle_timeout.setter
    def idle_timeout(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "idle_timeout", value)

    @_builtins.property
    @pulumi.getter(name="isJitEnabled")
    def is_jit_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether Just-In-Time access approval is enabled.
        """
        return pulumi.get(self, "is_jit_enabled")

    @is_jit_enabled.setter
    def is_jit_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "is_jit_enabled", value)

    @_builtins.property
    @pulumi.getter(name="jitApprovers")
    def jit_approvers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Emails of users who can approve Just-In-Time access requests.
        """
        return pulumi.get(self, "jit_approvers")

    @jit_approvers.setter
    def jit_approvers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "jit_approvers", value)

    @_builtins.property
    @pulumi.getter(name="jitMode")
    def jit_mode(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Which access paths require Just-In-Time approval: session, script, or both.
        """
        return pulumi.get(self, "jit_mode")

    @jit_mode.setter
    def jit_mode(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "jit_mode", value)

    @_builtins.property
    @pulumi.getter(name="jitMultiApprover")
    def jit_multi_approver(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Require multiple approvers for Just-In-Time access requests.
        """
        return pulumi.get(self, "jit_multi_approver")

    @jit_multi_approver.setter
    def jit_multi_approver(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "jit_multi_approver", value)

    @_builtins.property
    @pulumi.getter(name="jitTotalApprovers")
    def jit_total_approvers(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Number of approvals required when multi-approver is enabled.
        """
        return pulumi.get(self, "jit_total_approvers")

    @jit_total_approvers.setter
    def jit_total_approvers(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "jit_total_approvers", value)

    @_builtins.property
    @pulumi.getter
    def memory(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "memory")

    @memory.setter
    def memory(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "memory", value)

    @_builtins.property
    @pulumi.getter(name="pauseTimeout")
    def pause_timeout(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "pause_timeout")

    @pause_timeout.setter
    def pause_timeout(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "pause_timeout", value)

    @_builtins.property
    @pulumi.getter(name="scriptOnlyAccess")
    def script_only_access(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the endpoint is only accessible via script.
        """
        return pulumi.get(self, "script_only_access")

    @script_only_access.setter
    def script_only_access(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "script_only_access", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def ttl(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Time-to-live for the endpoint, e.g. 8h, 7d, 90d.
        """
        return pulumi.get(self, "ttl")

    @ttl.setter
    def ttl(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ttl", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The type of session: direct, client, cli, or services.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def users(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "users")

    @users.setter
    def users(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "users", value)


@pulumi.type_token("adaptive:index:Endpoint")
class Endpoint(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 authorization: Optional[pulumi.Input[_builtins.str]] = None,
                 auto_approval: Optional[pulumi.Input[_builtins.bool]] = None,
                 cluster: Optional[pulumi.Input[_builtins.str]] = None,
                 cpu: Optional[pulumi.Input[_builtins.str]] = None,
                 disable_data_studio: Optional[pulumi.Input[_builtins.bool]] = None,
                 disable_output_capture: Optional[pulumi.Input[_builtins.bool]] = None,
                 disable_web_cli: Optional[pulumi.Input[_builtins.bool]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 idle_timeout: Optional[pulumi.Input[_builtins.str]] = None,
                 is_jit_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 jit_approvers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 jit_mode: Optional[pulumi.Input[_builtins.str]] = None,
                 jit_multi_approver: Optional[pulumi.Input[_builtins.bool]] = None,
                 jit_total_approvers: Optional[pulumi.Input[_builtins.int]] = None,
                 memory: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 pause_timeout: Optional[pulumi.Input[_builtins.str]] = None,
                 resource: Optional[pulumi.Input[_builtins.str]] = None,
                 script_only_access: Optional[pulumi.Input[_builtins.bool]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ttl: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Create a Endpoint resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] authorization: The authorization (by name) to apply to this endpoint.
        :param pulumi.Input[_builtins.bool] auto_approval: Automatically approve Just-In-Time access requests.
        :param pulumi.Input[_builtins.bool] disable_data_studio: Hide Data Studio for this endpoint (cli endpoints only).
        :param pulumi.Input[_builtins.bool] disable_output_capture: Do not retain terminal output for this endpoint. The effective value is OR'd with the workspace-level setting: an endpoint cannot re-enable capture that the workspace disabled.
        :param pulumi.Input[_builtins.bool] disable_web_cli: Hide 'Connect via Web CLI' for this endpoint (cli endpoints only).
        :param pulumi.Input[_builtins.bool] is_jit_enabled: Whether Just-In-Time access approval is enabled.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] jit_approvers: Emails of users who can approve Just-In-Time access requests.
        :param pulumi.Input[_builtins.str] jit_mode: Which access paths require Just-In-Time approval: session, script, or both.
        :param pulumi.Input[_builtins.bool] jit_multi_approver: Require multiple approvers for Just-In-Time access requests.
        :param pulumi.Input[_builtins.int] jit_total_approvers: Number of approvals required when multi-approver is enabled.
        :param pulumi.Input[_builtins.str] name: The name of the endpoint to create.
        :param pulumi.Input[_builtins.str] resource: The resource (by name) this endpoint grants access to.
        :param pulumi.Input[_builtins.bool] script_only_access: Whether the endpoint is only accessible via script.
        :param pulumi.Input[_builtins.str] ttl: Time-to-live for the endpoint, e.g. 8h, 7d, 90d.
        :param pulumi.Input[_builtins.str] type: The type of session: direct, client, cli, or services.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: EndpointArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Endpoint resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param EndpointArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(EndpointArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 authorization: Optional[pulumi.Input[_builtins.str]] = None,
                 auto_approval: Optional[pulumi.Input[_builtins.bool]] = None,
                 cluster: Optional[pulumi.Input[_builtins.str]] = None,
                 cpu: Optional[pulumi.Input[_builtins.str]] = None,
                 disable_data_studio: Optional[pulumi.Input[_builtins.bool]] = None,
                 disable_output_capture: Optional[pulumi.Input[_builtins.bool]] = None,
                 disable_web_cli: Optional[pulumi.Input[_builtins.bool]] = None,
                 groups: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 idle_timeout: Optional[pulumi.Input[_builtins.str]] = None,
                 is_jit_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 jit_approvers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 jit_mode: Optional[pulumi.Input[_builtins.str]] = None,
                 jit_multi_approver: Optional[pulumi.Input[_builtins.bool]] = None,
                 jit_total_approvers: Optional[pulumi.Input[_builtins.int]] = None,
                 memory: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 pause_timeout: Optional[pulumi.Input[_builtins.str]] = None,
                 resource: Optional[pulumi.Input[_builtins.str]] = None,
                 script_only_access: Optional[pulumi.Input[_builtins.bool]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ttl: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = EndpointArgs.__new__(EndpointArgs)

            __props__.__dict__["authorization"] = authorization
            __props__.__dict__["auto_approval"] = auto_approval
            __props__.__dict__["cluster"] = cluster
            __props__.__dict__["cpu"] = cpu
            __props__.__dict__["disable_data_studio"] = disable_data_studio
            __props__.__dict__["disable_output_capture"] = disable_output_capture
            __props__.__dict__["disable_web_cli"] = disable_web_cli
            __props__.__dict__["groups"] = groups
            __props__.__dict__["idle_timeout"] = idle_timeout
            __props__.__dict__["is_jit_enabled"] = is_jit_enabled
            __props__.__dict__["jit_approvers"] = jit_approvers
            __props__.__dict__["jit_mode"] = jit_mode
            __props__.__dict__["jit_multi_approver"] = jit_multi_approver
            __props__.__dict__["jit_total_approvers"] = jit_total_approvers
            __props__.__dict__["memory"] = memory
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["pause_timeout"] = pause_timeout
            if resource is None and not opts.urn:
                raise TypeError("Missing required property 'resource'")
            __props__.__dict__["resource"] = resource
            __props__.__dict__["script_only_access"] = script_only_access
            __props__.__dict__["tags"] = tags
            __props__.__dict__["ttl"] = ttl
            if type is None:
                type = 'direct'
            __props__.__dict__["type"] = type
            __props__.__dict__["users"] = users
            __props__.__dict__["expose_status"] = None
            __props__.__dict__["expose_type"] = None
            __props__.__dict__["exposed"] = None
            __props__.__dict__["status"] = None
        super(Endpoint, __self__).__init__(
            'adaptive:index:Endpoint',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Endpoint':
        """
        Get an existing Endpoint resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = EndpointArgs.__new__(EndpointArgs)

        __props__.__dict__["authorization"] = None
        __props__.__dict__["auto_approval"] = None
        __props__.__dict__["cluster"] = None
        __props__.__dict__["cpu"] = None
        __props__.__dict__["disable_data_studio"] = None
        __props__.__dict__["disable_output_capture"] = None
        __props__.__dict__["disable_web_cli"] = None
        __props__.__dict__["expose_status"] = None
        __props__.__dict__["expose_type"] = None
        __props__.__dict__["exposed"] = None
        __props__.__dict__["groups"] = None
        __props__.__dict__["idle_timeout"] = None
        __props__.__dict__["is_jit_enabled"] = None
        __props__.__dict__["jit_approvers"] = None
        __props__.__dict__["jit_mode"] = None
        __props__.__dict__["jit_multi_approver"] = None
        __props__.__dict__["jit_total_approvers"] = None
        __props__.__dict__["memory"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["pause_timeout"] = None
        __props__.__dict__["resource"] = None
        __props__.__dict__["script_only_access"] = None
        __props__.__dict__["status"] = None
        __props__.__dict__["tags"] = None
        __props__.__dict__["ttl"] = None
        __props__.__dict__["type"] = None
        __props__.__dict__["users"] = None
        return Endpoint(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def authorization(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The authorization (by name) to apply to this endpoint.
        """
        return pulumi.get(self, "authorization")

    @_builtins.property
    @pulumi.getter(name="autoApproval")
    def auto_approval(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Automatically approve Just-In-Time access requests.
        """
        return pulumi.get(self, "auto_approval")

    @_builtins.property
    @pulumi.getter
    def cluster(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "cluster")

    @_builtins.property
    @pulumi.getter
    def cpu(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "cpu")

    @_builtins.property
    @pulumi.getter(name="disableDataStudio")
    def disable_data_studio(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Hide Data Studio for this endpoint (cli endpoints only).
        """
        return pulumi.get(self, "disable_data_studio")

    @_builtins.property
    @pulumi.getter(name="disableOutputCapture")
    def disable_output_capture(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Do not retain terminal output for this endpoint. The effective value is OR'd with the workspace-level setting: an endpoint cannot re-enable capture that the workspace disabled.
        """
        return pulumi.get(self, "disable_output_capture")

    @_builtins.property
    @pulumi.getter(name="disableWebCli")
    def disable_web_cli(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Hide 'Connect via Web CLI' for this endpoint (cli endpoints only).
        """
        return pulumi.get(self, "disable_web_cli")

    @_builtins.property
    @pulumi.getter(name="exposeStatus")
    def expose_status(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Provisioning status of the service exposure.
        """
        return pulumi.get(self, "expose_status")

    @_builtins.property
    @pulumi.getter(name="exposeType")
    def expose_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        How the endpoint is exposed (e.g. LoadBalancer).
        """
        return pulumi.get(self, "expose_type")

    @_builtins.property
    @pulumi.getter
    def exposed(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the endpoint is exposed as a service.
        """
        return pulumi.get(self, "exposed")

    @_builtins.property
    @pulumi.getter
    def groups(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "groups")

    @_builtins.property
    @pulumi.getter(name="idleTimeout")
    def idle_timeout(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "idle_timeout")

    @_builtins.property
    @pulumi.getter(name="isJitEnabled")
    def is_jit_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether Just-In-Time access approval is enabled.
        """
        return pulumi.get(self, "is_jit_enabled")

    @_builtins.property
    @pulumi.getter(name="jitApprovers")
    def jit_approvers(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Emails of users who can approve Just-In-Time access requests.
        """
        return pulumi.get(self, "jit_approvers")

    @_builtins.property
    @pulumi.getter(name="jitMode")
    def jit_mode(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Which access paths require Just-In-Time approval: session, script, or both.
        """
        return pulumi.get(self, "jit_mode")

    @_builtins.property
    @pulumi.getter(name="jitMultiApprover")
    def jit_multi_approver(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Require multiple approvers for Just-In-Time access requests.
        """
        return pulumi.get(self, "jit_multi_approver")

    @_builtins.property
    @pulumi.getter(name="jitTotalApprovers")
    def jit_total_approvers(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Number of approvals required when multi-approver is enabled.
        """
        return pulumi.get(self, "jit_total_approvers")

    @_builtins.property
    @pulumi.getter
    def memory(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "memory")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the endpoint to create.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="pauseTimeout")
    def pause_timeout(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "pause_timeout")

    @_builtins.property
    @pulumi.getter
    def resource(self) -> pulumi.Output[_builtins.str]:
        """
        The resource (by name) this endpoint grants access to.
        """
        return pulumi.get(self, "resource")

    @_builtins.property
    @pulumi.getter(name="scriptOnlyAccess")
    def script_only_access(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the endpoint is only accessible via script.
        """
        return pulumi.get(self, "script_only_access")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Current lifecycle status of the endpoint.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def ttl(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Time-to-live for the endpoint, e.g. 8h, 7d, 90d.
        """
        return pulumi.get(self, "ttl")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The type of session: direct, client, cli, or services.
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def users(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "users")

