# coding=utf-8
# *** WARNING: this file was generated by pulumi-adaptive-gen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ResourceArgs', 'Resource']

@pulumi.input_type
class ResourceArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 type: pulumi.Input[_builtins.str],
                 access_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 annotations: Optional[pulumi.Input[_builtins.str]] = None,
                 api_client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 api_client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 api_server: Optional[pulumi.Input[_builtins.str]] = None,
                 api_token: Optional[pulumi.Input[_builtins.str]] = None,
                 app_id: Optional[pulumi.Input[_builtins.str]] = None,
                 app_key: Optional[pulumi.Input[_builtins.str]] = None,
                 application_id: Optional[pulumi.Input[_builtins.str]] = None,
                 application_name: Optional[pulumi.Input[_builtins.str]] = None,
                 arn: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_access_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_arn: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_region: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_region_name: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_role_arn: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_secret_access_key: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_service_account: Optional[pulumi.Input[_builtins.str]] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 clientcert: Optional[pulumi.Input[_builtins.str]] = None,
                 cluster_cert: Optional[pulumi.Input[_builtins.str]] = None,
                 cluster_token: Optional[pulumi.Input[_builtins.str]] = None,
                 create_if_not_exists: Optional[pulumi.Input[_builtins.bool]] = None,
                 database_account: Optional[pulumi.Input[_builtins.str]] = None,
                 database_name: Optional[pulumi.Input[_builtins.str]] = None,
                 database_password: Optional[pulumi.Input[_builtins.str]] = None,
                 database_username: Optional[pulumi.Input[_builtins.str]] = None,
                 dd_api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 dd_site: Optional[pulumi.Input[_builtins.str]] = None,
                 default_cluster: Optional[pulumi.Input[_builtins.str]] = None,
                 default_user: Optional[pulumi.Input[_builtins.str]] = None,
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 host: Optional[pulumi.Input[_builtins.str]] = None,
                 hostname: Optional[pulumi.Input[_builtins.str]] = None,
                 hosts: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 image: Optional[pulumi.Input[_builtins.str]] = None,
                 index: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 key_file: Optional[pulumi.Input[_builtins.str]] = None,
                 login_url: Optional[pulumi.Input[_builtins.str]] = None,
                 namespace: Optional[pulumi.Input[_builtins.str]] = None,
                 network_id: Optional[pulumi.Input[_builtins.str]] = None,
                 node_affinity: Optional[pulumi.Input[_builtins.str]] = None,
                 node_selector: Optional[pulumi.Input[_builtins.str]] = None,
                 organization_id: Optional[pulumi.Input[_builtins.str]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 port: Optional[pulumi.Input[_builtins.str]] = None,
                 private_key: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 protocol: Optional[pulumi.Input[_builtins.str]] = None,
                 public_key: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 region_name: Optional[pulumi.Input[_builtins.str]] = None,
                 role: Optional[pulumi.Input[_builtins.str]] = None,
                 root_cert: Optional[pulumi.Input[_builtins.str]] = None,
                 schema: Optional[pulumi.Input[_builtins.str]] = None,
                 secret_access_key: Optional[pulumi.Input[_builtins.str]] = None,
                 secret_id: Optional[pulumi.Input[_builtins.str]] = None,
                 service_account_name: Optional[pulumi.Input[_builtins.str]] = None,
                 shared_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 ssl_mode: Optional[pulumi.Input[_builtins.str]] = None,
                 sub_system_name: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tls_cert_file: Optional[pulumi.Input[_builtins.str]] = None,
                 tls_key_file: Optional[pulumi.Input[_builtins.str]] = None,
                 tls_root_cert: Optional[pulumi.Input[_builtins.str]] = None,
                 token_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tolerations: Optional[pulumi.Input[_builtins.str]] = None,
                 uri: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 urls: Optional[pulumi.Input[_builtins.str]] = None,
                 use_irsa: Optional[pulumi.Input[_builtins.bool]] = None,
                 use_proxy: Optional[pulumi.Input[_builtins.bool]] = None,
                 use_rds_iam: Optional[pulumi.Input[_builtins.bool]] = None,
                 use_service_account: Optional[pulumi.Input[_builtins.bool]] = None,
                 use_tenant: Optional[pulumi.Input[_builtins.bool]] = None,
                 username: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None,
                 warehouse: Optional[pulumi.Input[_builtins.str]] = None,
                 webhook_url: Optional[pulumi.Input[_builtins.str]] = None,
                 webui_port: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Resource resource.

        :param pulumi.Input[_builtins.str] name: Name of the Adaptive resource.
        :param pulumi.Input[_builtins.str] type: Type of the Adaptive resource (integration), e.g. postgres, mysql, mongodb, ssh, kubernetes, aws, gcp, azure, snowflake.
        :param pulumi.Input[_builtins.str] default_cluster: The default cluster the resource is deployed to.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: Optional tags.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "type", type)
        if access_key_id is not None:
            pulumi.set(__self__, "access_key_id", access_key_id)
        if annotations is not None:
            pulumi.set(__self__, "annotations", annotations)
        if api_client_id is not None:
            pulumi.set(__self__, "api_client_id", api_client_id)
        if api_client_secret is not None:
            pulumi.set(__self__, "api_client_secret", api_client_secret)
        if api_key is not None:
            pulumi.set(__self__, "api_key", api_key)
        if api_server is not None:
            pulumi.set(__self__, "api_server", api_server)
        if api_token is not None:
            pulumi.set(__self__, "api_token", api_token)
        if app_id is not None:
            pulumi.set(__self__, "app_id", app_id)
        if app_key is not None:
            pulumi.set(__self__, "app_key", app_key)
        if application_id is not None:
            pulumi.set(__self__, "application_id", application_id)
        if application_name is not None:
            pulumi.set(__self__, "application_name", application_name)
        if arn is not None:
            pulumi.set(__self__, "arn", arn)
        if aws_access_key_id is not None:
            pulumi.set(__self__, "aws_access_key_id", aws_access_key_id)
        if aws_arn is not None:
            pulumi.set(__self__, "aws_arn", aws_arn)
        if aws_region is not None:
            pulumi.set(__self__, "aws_region", aws_region)
        if aws_region_name is not None:
            pulumi.set(__self__, "aws_region_name", aws_region_name)
        if aws_role_arn is not None:
            pulumi.set(__self__, "aws_role_arn", aws_role_arn)
        if aws_secret_access_key is not None:
            pulumi.set(__self__, "aws_secret_access_key", aws_secret_access_key)
        if aws_service_account is not None:
            pulumi.set(__self__, "aws_service_account", aws_service_account)
        if client_id is not None:
            pulumi.set(__self__, "client_id", client_id)
        if client_secret is not None:
            pulumi.set(__self__, "client_secret", client_secret)
        if clientcert is not None:
            pulumi.set(__self__, "clientcert", clientcert)
        if cluster_cert is not None:
            pulumi.set(__self__, "cluster_cert", cluster_cert)
        if cluster_token is not None:
            pulumi.set(__self__, "cluster_token", cluster_token)
        if create_if_not_exists is not None:
            pulumi.set(__self__, "create_if_not_exists", create_if_not_exists)
        if database_account is not None:
            pulumi.set(__self__, "database_account", database_account)
        if database_name is not None:
            pulumi.set(__self__, "database_name", database_name)
        if database_password is not None:
            pulumi.set(__self__, "database_password", database_password)
        if database_username is not None:
            pulumi.set(__self__, "database_username", database_username)
        if dd_api_key is not None:
            pulumi.set(__self__, "dd_api_key", dd_api_key)
        if dd_site is not None:
            pulumi.set(__self__, "dd_site", dd_site)
        if default_cluster is not None:
            pulumi.set(__self__, "default_cluster", default_cluster)
        if default_user is not None:
            pulumi.set(__self__, "default_user", default_user)
        if domain is not None:
            pulumi.set(__self__, "domain", domain)
        if host is not None:
            pulumi.set(__self__, "host", host)
        if hostname is not None:
            pulumi.set(__self__, "hostname", hostname)
        if hosts is not None:
            pulumi.set(__self__, "hosts", hosts)
        if image is not None:
            pulumi.set(__self__, "image", image)
        if index is not None:
            pulumi.set(__self__, "index", index)
        if key is not None:
            pulumi.set(__self__, "key", key)
        if key_file is not None:
            pulumi.set(__self__, "key_file", key_file)
        if login_url is not None:
            pulumi.set(__self__, "login_url", login_url)
        if namespace is not None:
            pulumi.set(__self__, "namespace", namespace)
        if network_id is not None:
            pulumi.set(__self__, "network_id", network_id)
        if node_affinity is not None:
            pulumi.set(__self__, "node_affinity", node_affinity)
        if node_selector is not None:
            pulumi.set(__self__, "node_selector", node_selector)
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if port is not None:
            pulumi.set(__self__, "port", port)
        if private_key is not None:
            pulumi.set(__self__, "private_key", private_key)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)
        if protocol is not None:
            pulumi.set(__self__, "protocol", protocol)
        if public_key is not None:
            pulumi.set(__self__, "public_key", public_key)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if region_name is not None:
            pulumi.set(__self__, "region_name", region_name)
        if role is not None:
            pulumi.set(__self__, "role", role)
        if root_cert is not None:
            pulumi.set(__self__, "root_cert", root_cert)
        if schema is not None:
            pulumi.set(__self__, "schema", schema)
        if secret_access_key is not None:
            pulumi.set(__self__, "secret_access_key", secret_access_key)
        if secret_id is not None:
            pulumi.set(__self__, "secret_id", secret_id)
        if service_account_name is not None:
            pulumi.set(__self__, "service_account_name", service_account_name)
        if shared_secret is not None:
            pulumi.set(__self__, "shared_secret", shared_secret)
        if ssl_mode is not None:
            pulumi.set(__self__, "ssl_mode", ssl_mode)
        if sub_system_name is not None:
            pulumi.set(__self__, "sub_system_name", sub_system_name)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tenant_id is not None:
            pulumi.set(__self__, "tenant_id", tenant_id)
        if tls_cert_file is not None:
            pulumi.set(__self__, "tls_cert_file", tls_cert_file)
        if tls_key_file is not None:
            pulumi.set(__self__, "tls_key_file", tls_key_file)
        if tls_root_cert is not None:
            pulumi.set(__self__, "tls_root_cert", tls_root_cert)
        if token_id is not None:
            pulumi.set(__self__, "token_id", token_id)
        if tolerations is not None:
            pulumi.set(__self__, "tolerations", tolerations)
        if uri is not None:
            pulumi.set(__self__, "uri", uri)
        if url is not None:
            pulumi.set(__self__, "url", url)
        if urls is not None:
            pulumi.set(__self__, "urls", urls)
        if use_irsa is not None:
            pulumi.set(__self__, "use_irsa", use_irsa)
        if use_proxy is not None:
            pulumi.set(__self__, "use_proxy", use_proxy)
        if use_rds_iam is not None:
            pulumi.set(__self__, "use_rds_iam", use_rds_iam)
        if use_service_account is not None:
            pulumi.set(__self__, "use_service_account", use_service_account)
        if use_tenant is not None:
            pulumi.set(__self__, "use_tenant", use_tenant)
        if username is not None:
            pulumi.set(__self__, "username", username)
        if version is not None:
            pulumi.set(__self__, "version", version)
        if warehouse is not None:
            pulumi.set(__self__, "warehouse", warehouse)
        if webhook_url is not None:
            pulumi.set(__self__, "webhook_url", webhook_url)
        if webui_port is not None:
            pulumi.set(__self__, "webui_port", webui_port)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        Name of the Adaptive resource.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        """
        Type of the Adaptive resource (integration), e.g. postgres, mysql, mongodb, ssh, kubernetes, aws, gcp, azure, snowflake.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter(name="accessKeyId")
    def access_key_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "access_key_id")

    @access_key_id.setter
    def access_key_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "access_key_id", value)

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "annotations")

    @annotations.setter
    def annotations(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "annotations", value)

    @_builtins.property
    @pulumi.getter(name="apiClientId")
    def api_client_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "api_client_id")

    @api_client_id.setter
    def api_client_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_client_id", value)

    @_builtins.property
    @pulumi.getter(name="apiClientSecret")
    def api_client_secret(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "api_client_secret")

    @api_client_secret.setter
    def api_client_secret(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_client_secret", value)

    @_builtins.property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "api_key")

    @api_key.setter
    def api_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_key", value)

    @_builtins.property
    @pulumi.getter(name="apiServer")
    def api_server(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "api_server")

    @api_server.setter
    def api_server(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_server", value)

    @_builtins.property
    @pulumi.getter(name="apiToken")
    def api_token(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "api_token")

    @api_token.setter
    def api_token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_token", value)

    @_builtins.property
    @pulumi.getter(name="appId")
    def app_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "app_id")

    @app_id.setter
    def app_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "app_id", value)

    @_builtins.property
    @pulumi.getter(name="appKey")
    def app_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "app_key")

    @app_key.setter
    def app_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "app_key", value)

    @_builtins.property
    @pulumi.getter(name="applicationId")
    def application_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "application_id")

    @application_id.setter
    def application_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "application_id", value)

    @_builtins.property
    @pulumi.getter(name="applicationName")
    def application_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "application_name")

    @application_name.setter
    def application_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "application_name", value)

    @_builtins.property
    @pulumi.getter
    def arn(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "arn")

    @arn.setter
    def arn(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "arn", value)

    @_builtins.property
    @pulumi.getter(name="awsAccessKeyId")
    def aws_access_key_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "aws_access_key_id")

    @aws_access_key_id.setter
    def aws_access_key_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "aws_access_key_id", value)

    @_builtins.property
    @pulumi.getter(name="awsArn")
    def aws_arn(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "aws_arn")

    @aws_arn.setter
    def aws_arn(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "aws_arn", value)

    @_builtins.property
    @pulumi.getter(name="awsRegion")
    def aws_region(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "aws_region")

    @aws_region.setter
    def aws_region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "aws_region", value)

    @_builtins.property
    @pulumi.getter(name="awsRegionName")
    def aws_region_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "aws_region_name")

    @aws_region_name.setter
    def aws_region_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "aws_region_name", value)

    @_builtins.property
    @pulumi.getter(name="awsRoleArn")
    def aws_role_arn(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "aws_role_arn")

    @aws_role_arn.setter
    def aws_role_arn(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "aws_role_arn", value)

    @_builtins.property
    @pulumi.getter(name="awsSecretAccessKey")
    def aws_secret_access_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "aws_secret_access_key")

    @aws_secret_access_key.setter
    def aws_secret_access_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "aws_secret_access_key", value)

    @_builtins.property
    @pulumi.getter(name="awsServiceAccount")
    def aws_service_account(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "aws_service_account")

    @aws_service_account.setter
    def aws_service_account(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "aws_service_account", value)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "client_id")

    @client_id.setter
    def client_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "client_id", value)

    @_builtins.property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "client_secret")

    @client_secret.setter
    def client_secret(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "client_secret", value)

    @_builtins.property
    @pulumi.getter
    def clientcert(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "clientcert")

    @clientcert.setter
    def clientcert(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "clientcert", value)

    @_builtins.property
    @pulumi.getter(name="clusterCert")
    def cluster_cert(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "cluster_cert")

    @cluster_cert.setter
    def cluster_cert(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cluster_cert", value)

    @_builtins.property
    @pulumi.getter(name="clusterToken")
    def cluster_token(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "cluster_token")

    @cluster_token.setter
    def cluster_token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cluster_token", value)

    @_builtins.property
    @pulumi.getter(name="createIfNotExists")
    def create_if_not_exists(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "create_if_not_exists")

    @create_if_not_exists.setter
    def create_if_not_exists(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "create_if_not_exists", value)

    @_builtins.property
    @pulumi.getter(name="databaseAccount")
    def database_account(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "database_account")

    @database_account.setter
    def database_account(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "database_account", value)

    @_builtins.property
    @pulumi.getter(name="databaseName")
    def database_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "database_name")

    @database_name.setter
    def database_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "database_name", value)

    @_builtins.property
    @pulumi.getter(name="databasePassword")
    def database_password(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "database_password")

    @database_password.setter
    def database_password(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "database_password", value)

    @_builtins.property
    @pulumi.getter(name="databaseUsername")
    def database_username(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "database_username")

    @database_username.setter
    def database_username(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "database_username", value)

    @_builtins.property
    @pulumi.getter(name="ddApiKey")
    def dd_api_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "dd_api_key")

    @dd_api_key.setter
    def dd_api_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "dd_api_key", value)

    @_builtins.property
    @pulumi.getter(name="ddSite")
    def dd_site(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "dd_site")

    @dd_site.setter
    def dd_site(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "dd_site", value)

    @_builtins.property
    @pulumi.getter(name="defaultCluster")
    def default_cluster(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The default cluster the resource is deployed to.
        """
        return pulumi.get(self, "default_cluster")

    @default_cluster.setter
    def default_cluster(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "default_cluster", value)

    @_builtins.property
    @pulumi.getter(name="defaultUser")
    def default_user(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "default_user")

    @default_user.setter
    def default_user(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "default_user", value)

    @_builtins.property
    @pulumi.getter
    def domain(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "domain", value)

    @_builtins.property
    @pulumi.getter
    def host(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "host")

    @host.setter
    def host(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "host", value)

    @_builtins.property
    @pulumi.getter
    def hostname(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "hostname")

    @hostname.setter
    def hostname(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "hostname", value)

    @_builtins.property
    @pulumi.getter
    def hosts(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "hosts")

    @hosts.setter
    def hosts(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "hosts", value)

    @_builtins.property
    @pulumi.getter
    def image(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "image")

    @image.setter
    def image(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "image", value)

    @_builtins.property
    @pulumi.getter
    def index(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "index")

    @index.setter
    def index(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "index", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter(name="keyFile")
    def key_file(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "key_file")

    @key_file.setter
    def key_file(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key_file", value)

    @_builtins.property
    @pulumi.getter(name="loginUrl")
    def login_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "login_url")

    @login_url.setter
    def login_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "login_url", value)

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "namespace")

    @namespace.setter
    def namespace(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "namespace", value)

    @_builtins.property
    @pulumi.getter(name="networkId")
    def network_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "network_id")

    @network_id.setter
    def network_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "network_id", value)

    @_builtins.property
    @pulumi.getter(name="nodeAffinity")
    def node_affinity(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "node_affinity")

    @node_affinity.setter
    def node_affinity(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "node_affinity", value)

    @_builtins.property
    @pulumi.getter(name="nodeSelector")
    def node_selector(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "node_selector")

    @node_selector.setter
    def node_selector(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "node_selector", value)

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "organization_id", value)

    @_builtins.property
    @pulumi.getter
    def password(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter
    def port(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "port", value)

    @_builtins.property
    @pulumi.getter(name="privateKey")
    def private_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "private_key")

    @private_key.setter
    def private_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "private_key", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "protocol")

    @protocol.setter
    def protocol(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "protocol", value)

    @_builtins.property
    @pulumi.getter(name="publicKey")
    def public_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "public_key")

    @public_key.setter
    def public_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "public_key", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="regionName")
    def region_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "region_name")

    @region_name.setter
    def region_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "region_name", value)

    @_builtins.property
    @pulumi.getter
    def role(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "role")

    @role.setter
    def role(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "role", value)

    @_builtins.property
    @pulumi.getter(name="rootCert")
    def root_cert(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "root_cert")

    @root_cert.setter
    def root_cert(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "root_cert", value)

    @_builtins.property
    @pulumi.getter
    def schema(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "schema")

    @schema.setter
    def schema(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "schema", value)

    @_builtins.property
    @pulumi.getter(name="secretAccessKey")
    def secret_access_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "secret_access_key")

    @secret_access_key.setter
    def secret_access_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "secret_access_key", value)

    @_builtins.property
    @pulumi.getter(name="secretId")
    def secret_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "secret_id")

    @secret_id.setter
    def secret_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "secret_id", value)

    @_builtins.property
    @pulumi.getter(name="serviceAccountName")
    def service_account_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "service_account_name")

    @service_account_name.setter
    def service_account_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "service_account_name", value)

    @_builtins.property
    @pulumi.getter(name="sharedSecret")
    def shared_secret(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "shared_secret")

    @shared_secret.setter
    def shared_secret(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "shared_secret", value)

    @_builtins.property
    @pulumi.getter(name="sslMode")
    def ssl_mode(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "ssl_mode")

    @ssl_mode.setter
    def ssl_mode(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ssl_mode", value)

    @_builtins.property
    @pulumi.getter(name="subSystemName")
    def sub_system_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "sub_system_name")

    @sub_system_name.setter
    def sub_system_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "sub_system_name", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Optional tags.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "tenant_id")

    @tenant_id.setter
    def tenant_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tenant_id", value)

    @_builtins.property
    @pulumi.getter(name="tlsCertFile")
    def tls_cert_file(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "tls_cert_file")

    @tls_cert_file.setter
    def tls_cert_file(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tls_cert_file", value)

    @_builtins.property
    @pulumi.getter(name="tlsKeyFile")
    def tls_key_file(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "tls_key_file")

    @tls_key_file.setter
    def tls_key_file(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tls_key_file", value)

    @_builtins.property
    @pulumi.getter(name="tlsRootCert")
    def tls_root_cert(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "tls_root_cert")

    @tls_root_cert.setter
    def tls_root_cert(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tls_root_cert", value)

    @_builtins.property
    @pulumi.getter(name="tokenId")
    def token_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "token_id")

    @token_id.setter
    def token_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "token_id", value)

    @_builtins.property
    @pulumi.getter
    def tolerations(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "tolerations")

    @tolerations.setter
    def tolerations(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tolerations", value)

    @_builtins.property
    @pulumi.getter
    def uri(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "uri")

    @uri.setter
    def uri(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "uri", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)

    @_builtins.property
    @pulumi.getter
    def urls(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "urls")

    @urls.setter
    def urls(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "urls", value)

    @_builtins.property
    @pulumi.getter(name="useIrsa")
    def use_irsa(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "use_irsa")

    @use_irsa.setter
    def use_irsa(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "use_irsa", value)

    @_builtins.property
    @pulumi.getter(name="useProxy")
    def use_proxy(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "use_proxy")

    @use_proxy.setter
    def use_proxy(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "use_proxy", value)

    @_builtins.property
    @pulumi.getter(name="useRdsIam")
    def use_rds_iam(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "use_rds_iam")

    @use_rds_iam.setter
    def use_rds_iam(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "use_rds_iam", value)

    @_builtins.property
    @pulumi.getter(name="useServiceAccount")
    def use_service_account(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "use_service_account")

    @use_service_account.setter
    def use_service_account(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "use_service_account", value)

    @_builtins.property
    @pulumi.getter(name="useTenant")
    def use_tenant(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "use_tenant")

    @use_tenant.setter
    def use_tenant(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "use_tenant", value)

    @_builtins.property
    @pulumi.getter
    def username(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "username")

    @username.setter
    def username(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "username", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "version", value)

    @_builtins.property
    @pulumi.getter
    def warehouse(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "warehouse")

    @warehouse.setter
    def warehouse(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "warehouse", value)

    @_builtins.property
    @pulumi.getter(name="webhookUrl")
    def webhook_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "webhook_url")

    @webhook_url.setter
    def webhook_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "webhook_url", value)

    @_builtins.property
    @pulumi.getter(name="webuiPort")
    def webui_port(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "webui_port")

    @webui_port.setter
    def webui_port(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "webui_port", value)


@pulumi.type_token("adaptive:index:Resource")
class Resource(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 annotations: Optional[pulumi.Input[_builtins.str]] = None,
                 api_client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 api_client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 api_server: Optional[pulumi.Input[_builtins.str]] = None,
                 api_token: Optional[pulumi.Input[_builtins.str]] = None,
                 app_id: Optional[pulumi.Input[_builtins.str]] = None,
                 app_key: Optional[pulumi.Input[_builtins.str]] = None,
                 application_id: Optional[pulumi.Input[_builtins.str]] = None,
                 application_name: Optional[pulumi.Input[_builtins.str]] = None,
                 arn: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_access_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_arn: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_region: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_region_name: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_role_arn: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_secret_access_key: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_service_account: Optional[pulumi.Input[_builtins.str]] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 clientcert: Optional[pulumi.Input[_builtins.str]] = None,
                 cluster_cert: Optional[pulumi.Input[_builtins.str]] = None,
                 cluster_token: Optional[pulumi.Input[_builtins.str]] = None,
                 create_if_not_exists: Optional[pulumi.Input[_builtins.bool]] = None,
                 database_account: Optional[pulumi.Input[_builtins.str]] = None,
                 database_name: Optional[pulumi.Input[_builtins.str]] = None,
                 database_password: Optional[pulumi.Input[_builtins.str]] = None,
                 database_username: Optional[pulumi.Input[_builtins.str]] = None,
                 dd_api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 dd_site: Optional[pulumi.Input[_builtins.str]] = None,
                 default_cluster: Optional[pulumi.Input[_builtins.str]] = None,
                 default_user: Optional[pulumi.Input[_builtins.str]] = None,
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 host: Optional[pulumi.Input[_builtins.str]] = None,
                 hostname: Optional[pulumi.Input[_builtins.str]] = None,
                 hosts: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 image: Optional[pulumi.Input[_builtins.str]] = None,
                 index: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 key_file: Optional[pulumi.Input[_builtins.str]] = None,
                 login_url: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 namespace: Optional[pulumi.Input[_builtins.str]] = None,
                 network_id: Optional[pulumi.Input[_builtins.str]] = None,
                 node_affinity: Optional[pulumi.Input[_builtins.str]] = None,
                 node_selector: Optional[pulumi.Input[_builtins.str]] = None,
                 organization_id: Optional[pulumi.Input[_builtins.str]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 port: Optional[pulumi.Input[_builtins.str]] = None,
                 private_key: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 protocol: Optional[pulumi.Input[_builtins.str]] = None,
                 public_key: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 region_name: Optional[pulumi.Input[_builtins.str]] = None,
                 role: Optional[pulumi.Input[_builtins.str]] = None,
                 root_cert: Optional[pulumi.Input[_builtins.str]] = None,
                 schema: Optional[pulumi.Input[_builtins.str]] = None,
                 secret_access_key: Optional[pulumi.Input[_builtins.str]] = None,
                 secret_id: Optional[pulumi.Input[_builtins.str]] = None,
                 service_account_name: Optional[pulumi.Input[_builtins.str]] = None,
                 shared_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 ssl_mode: Optional[pulumi.Input[_builtins.str]] = None,
                 sub_system_name: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tls_cert_file: Optional[pulumi.Input[_builtins.str]] = None,
                 tls_key_file: Optional[pulumi.Input[_builtins.str]] = None,
                 tls_root_cert: Optional[pulumi.Input[_builtins.str]] = None,
                 token_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tolerations: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 uri: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 urls: Optional[pulumi.Input[_builtins.str]] = None,
                 use_irsa: Optional[pulumi.Input[_builtins.bool]] = None,
                 use_proxy: Optional[pulumi.Input[_builtins.bool]] = None,
                 use_rds_iam: Optional[pulumi.Input[_builtins.bool]] = None,
                 use_service_account: Optional[pulumi.Input[_builtins.bool]] = None,
                 use_tenant: Optional[pulumi.Input[_builtins.bool]] = None,
                 username: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None,
                 warehouse: Optional[pulumi.Input[_builtins.str]] = None,
                 webhook_url: Optional[pulumi.Input[_builtins.str]] = None,
                 webui_port: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Resource resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] default_cluster: The default cluster the resource is deployed to.
        :param pulumi.Input[_builtins.str] name: Name of the Adaptive resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: Optional tags.
        :param pulumi.Input[_builtins.str] type: Type of the Adaptive resource (integration), e.g. postgres, mysql, mongodb, ssh, kubernetes, aws, gcp, azure, snowflake.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ResourceArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Resource resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ResourceArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ResourceArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 annotations: Optional[pulumi.Input[_builtins.str]] = None,
                 api_client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 api_client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 api_server: Optional[pulumi.Input[_builtins.str]] = None,
                 api_token: Optional[pulumi.Input[_builtins.str]] = None,
                 app_id: Optional[pulumi.Input[_builtins.str]] = None,
                 app_key: Optional[pulumi.Input[_builtins.str]] = None,
                 application_id: Optional[pulumi.Input[_builtins.str]] = None,
                 application_name: Optional[pulumi.Input[_builtins.str]] = None,
                 arn: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_access_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_arn: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_region: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_region_name: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_role_arn: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_secret_access_key: Optional[pulumi.Input[_builtins.str]] = None,
                 aws_service_account: Optional[pulumi.Input[_builtins.str]] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 clientcert: Optional[pulumi.Input[_builtins.str]] = None,
                 cluster_cert: Optional[pulumi.Input[_builtins.str]] = None,
                 cluster_token: Optional[pulumi.Input[_builtins.str]] = None,
                 create_if_not_exists: Optional[pulumi.Input[_builtins.bool]] = None,
                 database_account: Optional[pulumi.Input[_builtins.str]] = None,
                 database_name: Optional[pulumi.Input[_builtins.str]] = None,
                 database_password: Optional[pulumi.Input[_builtins.str]] = None,
                 database_username: Optional[pulumi.Input[_builtins.str]] = None,
                 dd_api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 dd_site: Optional[pulumi.Input[_builtins.str]] = None,
                 default_cluster: Optional[pulumi.Input[_builtins.str]] = None,
                 default_user: Optional[pulumi.Input[_builtins.str]] = None,
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 host: Optional[pulumi.Input[_builtins.str]] = None,
                 hostname: Optional[pulumi.Input[_builtins.str]] = None,
                 hosts: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 image: Optional[pulumi.Input[_builtins.str]] = None,
                 index: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 key_file: Optional[pulumi.Input[_builtins.str]] = None,
                 login_url: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 namespace: Optional[pulumi.Input[_builtins.str]] = None,
                 network_id: Optional[pulumi.Input[_builtins.str]] = None,
                 node_affinity: Optional[pulumi.Input[_builtins.str]] = None,
                 node_selector: Optional[pulumi.Input[_builtins.str]] = None,
                 organization_id: Optional[pulumi.Input[_builtins.str]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 port: Optional[pulumi.Input[_builtins.str]] = None,
                 private_key: Optional[pulumi.Input[_builtins.str]] = None,
                 project_id: Optional[pulumi.Input[_builtins.str]] = None,
                 protocol: Optional[pulumi.Input[_builtins.str]] = None,
                 public_key: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 region_name: Optional[pulumi.Input[_builtins.str]] = None,
                 role: Optional[pulumi.Input[_builtins.str]] = None,
                 root_cert: Optional[pulumi.Input[_builtins.str]] = None,
                 schema: Optional[pulumi.Input[_builtins.str]] = None,
                 secret_access_key: Optional[pulumi.Input[_builtins.str]] = None,
                 secret_id: Optional[pulumi.Input[_builtins.str]] = None,
                 service_account_name: Optional[pulumi.Input[_builtins.str]] = None,
                 shared_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 ssl_mode: Optional[pulumi.Input[_builtins.str]] = None,
                 sub_system_name: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 tenant_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tls_cert_file: Optional[pulumi.Input[_builtins.str]] = None,
                 tls_key_file: Optional[pulumi.Input[_builtins.str]] = None,
                 tls_root_cert: Optional[pulumi.Input[_builtins.str]] = None,
                 token_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tolerations: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 uri: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 urls: Optional[pulumi.Input[_builtins.str]] = None,
                 use_irsa: Optional[pulumi.Input[_builtins.bool]] = None,
                 use_proxy: Optional[pulumi.Input[_builtins.bool]] = None,
                 use_rds_iam: Optional[pulumi.Input[_builtins.bool]] = None,
                 use_service_account: Optional[pulumi.Input[_builtins.bool]] = None,
                 use_tenant: Optional[pulumi.Input[_builtins.bool]] = None,
                 username: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None,
                 warehouse: Optional[pulumi.Input[_builtins.str]] = None,
                 webhook_url: Optional[pulumi.Input[_builtins.str]] = None,
                 webui_port: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ResourceArgs.__new__(ResourceArgs)

            __props__.__dict__["access_key_id"] = None if access_key_id is None else pulumi.Output.secret(access_key_id)
            __props__.__dict__["annotations"] = annotations
            __props__.__dict__["api_client_id"] = api_client_id
            __props__.__dict__["api_client_secret"] = None if api_client_secret is None else pulumi.Output.secret(api_client_secret)
            __props__.__dict__["api_key"] = None if api_key is None else pulumi.Output.secret(api_key)
            __props__.__dict__["api_server"] = api_server
            __props__.__dict__["api_token"] = None if api_token is None else pulumi.Output.secret(api_token)
            __props__.__dict__["app_id"] = app_id
            __props__.__dict__["app_key"] = None if app_key is None else pulumi.Output.secret(app_key)
            __props__.__dict__["application_id"] = application_id
            __props__.__dict__["application_name"] = application_name
            __props__.__dict__["arn"] = arn
            __props__.__dict__["aws_access_key_id"] = aws_access_key_id
            __props__.__dict__["aws_arn"] = aws_arn
            __props__.__dict__["aws_region"] = aws_region
            __props__.__dict__["aws_region_name"] = aws_region_name
            __props__.__dict__["aws_role_arn"] = aws_role_arn
            __props__.__dict__["aws_secret_access_key"] = None if aws_secret_access_key is None else pulumi.Output.secret(aws_secret_access_key)
            __props__.__dict__["aws_service_account"] = aws_service_account
            __props__.__dict__["client_id"] = client_id
            __props__.__dict__["client_secret"] = None if client_secret is None else pulumi.Output.secret(client_secret)
            __props__.__dict__["clientcert"] = None if clientcert is None else pulumi.Output.secret(clientcert)
            __props__.__dict__["cluster_cert"] = None if cluster_cert is None else pulumi.Output.secret(cluster_cert)
            __props__.__dict__["cluster_token"] = None if cluster_token is None else pulumi.Output.secret(cluster_token)
            __props__.__dict__["create_if_not_exists"] = create_if_not_exists
            __props__.__dict__["database_account"] = database_account
            __props__.__dict__["database_name"] = database_name
            __props__.__dict__["database_password"] = None if database_password is None else pulumi.Output.secret(database_password)
            __props__.__dict__["database_username"] = database_username
            __props__.__dict__["dd_api_key"] = None if dd_api_key is None else pulumi.Output.secret(dd_api_key)
            __props__.__dict__["dd_site"] = dd_site
            __props__.__dict__["default_cluster"] = default_cluster
            __props__.__dict__["default_user"] = default_user
            __props__.__dict__["domain"] = domain
            __props__.__dict__["host"] = host
            __props__.__dict__["hostname"] = hostname
            __props__.__dict__["hosts"] = hosts
            __props__.__dict__["image"] = image
            __props__.__dict__["index"] = index
            __props__.__dict__["key"] = None if key is None else pulumi.Output.secret(key)
            __props__.__dict__["key_file"] = None if key_file is None else pulumi.Output.secret(key_file)
            __props__.__dict__["login_url"] = login_url
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["namespace"] = namespace
            __props__.__dict__["network_id"] = network_id
            __props__.__dict__["node_affinity"] = node_affinity
            __props__.__dict__["node_selector"] = node_selector
            __props__.__dict__["organization_id"] = organization_id
            __props__.__dict__["password"] = None if password is None else pulumi.Output.secret(password)
            __props__.__dict__["port"] = port
            __props__.__dict__["private_key"] = None if private_key is None else pulumi.Output.secret(private_key)
            __props__.__dict__["project_id"] = project_id
            __props__.__dict__["protocol"] = protocol
            __props__.__dict__["public_key"] = public_key
            __props__.__dict__["region"] = region
            __props__.__dict__["region_name"] = region_name
            __props__.__dict__["role"] = role
            __props__.__dict__["root_cert"] = None if root_cert is None else pulumi.Output.secret(root_cert)
            __props__.__dict__["schema"] = schema
            __props__.__dict__["secret_access_key"] = None if secret_access_key is None else pulumi.Output.secret(secret_access_key)
            __props__.__dict__["secret_id"] = secret_id
            __props__.__dict__["service_account_name"] = service_account_name
            __props__.__dict__["shared_secret"] = None if shared_secret is None else pulumi.Output.secret(shared_secret)
            __props__.__dict__["ssl_mode"] = ssl_mode
            __props__.__dict__["sub_system_name"] = sub_system_name
            __props__.__dict__["tags"] = tags
            __props__.__dict__["tenant_id"] = tenant_id
            __props__.__dict__["tls_cert_file"] = None if tls_cert_file is None else pulumi.Output.secret(tls_cert_file)
            __props__.__dict__["tls_key_file"] = None if tls_key_file is None else pulumi.Output.secret(tls_key_file)
            __props__.__dict__["tls_root_cert"] = None if tls_root_cert is None else pulumi.Output.secret(tls_root_cert)
            __props__.__dict__["token_id"] = token_id
            __props__.__dict__["tolerations"] = tolerations
            if type is None and not opts.urn:
                raise TypeError("Missing required property 'type'")
            __props__.__dict__["type"] = type
            __props__.__dict__["uri"] = uri
            __props__.__dict__["url"] = url
            __props__.__dict__["urls"] = urls
            __props__.__dict__["use_irsa"] = use_irsa
            __props__.__dict__["use_proxy"] = use_proxy
            __props__.__dict__["use_rds_iam"] = use_rds_iam
            __props__.__dict__["use_service_account"] = use_service_account
            __props__.__dict__["use_tenant"] = use_tenant
            __props__.__dict__["username"] = username
            __props__.__dict__["version"] = version
            __props__.__dict__["warehouse"] = warehouse
            __props__.__dict__["webhook_url"] = None if webhook_url is None else pulumi.Output.secret(webhook_url)
            __props__.__dict__["webui_port"] = webui_port
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["accessKeyId", "apiClientSecret", "apiKey", "apiToken", "appKey", "awsSecretAccessKey", "clientSecret", "clientcert", "clusterCert", "clusterToken", "databasePassword", "ddApiKey", "key", "keyFile", "password", "privateKey", "rootCert", "secretAccessKey", "sharedSecret", "tlsCertFile", "tlsKeyFile", "tlsRootCert", "webhookUrl"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Resource, __self__).__init__(
            'adaptive:index:Resource',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Resource':
        """
        Get an existing Resource resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ResourceArgs.__new__(ResourceArgs)

        __props__.__dict__["access_key_id"] = None
        __props__.__dict__["annotations"] = None
        __props__.__dict__["api_client_id"] = None
        __props__.__dict__["api_client_secret"] = None
        __props__.__dict__["api_key"] = None
        __props__.__dict__["api_server"] = None
        __props__.__dict__["api_token"] = None
        __props__.__dict__["app_id"] = None
        __props__.__dict__["app_key"] = None
        __props__.__dict__["application_id"] = None
        __props__.__dict__["application_name"] = None
        __props__.__dict__["arn"] = None
        __props__.__dict__["aws_access_key_id"] = None
        __props__.__dict__["aws_arn"] = None
        __props__.__dict__["aws_region"] = None
        __props__.__dict__["aws_region_name"] = None
        __props__.__dict__["aws_role_arn"] = None
        __props__.__dict__["aws_secret_access_key"] = None
        __props__.__dict__["aws_service_account"] = None
        __props__.__dict__["client_id"] = None
        __props__.__dict__["client_secret"] = None
        __props__.__dict__["clientcert"] = None
        __props__.__dict__["cluster_cert"] = None
        __props__.__dict__["cluster_token"] = None
        __props__.__dict__["create_if_not_exists"] = None
        __props__.__dict__["database_account"] = None
        __props__.__dict__["database_name"] = None
        __props__.__dict__["database_password"] = None
        __props__.__dict__["database_username"] = None
        __props__.__dict__["dd_api_key"] = None
        __props__.__dict__["dd_site"] = None
        __props__.__dict__["default_cluster"] = None
        __props__.__dict__["default_user"] = None
        __props__.__dict__["domain"] = None
        __props__.__dict__["host"] = None
        __props__.__dict__["hostname"] = None
        __props__.__dict__["hosts"] = None
        __props__.__dict__["image"] = None
        __props__.__dict__["index"] = None
        __props__.__dict__["key"] = None
        __props__.__dict__["key_file"] = None
        __props__.__dict__["login_url"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["namespace"] = None
        __props__.__dict__["network_id"] = None
        __props__.__dict__["node_affinity"] = None
        __props__.__dict__["node_selector"] = None
        __props__.__dict__["organization_id"] = None
        __props__.__dict__["password"] = None
        __props__.__dict__["port"] = None
        __props__.__dict__["private_key"] = None
        __props__.__dict__["project_id"] = None
        __props__.__dict__["protocol"] = None
        __props__.__dict__["public_key"] = None
        __props__.__dict__["region"] = None
        __props__.__dict__["region_name"] = None
        __props__.__dict__["role"] = None
        __props__.__dict__["root_cert"] = None
        __props__.__dict__["schema"] = None
        __props__.__dict__["secret_access_key"] = None
        __props__.__dict__["secret_id"] = None
        __props__.__dict__["service_account_name"] = None
        __props__.__dict__["shared_secret"] = None
        __props__.__dict__["ssl_mode"] = None
        __props__.__dict__["sub_system_name"] = None
        __props__.__dict__["tags"] = None
        __props__.__dict__["tenant_id"] = None
        __props__.__dict__["tls_cert_file"] = None
        __props__.__dict__["tls_key_file"] = None
        __props__.__dict__["tls_root_cert"] = None
        __props__.__dict__["token_id"] = None
        __props__.__dict__["tolerations"] = None
        __props__.__dict__["type"] = None
        __props__.__dict__["uri"] = None
        __props__.__dict__["url"] = None
        __props__.__dict__["urls"] = None
        __props__.__dict__["use_irsa"] = None
        __props__.__dict__["use_proxy"] = None
        __props__.__dict__["use_rds_iam"] = None
        __props__.__dict__["use_service_account"] = None
        __props__.__dict__["use_tenant"] = None
        __props__.__dict__["username"] = None
        __props__.__dict__["version"] = None
        __props__.__dict__["warehouse"] = None
        __props__.__dict__["webhook_url"] = None
        __props__.__dict__["webui_port"] = None
        return Resource(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accessKeyId")
    def access_key_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "access_key_id")

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "annotations")

    @_builtins.property
    @pulumi.getter(name="apiClientId")
    def api_client_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "api_client_id")

    @_builtins.property
    @pulumi.getter(name="apiClientSecret")
    def api_client_secret(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "api_client_secret")

    @_builtins.property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "api_key")

    @_builtins.property
    @pulumi.getter(name="apiServer")
    def api_server(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "api_server")

    @_builtins.property
    @pulumi.getter(name="apiToken")
    def api_token(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "api_token")

    @_builtins.property
    @pulumi.getter(name="appId")
    def app_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "app_id")

    @_builtins.property
    @pulumi.getter(name="appKey")
    def app_key(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "app_key")

    @_builtins.property
    @pulumi.getter(name="applicationId")
    def application_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "application_id")

    @_builtins.property
    @pulumi.getter(name="applicationName")
    def application_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "application_name")

    @_builtins.property
    @pulumi.getter
    def arn(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "arn")

    @_builtins.property
    @pulumi.getter(name="awsAccessKeyId")
    def aws_access_key_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "aws_access_key_id")

    @_builtins.property
    @pulumi.getter(name="awsArn")
    def aws_arn(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "aws_arn")

    @_builtins.property
    @pulumi.getter(name="awsRegion")
    def aws_region(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "aws_region")

    @_builtins.property
    @pulumi.getter(name="awsRegionName")
    def aws_region_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "aws_region_name")

    @_builtins.property
    @pulumi.getter(name="awsRoleArn")
    def aws_role_arn(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "aws_role_arn")

    @_builtins.property
    @pulumi.getter(name="awsSecretAccessKey")
    def aws_secret_access_key(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "aws_secret_access_key")

    @_builtins.property
    @pulumi.getter(name="awsServiceAccount")
    def aws_service_account(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "aws_service_account")

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "client_id")

    @_builtins.property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "client_secret")

    @_builtins.property
    @pulumi.getter
    def clientcert(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "clientcert")

    @_builtins.property
    @pulumi.getter(name="clusterCert")
    def cluster_cert(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "cluster_cert")

    @_builtins.property
    @pulumi.getter(name="clusterToken")
    def cluster_token(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "cluster_token")

    @_builtins.property
    @pulumi.getter(name="createIfNotExists")
    def create_if_not_exists(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "create_if_not_exists")

    @_builtins.property
    @pulumi.getter(name="databaseAccount")
    def database_account(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "database_account")

    @_builtins.property
    @pulumi.getter(name="databaseName")
    def database_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "database_name")

    @_builtins.property
    @pulumi.getter(name="databasePassword")
    def database_password(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "database_password")

    @_builtins.property
    @pulumi.getter(name="databaseUsername")
    def database_username(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "database_username")

    @_builtins.property
    @pulumi.getter(name="ddApiKey")
    def dd_api_key(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "dd_api_key")

    @_builtins.property
    @pulumi.getter(name="ddSite")
    def dd_site(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "dd_site")

    @_builtins.property
    @pulumi.getter(name="defaultCluster")
    def default_cluster(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The default cluster the resource is deployed to.
        """
        return pulumi.get(self, "default_cluster")

    @_builtins.property
    @pulumi.getter(name="defaultUser")
    def default_user(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "default_user")

    @_builtins.property
    @pulumi.getter
    def domain(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter
    def host(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "host")

    @_builtins.property
    @pulumi.getter
    def hostname(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "hostname")

    @_builtins.property
    @pulumi.getter
    def hosts(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "hosts")

    @_builtins.property
    @pulumi.getter
    def image(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "image")

    @_builtins.property
    @pulumi.getter
    def index(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "index")

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter(name="keyFile")
    def key_file(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "key_file")

    @_builtins.property
    @pulumi.getter(name="loginUrl")
    def login_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "login_url")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the Adaptive resource.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "namespace")

    @_builtins.property
    @pulumi.getter(name="networkId")
    def network_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "network_id")

    @_builtins.property
    @pulumi.getter(name="nodeAffinity")
    def node_affinity(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "node_affinity")

    @_builtins.property
    @pulumi.getter(name="nodeSelector")
    def node_selector(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "node_selector")

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "organization_id")

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "password")

    @_builtins.property
    @pulumi.getter
    def port(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "port")

    @_builtins.property
    @pulumi.getter(name="privateKey")
    def private_key(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "private_key")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "protocol")

    @_builtins.property
    @pulumi.getter(name="publicKey")
    def public_key(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "public_key")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="regionName")
    def region_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "region_name")

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "role")

    @_builtins.property
    @pulumi.getter(name="rootCert")
    def root_cert(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "root_cert")

    @_builtins.property
    @pulumi.getter
    def schema(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "schema")

    @_builtins.property
    @pulumi.getter(name="secretAccessKey")
    def secret_access_key(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "secret_access_key")

    @_builtins.property
    @pulumi.getter(name="secretId")
    def secret_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "secret_id")

    @_builtins.property
    @pulumi.getter(name="serviceAccountName")
    def service_account_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "service_account_name")

    @_builtins.property
    @pulumi.getter(name="sharedSecret")
    def shared_secret(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "shared_secret")

    @_builtins.property
    @pulumi.getter(name="sslMode")
    def ssl_mode(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ssl_mode")

    @_builtins.property
    @pulumi.getter(name="subSystemName")
    def sub_system_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "sub_system_name")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Optional tags.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "tenant_id")

    @_builtins.property
    @pulumi.getter(name="tlsCertFile")
    def tls_cert_file(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "tls_cert_file")

    @_builtins.property
    @pulumi.getter(name="tlsKeyFile")
    def tls_key_file(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "tls_key_file")

    @_builtins.property
    @pulumi.getter(name="tlsRootCert")
    def tls_root_cert(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "tls_root_cert")

    @_builtins.property
    @pulumi.getter(name="tokenId")
    def token_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "token_id")

    @_builtins.property
    @pulumi.getter
    def tolerations(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "tolerations")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[_builtins.str]:
        """
        Type of the Adaptive resource (integration), e.g. postgres, mysql, mongodb, ssh, kubernetes, aws, gcp, azure, snowflake.
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def uri(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "uri")

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "url")

    @_builtins.property
    @pulumi.getter
    def urls(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "urls")

    @_builtins.property
    @pulumi.getter(name="useIrsa")
    def use_irsa(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "use_irsa")

    @_builtins.property
    @pulumi.getter(name="useProxy")
    def use_proxy(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "use_proxy")

    @_builtins.property
    @pulumi.getter(name="useRdsIam")
    def use_rds_iam(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "use_rds_iam")

    @_builtins.property
    @pulumi.getter(name="useServiceAccount")
    def use_service_account(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "use_service_account")

    @_builtins.property
    @pulumi.getter(name="useTenant")
    def use_tenant(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "use_tenant")

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "username")

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "version")

    @_builtins.property
    @pulumi.getter
    def warehouse(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "warehouse")

    @_builtins.property
    @pulumi.getter(name="webhookUrl")
    def webhook_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "webhook_url")

    @_builtins.property
    @pulumi.getter(name="webuiPort")
    def webui_port(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "webui_port")

