# coding=utf-8
# *** WARNING: this file was generated by pulumi-adaptive-gen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ScheduleArgs', 'Schedule']

@pulumi.input_type
class ScheduleArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 schedule_type: pulumi.Input[_builtins.str],
                 all_day: Optional[pulumi.Input[_builtins.bool]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 end_day: Optional[pulumi.Input[_builtins.int]] = None,
                 end_hour: Optional[pulumi.Input[_builtins.int]] = None,
                 end_minute: Optional[pulumi.Input[_builtins.int]] = None,
                 endpoints: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 expires_at: Optional[pulumi.Input[_builtins.str]] = None,
                 is_active: Optional[pulumi.Input[_builtins.bool]] = None,
                 max_access_time: Optional[pulumi.Input[_builtins.int]] = None,
                 operation_type: Optional[pulumi.Input[_builtins.str]] = None,
                 specific_dates: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 start_day: Optional[pulumi.Input[_builtins.int]] = None,
                 start_hour: Optional[pulumi.Input[_builtins.int]] = None,
                 start_minute: Optional[pulumi.Input[_builtins.int]] = None,
                 teams: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timezone: Optional[pulumi.Input[_builtins.str]] = None,
                 users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 weekdays: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a Schedule resource.

        :param pulumi.Input[_builtins.str] name: Name of the schedule. Note: the Adaptive API upserts schedules by name, so creating a schedule whose name already exists adopts the existing schedule.
        :param pulumi.Input[_builtins.str] schedule_type: The schedule pattern: weekdays, weekends, everyday, monthly, specific, or custom.
        :param pulumi.Input[_builtins.bool] all_day: Whether the schedule covers the whole day (start/end times are ignored).
        :param pulumi.Input[_builtins.str] description: An optional description of the schedule.
        :param pulumi.Input[_builtins.int] end_day: Day of month (1-31) the window closes, for monthly schedules.
        :param pulumi.Input[_builtins.int] end_hour: Hour (0-23) the window closes.
        :param pulumi.Input[_builtins.int] end_minute: Minute (0-59) the window closes.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] endpoints: Names of endpoints the schedule applies to.
        :param pulumi.Input[_builtins.str] expires_at: RFC3339 timestamp after which the schedule no longer applies.
        :param pulumi.Input[_builtins.bool] is_active: Whether the schedule is active.
        :param pulumi.Input[_builtins.int] max_access_time: Maximum access duration in minutes granted by an auto-approval.
        :param pulumi.Input[_builtins.str] operation_type: What the schedule does inside its window: autoapprove or autoreject.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] specific_dates: RFC3339 dates for a specific-dates schedule.
        :param pulumi.Input[_builtins.int] start_day: Day of month (1-31) the window opens, for monthly schedules.
        :param pulumi.Input[_builtins.int] start_hour: Hour (0-23) the window opens.
        :param pulumi.Input[_builtins.int] start_minute: Minute (0-59) the window opens.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] teams: Names of groups the schedule applies to.
        :param pulumi.Input[_builtins.str] timezone: IANA timezone for the schedule window. Empty inherits the workspace default.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] users: Emails of users the schedule applies to.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] weekdays: Weekday names for a custom schedule (e.g. monday, tuesday).
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "schedule_type", schedule_type)
        if all_day is not None:
            pulumi.set(__self__, "all_day", all_day)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if end_day is not None:
            pulumi.set(__self__, "end_day", end_day)
        if end_hour is not None:
            pulumi.set(__self__, "end_hour", end_hour)
        if end_minute is not None:
            pulumi.set(__self__, "end_minute", end_minute)
        if endpoints is not None:
            pulumi.set(__self__, "endpoints", endpoints)
        if expires_at is not None:
            pulumi.set(__self__, "expires_at", expires_at)
        if is_active is not None:
            pulumi.set(__self__, "is_active", is_active)
        if max_access_time is not None:
            pulumi.set(__self__, "max_access_time", max_access_time)
        if operation_type is None:
            operation_type = 'autoapprove'
        if operation_type is not None:
            pulumi.set(__self__, "operation_type", operation_type)
        if specific_dates is not None:
            pulumi.set(__self__, "specific_dates", specific_dates)
        if start_day is not None:
            pulumi.set(__self__, "start_day", start_day)
        if start_hour is not None:
            pulumi.set(__self__, "start_hour", start_hour)
        if start_minute is not None:
            pulumi.set(__self__, "start_minute", start_minute)
        if teams is not None:
            pulumi.set(__self__, "teams", teams)
        if timezone is not None:
            pulumi.set(__self__, "timezone", timezone)
        if users is not None:
            pulumi.set(__self__, "users", users)
        if weekdays is not None:
            pulumi.set(__self__, "weekdays", weekdays)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        Name of the schedule. Note: the Adaptive API upserts schedules by name, so creating a schedule whose name already exists adopts the existing schedule.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="scheduleType")
    def schedule_type(self) -> pulumi.Input[_builtins.str]:
        """
        The schedule pattern: weekdays, weekends, everyday, monthly, specific, or custom.
        """
        return pulumi.get(self, "schedule_type")

    @schedule_type.setter
    def schedule_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "schedule_type", value)

    @_builtins.property
    @pulumi.getter(name="allDay")
    def all_day(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the schedule covers the whole day (start/end times are ignored).
        """
        return pulumi.get(self, "all_day")

    @all_day.setter
    def all_day(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "all_day", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        An optional description of the schedule.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="endDay")
    def end_day(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Day of month (1-31) the window closes, for monthly schedules.
        """
        return pulumi.get(self, "end_day")

    @end_day.setter
    def end_day(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "end_day", value)

    @_builtins.property
    @pulumi.getter(name="endHour")
    def end_hour(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Hour (0-23) the window closes.
        """
        return pulumi.get(self, "end_hour")

    @end_hour.setter
    def end_hour(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "end_hour", value)

    @_builtins.property
    @pulumi.getter(name="endMinute")
    def end_minute(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Minute (0-59) the window closes.
        """
        return pulumi.get(self, "end_minute")

    @end_minute.setter
    def end_minute(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "end_minute", value)

    @_builtins.property
    @pulumi.getter
    def endpoints(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Names of endpoints the schedule applies to.
        """
        return pulumi.get(self, "endpoints")

    @endpoints.setter
    def endpoints(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "endpoints", value)

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        RFC3339 timestamp after which the schedule no longer applies.
        """
        return pulumi.get(self, "expires_at")

    @expires_at.setter
    def expires_at(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "expires_at", value)

    @_builtins.property
    @pulumi.getter(name="isActive")
    def is_active(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the schedule is active.
        """
        return pulumi.get(self, "is_active")

    @is_active.setter
    def is_active(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "is_active", value)

    @_builtins.property
    @pulumi.getter(name="maxAccessTime")
    def max_access_time(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Maximum access duration in minutes granted by an auto-approval.
        """
        return pulumi.get(self, "max_access_time")

    @max_access_time.setter
    def max_access_time(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "max_access_time", value)

    @_builtins.property
    @pulumi.getter(name="operationType")
    def operation_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        What the schedule does inside its window: autoapprove or autoreject.
        """
        return pulumi.get(self, "operation_type")

    @operation_type.setter
    def operation_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "operation_type", value)

    @_builtins.property
    @pulumi.getter(name="specificDates")
    def specific_dates(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        RFC3339 dates for a specific-dates schedule.
        """
        return pulumi.get(self, "specific_dates")

    @specific_dates.setter
    def specific_dates(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "specific_dates", value)

    @_builtins.property
    @pulumi.getter(name="startDay")
    def start_day(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Day of month (1-31) the window opens, for monthly schedules.
        """
        return pulumi.get(self, "start_day")

    @start_day.setter
    def start_day(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "start_day", value)

    @_builtins.property
    @pulumi.getter(name="startHour")
    def start_hour(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Hour (0-23) the window opens.
        """
        return pulumi.get(self, "start_hour")

    @start_hour.setter
    def start_hour(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "start_hour", value)

    @_builtins.property
    @pulumi.getter(name="startMinute")
    def start_minute(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Minute (0-59) the window opens.
        """
        return pulumi.get(self, "start_minute")

    @start_minute.setter
    def start_minute(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "start_minute", value)

    @_builtins.property
    @pulumi.getter
    def teams(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Names of groups the schedule applies to.
        """
        return pulumi.get(self, "teams")

    @teams.setter
    def teams(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "teams", value)

    @_builtins.property
    @pulumi.getter
    def timezone(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        IANA timezone for the schedule window. Empty inherits the workspace default.
        """
        return pulumi.get(self, "timezone")

    @timezone.setter
    def timezone(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "timezone", value)

    @_builtins.property
    @pulumi.getter
    def users(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Emails of users the schedule applies to.
        """
        return pulumi.get(self, "users")

    @users.setter
    def users(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "users", value)

    @_builtins.property
    @pulumi.getter
    def weekdays(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Weekday names for a custom schedule (e.g. monday, tuesday).
        """
        return pulumi.get(self, "weekdays")

    @weekdays.setter
    def weekdays(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "weekdays", value)


@pulumi.type_token("adaptive:index:Schedule")
class Schedule(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 all_day: Optional[pulumi.Input[_builtins.bool]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 end_day: Optional[pulumi.Input[_builtins.int]] = None,
                 end_hour: Optional[pulumi.Input[_builtins.int]] = None,
                 end_minute: Optional[pulumi.Input[_builtins.int]] = None,
                 endpoints: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 expires_at: Optional[pulumi.Input[_builtins.str]] = None,
                 is_active: Optional[pulumi.Input[_builtins.bool]] = None,
                 max_access_time: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 operation_type: Optional[pulumi.Input[_builtins.str]] = None,
                 schedule_type: Optional[pulumi.Input[_builtins.str]] = None,
                 specific_dates: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 start_day: Optional[pulumi.Input[_builtins.int]] = None,
                 start_hour: Optional[pulumi.Input[_builtins.int]] = None,
                 start_minute: Optional[pulumi.Input[_builtins.int]] = None,
                 teams: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timezone: Optional[pulumi.Input[_builtins.str]] = None,
                 users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 weekdays: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Create a Schedule resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] all_day: Whether the schedule covers the whole day (start/end times are ignored).
        :param pulumi.Input[_builtins.str] description: An optional description of the schedule.
        :param pulumi.Input[_builtins.int] end_day: Day of month (1-31) the window closes, for monthly schedules.
        :param pulumi.Input[_builtins.int] end_hour: Hour (0-23) the window closes.
        :param pulumi.Input[_builtins.int] end_minute: Minute (0-59) the window closes.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] endpoints: Names of endpoints the schedule applies to.
        :param pulumi.Input[_builtins.str] expires_at: RFC3339 timestamp after which the schedule no longer applies.
        :param pulumi.Input[_builtins.bool] is_active: Whether the schedule is active.
        :param pulumi.Input[_builtins.int] max_access_time: Maximum access duration in minutes granted by an auto-approval.
        :param pulumi.Input[_builtins.str] name: Name of the schedule. Note: the Adaptive API upserts schedules by name, so creating a schedule whose name already exists adopts the existing schedule.
        :param pulumi.Input[_builtins.str] operation_type: What the schedule does inside its window: autoapprove or autoreject.
        :param pulumi.Input[_builtins.str] schedule_type: The schedule pattern: weekdays, weekends, everyday, monthly, specific, or custom.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] specific_dates: RFC3339 dates for a specific-dates schedule.
        :param pulumi.Input[_builtins.int] start_day: Day of month (1-31) the window opens, for monthly schedules.
        :param pulumi.Input[_builtins.int] start_hour: Hour (0-23) the window opens.
        :param pulumi.Input[_builtins.int] start_minute: Minute (0-59) the window opens.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] teams: Names of groups the schedule applies to.
        :param pulumi.Input[_builtins.str] timezone: IANA timezone for the schedule window. Empty inherits the workspace default.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] users: Emails of users the schedule applies to.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] weekdays: Weekday names for a custom schedule (e.g. monday, tuesday).
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ScheduleArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Schedule resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ScheduleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ScheduleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 all_day: Optional[pulumi.Input[_builtins.bool]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 end_day: Optional[pulumi.Input[_builtins.int]] = None,
                 end_hour: Optional[pulumi.Input[_builtins.int]] = None,
                 end_minute: Optional[pulumi.Input[_builtins.int]] = None,
                 endpoints: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 expires_at: Optional[pulumi.Input[_builtins.str]] = None,
                 is_active: Optional[pulumi.Input[_builtins.bool]] = None,
                 max_access_time: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 operation_type: Optional[pulumi.Input[_builtins.str]] = None,
                 schedule_type: Optional[pulumi.Input[_builtins.str]] = None,
                 specific_dates: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 start_day: Optional[pulumi.Input[_builtins.int]] = None,
                 start_hour: Optional[pulumi.Input[_builtins.int]] = None,
                 start_minute: Optional[pulumi.Input[_builtins.int]] = None,
                 teams: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timezone: Optional[pulumi.Input[_builtins.str]] = None,
                 users: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 weekdays: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ScheduleArgs.__new__(ScheduleArgs)

            __props__.__dict__["all_day"] = all_day
            __props__.__dict__["description"] = description
            __props__.__dict__["end_day"] = end_day
            __props__.__dict__["end_hour"] = end_hour
            __props__.__dict__["end_minute"] = end_minute
            __props__.__dict__["endpoints"] = endpoints
            __props__.__dict__["expires_at"] = expires_at
            __props__.__dict__["is_active"] = is_active
            __props__.__dict__["max_access_time"] = max_access_time
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            if operation_type is None:
                operation_type = 'autoapprove'
            __props__.__dict__["operation_type"] = operation_type
            if schedule_type is None and not opts.urn:
                raise TypeError("Missing required property 'schedule_type'")
            __props__.__dict__["schedule_type"] = schedule_type
            __props__.__dict__["specific_dates"] = specific_dates
            __props__.__dict__["start_day"] = start_day
            __props__.__dict__["start_hour"] = start_hour
            __props__.__dict__["start_minute"] = start_minute
            __props__.__dict__["teams"] = teams
            __props__.__dict__["timezone"] = timezone
            __props__.__dict__["users"] = users
            __props__.__dict__["weekdays"] = weekdays
            __props__.__dict__["updated_at"] = None
        super(Schedule, __self__).__init__(
            'adaptive:index:Schedule',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Schedule':
        """
        Get an existing Schedule resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ScheduleArgs.__new__(ScheduleArgs)

        __props__.__dict__["all_day"] = None
        __props__.__dict__["description"] = None
        __props__.__dict__["end_day"] = None
        __props__.__dict__["end_hour"] = None
        __props__.__dict__["end_minute"] = None
        __props__.__dict__["endpoints"] = None
        __props__.__dict__["expires_at"] = None
        __props__.__dict__["is_active"] = None
        __props__.__dict__["max_access_time"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["operation_type"] = None
        __props__.__dict__["schedule_type"] = None
        __props__.__dict__["specific_dates"] = None
        __props__.__dict__["start_day"] = None
        __props__.__dict__["start_hour"] = None
        __props__.__dict__["start_minute"] = None
        __props__.__dict__["teams"] = None
        __props__.__dict__["timezone"] = None
        __props__.__dict__["updated_at"] = None
        __props__.__dict__["users"] = None
        __props__.__dict__["weekdays"] = None
        return Schedule(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="allDay")
    def all_day(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the schedule covers the whole day (start/end times are ignored).
        """
        return pulumi.get(self, "all_day")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        An optional description of the schedule.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="endDay")
    def end_day(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Day of month (1-31) the window closes, for monthly schedules.
        """
        return pulumi.get(self, "end_day")

    @_builtins.property
    @pulumi.getter(name="endHour")
    def end_hour(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Hour (0-23) the window closes.
        """
        return pulumi.get(self, "end_hour")

    @_builtins.property
    @pulumi.getter(name="endMinute")
    def end_minute(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Minute (0-59) the window closes.
        """
        return pulumi.get(self, "end_minute")

    @_builtins.property
    @pulumi.getter
    def endpoints(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Names of endpoints the schedule applies to.
        """
        return pulumi.get(self, "endpoints")

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        RFC3339 timestamp after which the schedule no longer applies.
        """
        return pulumi.get(self, "expires_at")

    @_builtins.property
    @pulumi.getter(name="isActive")
    def is_active(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the schedule is active.
        """
        return pulumi.get(self, "is_active")

    @_builtins.property
    @pulumi.getter(name="maxAccessTime")
    def max_access_time(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Maximum access duration in minutes granted by an auto-approval.
        """
        return pulumi.get(self, "max_access_time")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the schedule. Note: the Adaptive API upserts schedules by name, so creating a schedule whose name already exists adopts the existing schedule.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="operationType")
    def operation_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        What the schedule does inside its window: autoapprove or autoreject.
        """
        return pulumi.get(self, "operation_type")

    @_builtins.property
    @pulumi.getter(name="scheduleType")
    def schedule_type(self) -> pulumi.Output[_builtins.str]:
        """
        The schedule pattern: weekdays, weekends, everyday, monthly, specific, or custom.
        """
        return pulumi.get(self, "schedule_type")

    @_builtins.property
    @pulumi.getter(name="specificDates")
    def specific_dates(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        RFC3339 dates for a specific-dates schedule.
        """
        return pulumi.get(self, "specific_dates")

    @_builtins.property
    @pulumi.getter(name="startDay")
    def start_day(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Day of month (1-31) the window opens, for monthly schedules.
        """
        return pulumi.get(self, "start_day")

    @_builtins.property
    @pulumi.getter(name="startHour")
    def start_hour(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Hour (0-23) the window opens.
        """
        return pulumi.get(self, "start_hour")

    @_builtins.property
    @pulumi.getter(name="startMinute")
    def start_minute(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Minute (0-59) the window opens.
        """
        return pulumi.get(self, "start_minute")

    @_builtins.property
    @pulumi.getter
    def teams(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Names of groups the schedule applies to.
        """
        return pulumi.get(self, "teams")

    @_builtins.property
    @pulumi.getter
    def timezone(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        IANA timezone for the schedule window. Empty inherits the workspace default.
        """
        return pulumi.get(self, "timezone")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Last time the schedule was modified.
        """
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter
    def users(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Emails of users the schedule applies to.
        """
        return pulumi.get(self, "users")

    @_builtins.property
    @pulumi.getter
    def weekdays(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Weekday names for a custom schedule (e.g. monday, tuesday).
        """
        return pulumi.get(self, "weekdays")

