// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace AdaptiveScale.Adaptive.Inputs
{

    public sealed class DataProtectionColumnMaskArgs : global::Pulumi.ResourceArgs
    {
        [Input("columnName", required: true)]
        public Input<string> ColumnName { get; set; } = null!;

        [Input("maskingType", required: true)]
        public Input<string> MaskingType { get; set; } = null!;

        public DataProtectionColumnMaskArgs()
        {
        }
        public static new DataProtectionColumnMaskArgs Empty => new DataProtectionColumnMaskArgs();
    }
}
