// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace AdaptiveScale.Adaptive.Inputs
{

    public sealed class DataProtectionTableArgs : global::Pulumi.ResourceArgs
    {
        [Input("masked")]
        public Input<bool>? Masked { get; set; }

        [Input("maskedColumns")]
        private InputList<Inputs.DataProtectionColumnMaskArgs>? _maskedColumns;
        public InputList<Inputs.DataProtectionColumnMaskArgs> MaskedColumns
        {
            get => _maskedColumns ?? (_maskedColumns = new InputList<Inputs.DataProtectionColumnMaskArgs>());
            set => _maskedColumns = value;
        }

        [Input("schema")]
        public Input<string>? Schema { get; set; }

        [Input("tableName", required: true)]
        public Input<string> TableName { get; set; } = null!;

        public DataProtectionTableArgs()
        {
        }
        public static new DataProtectionTableArgs Empty => new DataProtectionTableArgs();
    }
}
