// *** WARNING: this file was generated by pulumi-adaptive-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class DataProtection extends pulumi.CustomResource {
    /**
     * Get an existing DataProtection resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): DataProtection {
        return new DataProtection(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'adaptive:index:DataProtection';

    /**
     * Returns true if the given object is an instance of DataProtection.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DataProtection {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DataProtection.__pulumiType;
    }

    /**
     * Name of the generated masking authorization (masked_<resource>). Attach it to an Endpoint's `authorization` to serve masked sessions.
     */
    declare public /*out*/ readonly authorizationName: pulumi.Output<string | undefined>;
    /**
     * Last time the policy was applied to the target database.
     */
    declare public /*out*/ readonly lastAppliedAt: pulumi.Output<string | undefined>;
    /**
     * Masking rules, grouped per database and table.
     */
    declare public readonly masks: pulumi.Output<outputs.DataProtectionMask[] | undefined>;
    /**
     * Name of the resource (integration) this masking policy protects. Cannot be changed after creation. Note: creating a policy for a resource that already has one (e.g. configured in the UI) adopts and overwrites it.
     */
    declare public readonly resource: pulumi.Output<string>;
    /**
     * When true (the default), session users only see the generated masked views. When false, users see everything except the raw masked tables (requires synced metadata).
     */
    declare public readonly scoped: pulumi.Output<boolean | undefined>;
    /**
     * Provisioning status of the policy. Masked views are created lazily at session start.
     */
    declare public /*out*/ readonly status: pulumi.Output<string | undefined>;

    /**
     * Create a DataProtection resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DataProtectionArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.resource === undefined && !opts.urn) {
                throw new Error("Missing required property 'resource'");
            }
            resourceInputs["masks"] = args?.masks;
            resourceInputs["resource"] = args?.resource;
            resourceInputs["scoped"] = args?.scoped;
            resourceInputs["authorizationName"] = undefined /*out*/;
            resourceInputs["lastAppliedAt"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        } else {
            resourceInputs["authorizationName"] = undefined /*out*/;
            resourceInputs["lastAppliedAt"] = undefined /*out*/;
            resourceInputs["masks"] = undefined /*out*/;
            resourceInputs["resource"] = undefined /*out*/;
            resourceInputs["scoped"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DataProtection.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a DataProtection resource.
 */
export interface DataProtectionArgs {
    /**
     * Masking rules, grouped per database and table.
     */
    masks?: pulumi.Input<pulumi.Input<inputs.DataProtectionMaskArgs>[]>;
    /**
     * Name of the resource (integration) this masking policy protects. Cannot be changed after creation. Note: creating a policy for a resource that already has one (e.g. configured in the UI) adopts and overwrites it.
     */
    resource: pulumi.Input<string>;
    /**
     * When true (the default), session users only see the generated masked views. When false, users see everything except the raw masked tables (requires synced metadata).
     */
    scoped?: pulumi.Input<boolean>;
}
