// *** WARNING: this file was generated by pulumi-adaptive-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Endpoint extends pulumi.CustomResource {
    /**
     * Get an existing Endpoint resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Endpoint {
        return new Endpoint(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'adaptive:index:Endpoint';

    /**
     * Returns true if the given object is an instance of Endpoint.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Endpoint {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Endpoint.__pulumiType;
    }

    /**
     * The authorization (by name) to apply to this endpoint.
     */
    declare public readonly authorization: pulumi.Output<string | undefined>;
    declare public readonly cluster: pulumi.Output<string | undefined>;
    declare public readonly cpu: pulumi.Output<string | undefined>;
    /**
     * Whether to stop retaining terminal output for sessions on this endpoint. Commands are still audited; the recorded output is purged and session replay shows a notice instead. The workspace-level setting is OR'd with this, so leaving it false does not re-enable capture for a workspace that has turned it off.
     */
    declare public readonly disableOutputCapture: pulumi.Output<boolean | undefined>;
    declare public readonly groups: pulumi.Output<string[] | undefined>;
    declare public readonly idleTimeout: pulumi.Output<string | undefined>;
    /**
     * Whether Just-In-Time access approval is enabled.
     */
    declare public readonly isJitEnabled: pulumi.Output<boolean | undefined>;
    /**
     * Emails of users who can approve Just-In-Time access requests.
     */
    declare public readonly jitApprovers: pulumi.Output<string[] | undefined>;
    declare public readonly memory: pulumi.Output<string | undefined>;
    /**
     * The name of the endpoint to create.
     */
    declare public readonly name: pulumi.Output<string>;
    declare public readonly pauseTimeout: pulumi.Output<string | undefined>;
    /**
     * The resource (by name) this endpoint grants access to.
     */
    declare public readonly resource: pulumi.Output<string>;
    /**
     * Whether the endpoint is only accessible via script.
     */
    declare public readonly scriptOnlyAccess: pulumi.Output<boolean | undefined>;
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    /**
     * Time-to-live for the endpoint, e.g. 8h, 7d, 90d.
     */
    declare public readonly ttl: pulumi.Output<string | undefined>;
    /**
     * The type of session: direct, client, cli, or services.
     */
    declare public readonly type: pulumi.Output<string | undefined>;
    declare public readonly users: pulumi.Output<string[] | undefined>;

    /**
     * Create a Endpoint resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EndpointArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.resource === undefined && !opts.urn) {
                throw new Error("Missing required property 'resource'");
            }
            resourceInputs["authorization"] = args?.authorization;
            resourceInputs["cluster"] = args?.cluster;
            resourceInputs["cpu"] = args?.cpu;
            resourceInputs["disableOutputCapture"] = args?.disableOutputCapture;
            resourceInputs["groups"] = args?.groups;
            resourceInputs["idleTimeout"] = args?.idleTimeout;
            resourceInputs["isJitEnabled"] = args?.isJitEnabled;
            resourceInputs["jitApprovers"] = args?.jitApprovers;
            resourceInputs["memory"] = args?.memory;
            resourceInputs["name"] = args?.name;
            resourceInputs["pauseTimeout"] = args?.pauseTimeout;
            resourceInputs["resource"] = args?.resource;
            resourceInputs["scriptOnlyAccess"] = args?.scriptOnlyAccess;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["ttl"] = args?.ttl;
            resourceInputs["type"] = (args?.type) ?? "direct";
            resourceInputs["users"] = args?.users;
        } else {
            resourceInputs["authorization"] = undefined /*out*/;
            resourceInputs["cluster"] = undefined /*out*/;
            resourceInputs["cpu"] = undefined /*out*/;
            resourceInputs["disableOutputCapture"] = undefined /*out*/;
            resourceInputs["groups"] = undefined /*out*/;
            resourceInputs["idleTimeout"] = undefined /*out*/;
            resourceInputs["isJitEnabled"] = undefined /*out*/;
            resourceInputs["jitApprovers"] = undefined /*out*/;
            resourceInputs["memory"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["pauseTimeout"] = undefined /*out*/;
            resourceInputs["resource"] = undefined /*out*/;
            resourceInputs["scriptOnlyAccess"] = undefined /*out*/;
            resourceInputs["tags"] = undefined /*out*/;
            resourceInputs["ttl"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["users"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Endpoint.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Endpoint resource.
 */
export interface EndpointArgs {
    /**
     * The authorization (by name) to apply to this endpoint.
     */
    authorization?: pulumi.Input<string>;
    cluster?: pulumi.Input<string>;
    cpu?: pulumi.Input<string>;
    /**
     * Whether to stop retaining terminal output for sessions on this endpoint. Commands are still audited; the recorded output is purged and session replay shows a notice instead. The workspace-level setting is OR'd with this, so leaving it false does not re-enable capture for a workspace that has turned it off.
     */
    disableOutputCapture?: pulumi.Input<boolean>;
    groups?: pulumi.Input<pulumi.Input<string>[]>;
    idleTimeout?: pulumi.Input<string>;
    /**
     * Whether Just-In-Time access approval is enabled.
     */
    isJitEnabled?: pulumi.Input<boolean>;
    /**
     * Emails of users who can approve Just-In-Time access requests.
     */
    jitApprovers?: pulumi.Input<pulumi.Input<string>[]>;
    memory?: pulumi.Input<string>;
    /**
     * The name of the endpoint to create.
     */
    name: pulumi.Input<string>;
    pauseTimeout?: pulumi.Input<string>;
    /**
     * The resource (by name) this endpoint grants access to.
     */
    resource: pulumi.Input<string>;
    /**
     * Whether the endpoint is only accessible via script.
     */
    scriptOnlyAccess?: pulumi.Input<boolean>;
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Time-to-live for the endpoint, e.g. 8h, 7d, 90d.
     */
    ttl?: pulumi.Input<string>;
    /**
     * The type of session: direct, client, cli, or services.
     */
    type?: pulumi.Input<string>;
    users?: pulumi.Input<pulumi.Input<string>[]>;
}
