// *** WARNING: this file was generated by pulumi-adaptive-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Group extends pulumi.CustomResource {
    /**
     * Get an existing Group resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Group {
        return new Group(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'adaptive:index:Group';

    /**
     * Returns true if the given object is an instance of Group.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Group {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Group.__pulumiType;
    }

    /**
     * Names of endpoints to add to this group.
     */
    declare public readonly endpoints: pulumi.Output<string[] | undefined>;
    /**
     * Emails of users to add to the group.
     */
    declare public readonly members: pulumi.Output<string[] | undefined>;
    /**
     * Name of the group. Must be unique.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Slack channel ID associated with this group.
     */
    declare public readonly slackChannelId: pulumi.Output<string | undefined>;

    /**
     * Create a Group resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GroupArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["endpoints"] = args?.endpoints;
            resourceInputs["members"] = args?.members;
            resourceInputs["name"] = args?.name;
            resourceInputs["slackChannelId"] = args?.slackChannelId;
        } else {
            resourceInputs["endpoints"] = undefined /*out*/;
            resourceInputs["members"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["slackChannelId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Group.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Group resource.
 */
export interface GroupArgs {
    /**
     * Names of endpoints to add to this group.
     */
    endpoints?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Emails of users to add to the group.
     */
    members?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Name of the group. Must be unique.
     */
    name: pulumi.Input<string>;
    /**
     * Slack channel ID associated with this group.
     */
    slackChannelId?: pulumi.Input<string>;
}
