// *** WARNING: this file was generated by pulumi-adaptive-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AuthorizationArgs } from "./authorization";
export type Authorization = import("./authorization").Authorization;
export const Authorization: typeof import("./authorization").Authorization = null as any;
utilities.lazyLoad(exports, ["Authorization"], () => require("./authorization"));

export { EndpointArgs } from "./endpoint";
export type Endpoint = import("./endpoint").Endpoint;
export const Endpoint: typeof import("./endpoint").Endpoint = null as any;
utilities.lazyLoad(exports, ["Endpoint"], () => require("./endpoint"));

export { GroupArgs } from "./group";
export type Group = import("./group").Group;
export const Group: typeof import("./group").Group = null as any;
utilities.lazyLoad(exports, ["Group"], () => require("./group"));

export { MSTeamsWorkflowArgs } from "./msteamsWorkflow";
export type MSTeamsWorkflow = import("./msteamsWorkflow").MSTeamsWorkflow;
export const MSTeamsWorkflow: typeof import("./msteamsWorkflow").MSTeamsWorkflow = null as any;
utilities.lazyLoad(exports, ["MSTeamsWorkflow"], () => require("./msteamsWorkflow"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { ResourceArgs } from "./resource";
export type Resource = import("./resource").Resource;
export const Resource: typeof import("./resource").Resource = null as any;
utilities.lazyLoad(exports, ["Resource"], () => require("./resource"));

export { ScriptArgs } from "./script";
export type Script = import("./script").Script;
export const Script: typeof import("./script").Script = null as any;
utilities.lazyLoad(exports, ["Script"], () => require("./script"));


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "adaptive:index:Authorization":
                return new Authorization(name, <any>undefined, { urn })
            case "adaptive:index:Endpoint":
                return new Endpoint(name, <any>undefined, { urn })
            case "adaptive:index:Group":
                return new Group(name, <any>undefined, { urn })
            case "adaptive:index:MSTeamsWorkflow":
                return new MSTeamsWorkflow(name, <any>undefined, { urn })
            case "adaptive:index:Resource":
                return new Resource(name, <any>undefined, { urn })
            case "adaptive:index:Script":
                return new Script(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("adaptive", "index", _module)
pulumi.runtime.registerResourcePackage("adaptive", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:adaptive") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
