// *** WARNING: this file was generated by pulumi-adaptive-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Resource extends pulumi.CustomResource {
    /**
     * Get an existing Resource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Resource {
        return new Resource(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'adaptive:index:Resource';

    /**
     * Returns true if the given object is an instance of Resource.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Resource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Resource.__pulumiType;
    }

    declare public readonly accessControlGroup: pulumi.Output<string | undefined>;
    declare public readonly accessControlMethod: pulumi.Output<string | undefined>;
    declare public readonly accessKeyId: pulumi.Output<string | undefined>;
    declare public readonly annotations: pulumi.Output<string | undefined>;
    declare public readonly apiClientId: pulumi.Output<string | undefined>;
    declare public readonly apiClientSecret: pulumi.Output<string | undefined>;
    declare public readonly apiKey: pulumi.Output<string | undefined>;
    declare public readonly apiSecret: pulumi.Output<string | undefined>;
    declare public readonly apiServer: pulumi.Output<string | undefined>;
    declare public readonly apiToken: pulumi.Output<string | undefined>;
    declare public readonly appId: pulumi.Output<string | undefined>;
    declare public readonly appKey: pulumi.Output<string | undefined>;
    declare public readonly applicationId: pulumi.Output<string | undefined>;
    declare public readonly applicationName: pulumi.Output<string | undefined>;
    /**
     * Opaque server fingerprints of the write-only secret fields as of the last write by this provider, used to detect out-of-band secret changes on refresh. Not comparable across resources or workspaces.
     */
    declare public /*out*/ readonly appliedDigests: pulumi.Output<{[key: string]: string} | undefined>;
    declare public readonly arn: pulumi.Output<string | undefined>;
    declare public readonly automationMode: pulumi.Output<string | undefined>;
    declare public readonly awsArn: pulumi.Output<string | undefined>;
    declare public readonly awsRegionName: pulumi.Output<string | undefined>;
    declare public readonly clientCert: pulumi.Output<string | undefined>;
    declare public readonly clientCertificate: pulumi.Output<string | undefined>;
    declare public readonly clientConfiguration: pulumi.Output<string | undefined>;
    declare public readonly clientId: pulumi.Output<string | undefined>;
    declare public readonly clientKey: pulumi.Output<string | undefined>;
    declare public readonly clientSecret: pulumi.Output<string | undefined>;
    declare public readonly clientcert: pulumi.Output<string | undefined>;
    declare public readonly clusterCert: pulumi.Output<string | undefined>;
    declare public readonly clusterToken: pulumi.Output<string | undefined>;
    declare public readonly connectServerUrl: pulumi.Output<string | undefined>;
    declare public readonly cpu: pulumi.Output<string | undefined>;
    declare public readonly createIfNotExists: pulumi.Output<boolean | undefined>;
    declare public readonly credentialJson: pulumi.Output<string | undefined>;
    declare public readonly databaseAccount: pulumi.Output<string | undefined>;
    declare public readonly databaseName: pulumi.Output<string | undefined>;
    declare public readonly databasePassword: pulumi.Output<string | undefined>;
    declare public readonly databaseUsername: pulumi.Output<string | undefined>;
    declare public readonly ddApiKey: pulumi.Output<string | undefined>;
    declare public readonly ddSite: pulumi.Output<string | undefined>;
    /**
     * The default cluster the resource is deployed to.
     */
    declare public readonly defaultCluster: pulumi.Output<string | undefined>;
    declare public readonly defaultUser: pulumi.Output<string | undefined>;
    declare public readonly domain: pulumi.Output<string | undefined>;
    declare public readonly fields: pulumi.Output<string | undefined>;
    declare public readonly host: pulumi.Output<string | undefined>;
    declare public readonly hostname: pulumi.Output<string | undefined>;
    declare public readonly hosts: pulumi.Output<string[] | undefined>;
    declare public readonly image: pulumi.Output<string | undefined>;
    declare public readonly index: pulumi.Output<string | undefined>;
    declare public readonly isRedisLabs: pulumi.Output<boolean | undefined>;
    declare public readonly key: pulumi.Output<string | undefined>;
    declare public readonly keyFile: pulumi.Output<string | undefined>;
    declare public readonly ldapEncryptionMethod: pulumi.Output<string | undefined>;
    declare public readonly ldapHostname: pulumi.Output<string | undefined>;
    declare public readonly ldapPort: pulumi.Output<string | undefined>;
    declare public readonly ldapSearchBindDn: pulumi.Output<string | undefined>;
    declare public readonly ldapSearchBindPassword: pulumi.Output<string | undefined>;
    declare public readonly ldapUserBaseDn: pulumi.Output<string | undefined>;
    declare public readonly ldapUserNameAttribute: pulumi.Output<string | undefined>;
    declare public readonly logGroupName: pulumi.Output<string | undefined>;
    declare public readonly logStreamName: pulumi.Output<string | undefined>;
    declare public readonly loginUrl: pulumi.Output<string | undefined>;
    declare public readonly machine: pulumi.Output<string | undefined>;
    declare public readonly memory: pulumi.Output<string | undefined>;
    /**
     * Name of the Adaptive resource.
     */
    declare public readonly name: pulumi.Output<string>;
    declare public readonly namespace: pulumi.Output<string | undefined>;
    declare public readonly networkId: pulumi.Output<string | undefined>;
    declare public readonly nodeAffinity: pulumi.Output<string | undefined>;
    declare public readonly nodeSelector: pulumi.Output<string | undefined>;
    declare public readonly oldVersion: pulumi.Output<boolean | undefined>;
    declare public readonly organizationId: pulumi.Output<string | undefined>;
    declare public readonly password: pulumi.Output<string | undefined>;
    declare public readonly port: pulumi.Output<string | undefined>;
    declare public readonly prestart: pulumi.Output<string | undefined>;
    declare public readonly privateKey: pulumi.Output<string | undefined>;
    declare public readonly projectId: pulumi.Output<string | undefined>;
    declare public readonly protocol: pulumi.Output<string | undefined>;
    declare public readonly proxysqlAdminPassword: pulumi.Output<string | undefined>;
    declare public readonly proxysqlAdminPort: pulumi.Output<string | undefined>;
    declare public readonly proxysqlAdminUsername: pulumi.Output<string | undefined>;
    declare public readonly proxysqlHostgroupId: pulumi.Output<string | undefined>;
    declare public readonly publicKey: pulumi.Output<string | undefined>;
    declare public readonly region: pulumi.Output<string | undefined>;
    declare public readonly regionName: pulumi.Output<string | undefined>;
    declare public readonly resource: pulumi.Output<string | undefined>;
    declare public readonly role: pulumi.Output<string | undefined>;
    declare public readonly rootCert: pulumi.Output<string | undefined>;
    declare public readonly schema: pulumi.Output<string | undefined>;
    declare public readonly script: pulumi.Output<string | undefined>;
    declare public readonly secretAccessKey: pulumi.Output<string | undefined>;
    declare public readonly secretId: pulumi.Output<string | undefined>;
    declare public readonly serviceAccount: pulumi.Output<string | undefined>;
    declare public readonly serviceAccountName: pulumi.Output<string | undefined>;
    declare public readonly serviceName: pulumi.Output<string | undefined>;
    declare public readonly sharedSecret: pulumi.Output<string | undefined>;
    declare public readonly sslMode: pulumi.Output<string | undefined>;
    declare public readonly storage: pulumi.Output<string | undefined>;
    declare public readonly subSystemName: pulumi.Output<string | undefined>;
    /**
     * Optional tags.
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    declare public readonly targets: pulumi.Output<string | undefined>;
    declare public readonly tenantId: pulumi.Output<string | undefined>;
    declare public readonly tlsCaCert: pulumi.Output<string | undefined>;
    declare public readonly tlsCertFile: pulumi.Output<string | undefined>;
    declare public readonly tlsEnabled: pulumi.Output<boolean | undefined>;
    declare public readonly tlsKeyFile: pulumi.Output<string | undefined>;
    declare public readonly tlsRootCert: pulumi.Output<string | undefined>;
    declare public readonly tlsSkipVerify: pulumi.Output<boolean | undefined>;
    declare public readonly token: pulumi.Output<string | undefined>;
    declare public readonly tokenId: pulumi.Output<string | undefined>;
    declare public readonly tolerations: pulumi.Output<string | undefined>;
    /**
     * Type of the Adaptive resource (integration), e.g. postgres, mysql, mongodb, ssh, kubernetes, aws, gcp, azure, snowflake.
     */
    declare public readonly type: pulumi.Output<string>;
    declare public readonly uri: pulumi.Output<string | undefined>;
    declare public readonly url: pulumi.Output<string | undefined>;
    declare public readonly urls: pulumi.Output<string | undefined>;
    declare public readonly useConnectServer: pulumi.Output<boolean | undefined>;
    declare public readonly useProxy: pulumi.Output<boolean | undefined>;
    declare public readonly useServiceAccount: pulumi.Output<boolean | undefined>;
    declare public readonly useTenant: pulumi.Output<boolean | undefined>;
    declare public readonly useTls: pulumi.Output<boolean | undefined>;
    declare public readonly username: pulumi.Output<string | undefined>;
    declare public readonly value: pulumi.Output<string | undefined>;
    declare public readonly version: pulumi.Output<string | undefined>;
    declare public readonly warehouse: pulumi.Output<string | undefined>;
    declare public readonly webhookUrl: pulumi.Output<string | undefined>;
    declare public readonly webuiPort: pulumi.Output<string | undefined>;

    /**
     * Create a Resource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ResourceArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["accessControlGroup"] = args?.accessControlGroup;
            resourceInputs["accessControlMethod"] = args?.accessControlMethod;
            resourceInputs["accessKeyId"] = args?.accessKeyId;
            resourceInputs["annotations"] = args?.annotations;
            resourceInputs["apiClientId"] = args?.apiClientId;
            resourceInputs["apiClientSecret"] = args?.apiClientSecret ? pulumi.secret(args.apiClientSecret) : undefined;
            resourceInputs["apiKey"] = args?.apiKey ? pulumi.secret(args.apiKey) : undefined;
            resourceInputs["apiSecret"] = args?.apiSecret ? pulumi.secret(args.apiSecret) : undefined;
            resourceInputs["apiServer"] = args?.apiServer;
            resourceInputs["apiToken"] = args?.apiToken ? pulumi.secret(args.apiToken) : undefined;
            resourceInputs["appId"] = args?.appId;
            resourceInputs["appKey"] = args?.appKey ? pulumi.secret(args.appKey) : undefined;
            resourceInputs["applicationId"] = args?.applicationId;
            resourceInputs["applicationName"] = args?.applicationName;
            resourceInputs["arn"] = args?.arn;
            resourceInputs["automationMode"] = args?.automationMode;
            resourceInputs["awsArn"] = args?.awsArn;
            resourceInputs["awsRegionName"] = args?.awsRegionName;
            resourceInputs["clientCert"] = args?.clientCert ? pulumi.secret(args.clientCert) : undefined;
            resourceInputs["clientCertificate"] = args?.clientCertificate ? pulumi.secret(args.clientCertificate) : undefined;
            resourceInputs["clientConfiguration"] = args?.clientConfiguration ? pulumi.secret(args.clientConfiguration) : undefined;
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["clientKey"] = args?.clientKey ? pulumi.secret(args.clientKey) : undefined;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["clientcert"] = args?.clientcert ? pulumi.secret(args.clientcert) : undefined;
            resourceInputs["clusterCert"] = args?.clusterCert;
            resourceInputs["clusterToken"] = args?.clusterToken ? pulumi.secret(args.clusterToken) : undefined;
            resourceInputs["connectServerUrl"] = args?.connectServerUrl;
            resourceInputs["cpu"] = args?.cpu;
            resourceInputs["createIfNotExists"] = args?.createIfNotExists;
            resourceInputs["credentialJson"] = args?.credentialJson ? pulumi.secret(args.credentialJson) : undefined;
            resourceInputs["databaseAccount"] = args?.databaseAccount;
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["databasePassword"] = args?.databasePassword ? pulumi.secret(args.databasePassword) : undefined;
            resourceInputs["databaseUsername"] = args?.databaseUsername;
            resourceInputs["ddApiKey"] = args?.ddApiKey ? pulumi.secret(args.ddApiKey) : undefined;
            resourceInputs["ddSite"] = args?.ddSite;
            resourceInputs["defaultCluster"] = args?.defaultCluster;
            resourceInputs["defaultUser"] = args?.defaultUser;
            resourceInputs["domain"] = args?.domain;
            resourceInputs["fields"] = args?.fields;
            resourceInputs["host"] = args?.host;
            resourceInputs["hostname"] = args?.hostname;
            resourceInputs["hosts"] = args?.hosts;
            resourceInputs["image"] = args?.image;
            resourceInputs["index"] = args?.index;
            resourceInputs["isRedisLabs"] = args?.isRedisLabs;
            resourceInputs["key"] = args?.key ? pulumi.secret(args.key) : undefined;
            resourceInputs["keyFile"] = args?.keyFile ? pulumi.secret(args.keyFile) : undefined;
            resourceInputs["ldapEncryptionMethod"] = args?.ldapEncryptionMethod;
            resourceInputs["ldapHostname"] = args?.ldapHostname;
            resourceInputs["ldapPort"] = args?.ldapPort;
            resourceInputs["ldapSearchBindDn"] = args?.ldapSearchBindDn;
            resourceInputs["ldapSearchBindPassword"] = args?.ldapSearchBindPassword ? pulumi.secret(args.ldapSearchBindPassword) : undefined;
            resourceInputs["ldapUserBaseDn"] = args?.ldapUserBaseDn;
            resourceInputs["ldapUserNameAttribute"] = args?.ldapUserNameAttribute;
            resourceInputs["logGroupName"] = args?.logGroupName;
            resourceInputs["logStreamName"] = args?.logStreamName;
            resourceInputs["loginUrl"] = args?.loginUrl;
            resourceInputs["machine"] = args?.machine;
            resourceInputs["memory"] = args?.memory;
            resourceInputs["name"] = args?.name;
            resourceInputs["namespace"] = args?.namespace;
            resourceInputs["networkId"] = args?.networkId;
            resourceInputs["nodeAffinity"] = args?.nodeAffinity;
            resourceInputs["nodeSelector"] = args?.nodeSelector;
            resourceInputs["oldVersion"] = args?.oldVersion;
            resourceInputs["organizationId"] = args?.organizationId;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["port"] = args?.port;
            resourceInputs["prestart"] = args?.prestart;
            resourceInputs["privateKey"] = args?.privateKey ? pulumi.secret(args.privateKey) : undefined;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["protocol"] = args?.protocol;
            resourceInputs["proxysqlAdminPassword"] = args?.proxysqlAdminPassword ? pulumi.secret(args.proxysqlAdminPassword) : undefined;
            resourceInputs["proxysqlAdminPort"] = args?.proxysqlAdminPort;
            resourceInputs["proxysqlAdminUsername"] = args?.proxysqlAdminUsername;
            resourceInputs["proxysqlHostgroupId"] = args?.proxysqlHostgroupId;
            resourceInputs["publicKey"] = args?.publicKey;
            resourceInputs["region"] = args?.region;
            resourceInputs["regionName"] = args?.regionName;
            resourceInputs["resource"] = args?.resource;
            resourceInputs["role"] = args?.role;
            resourceInputs["rootCert"] = args?.rootCert;
            resourceInputs["schema"] = args?.schema;
            resourceInputs["script"] = args?.script;
            resourceInputs["secretAccessKey"] = args?.secretAccessKey ? pulumi.secret(args.secretAccessKey) : undefined;
            resourceInputs["secretId"] = args?.secretId ? pulumi.secret(args.secretId) : undefined;
            resourceInputs["serviceAccount"] = args?.serviceAccount;
            resourceInputs["serviceAccountName"] = args?.serviceAccountName;
            resourceInputs["serviceName"] = args?.serviceName;
            resourceInputs["sharedSecret"] = args?.sharedSecret ? pulumi.secret(args.sharedSecret) : undefined;
            resourceInputs["sslMode"] = args?.sslMode;
            resourceInputs["storage"] = args?.storage;
            resourceInputs["subSystemName"] = args?.subSystemName;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["targets"] = args?.targets ? pulumi.secret(args.targets) : undefined;
            resourceInputs["tenantId"] = args?.tenantId;
            resourceInputs["tlsCaCert"] = args?.tlsCaCert;
            resourceInputs["tlsCertFile"] = args?.tlsCertFile;
            resourceInputs["tlsEnabled"] = args?.tlsEnabled;
            resourceInputs["tlsKeyFile"] = args?.tlsKeyFile ? pulumi.secret(args.tlsKeyFile) : undefined;
            resourceInputs["tlsRootCert"] = args?.tlsRootCert;
            resourceInputs["tlsSkipVerify"] = args?.tlsSkipVerify;
            resourceInputs["token"] = args?.token ? pulumi.secret(args.token) : undefined;
            resourceInputs["tokenId"] = args?.tokenId ? pulumi.secret(args.tokenId) : undefined;
            resourceInputs["tolerations"] = args?.tolerations;
            resourceInputs["type"] = args?.type;
            resourceInputs["uri"] = args?.uri ? pulumi.secret(args.uri) : undefined;
            resourceInputs["url"] = args?.url;
            resourceInputs["urls"] = args?.urls;
            resourceInputs["useConnectServer"] = args?.useConnectServer;
            resourceInputs["useProxy"] = args?.useProxy;
            resourceInputs["useServiceAccount"] = args?.useServiceAccount;
            resourceInputs["useTenant"] = args?.useTenant;
            resourceInputs["useTls"] = args?.useTls;
            resourceInputs["username"] = args?.username;
            resourceInputs["value"] = args?.value;
            resourceInputs["version"] = args?.version;
            resourceInputs["warehouse"] = args?.warehouse;
            resourceInputs["webhookUrl"] = args?.webhookUrl ? pulumi.secret(args.webhookUrl) : undefined;
            resourceInputs["webuiPort"] = args?.webuiPort;
            resourceInputs["appliedDigests"] = undefined /*out*/;
        } else {
            resourceInputs["accessControlGroup"] = undefined /*out*/;
            resourceInputs["accessControlMethod"] = undefined /*out*/;
            resourceInputs["accessKeyId"] = undefined /*out*/;
            resourceInputs["annotations"] = undefined /*out*/;
            resourceInputs["apiClientId"] = undefined /*out*/;
            resourceInputs["apiClientSecret"] = undefined /*out*/;
            resourceInputs["apiKey"] = undefined /*out*/;
            resourceInputs["apiSecret"] = undefined /*out*/;
            resourceInputs["apiServer"] = undefined /*out*/;
            resourceInputs["apiToken"] = undefined /*out*/;
            resourceInputs["appId"] = undefined /*out*/;
            resourceInputs["appKey"] = undefined /*out*/;
            resourceInputs["applicationId"] = undefined /*out*/;
            resourceInputs["applicationName"] = undefined /*out*/;
            resourceInputs["appliedDigests"] = undefined /*out*/;
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["automationMode"] = undefined /*out*/;
            resourceInputs["awsArn"] = undefined /*out*/;
            resourceInputs["awsRegionName"] = undefined /*out*/;
            resourceInputs["clientCert"] = undefined /*out*/;
            resourceInputs["clientCertificate"] = undefined /*out*/;
            resourceInputs["clientConfiguration"] = undefined /*out*/;
            resourceInputs["clientId"] = undefined /*out*/;
            resourceInputs["clientKey"] = undefined /*out*/;
            resourceInputs["clientSecret"] = undefined /*out*/;
            resourceInputs["clientcert"] = undefined /*out*/;
            resourceInputs["clusterCert"] = undefined /*out*/;
            resourceInputs["clusterToken"] = undefined /*out*/;
            resourceInputs["connectServerUrl"] = undefined /*out*/;
            resourceInputs["cpu"] = undefined /*out*/;
            resourceInputs["createIfNotExists"] = undefined /*out*/;
            resourceInputs["credentialJson"] = undefined /*out*/;
            resourceInputs["databaseAccount"] = undefined /*out*/;
            resourceInputs["databaseName"] = undefined /*out*/;
            resourceInputs["databasePassword"] = undefined /*out*/;
            resourceInputs["databaseUsername"] = undefined /*out*/;
            resourceInputs["ddApiKey"] = undefined /*out*/;
            resourceInputs["ddSite"] = undefined /*out*/;
            resourceInputs["defaultCluster"] = undefined /*out*/;
            resourceInputs["defaultUser"] = undefined /*out*/;
            resourceInputs["domain"] = undefined /*out*/;
            resourceInputs["fields"] = undefined /*out*/;
            resourceInputs["host"] = undefined /*out*/;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["hosts"] = undefined /*out*/;
            resourceInputs["image"] = undefined /*out*/;
            resourceInputs["index"] = undefined /*out*/;
            resourceInputs["isRedisLabs"] = undefined /*out*/;
            resourceInputs["key"] = undefined /*out*/;
            resourceInputs["keyFile"] = undefined /*out*/;
            resourceInputs["ldapEncryptionMethod"] = undefined /*out*/;
            resourceInputs["ldapHostname"] = undefined /*out*/;
            resourceInputs["ldapPort"] = undefined /*out*/;
            resourceInputs["ldapSearchBindDn"] = undefined /*out*/;
            resourceInputs["ldapSearchBindPassword"] = undefined /*out*/;
            resourceInputs["ldapUserBaseDn"] = undefined /*out*/;
            resourceInputs["ldapUserNameAttribute"] = undefined /*out*/;
            resourceInputs["logGroupName"] = undefined /*out*/;
            resourceInputs["logStreamName"] = undefined /*out*/;
            resourceInputs["loginUrl"] = undefined /*out*/;
            resourceInputs["machine"] = undefined /*out*/;
            resourceInputs["memory"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["namespace"] = undefined /*out*/;
            resourceInputs["networkId"] = undefined /*out*/;
            resourceInputs["nodeAffinity"] = undefined /*out*/;
            resourceInputs["nodeSelector"] = undefined /*out*/;
            resourceInputs["oldVersion"] = undefined /*out*/;
            resourceInputs["organizationId"] = undefined /*out*/;
            resourceInputs["password"] = undefined /*out*/;
            resourceInputs["port"] = undefined /*out*/;
            resourceInputs["prestart"] = undefined /*out*/;
            resourceInputs["privateKey"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["protocol"] = undefined /*out*/;
            resourceInputs["proxysqlAdminPassword"] = undefined /*out*/;
            resourceInputs["proxysqlAdminPort"] = undefined /*out*/;
            resourceInputs["proxysqlAdminUsername"] = undefined /*out*/;
            resourceInputs["proxysqlHostgroupId"] = undefined /*out*/;
            resourceInputs["publicKey"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["regionName"] = undefined /*out*/;
            resourceInputs["resource"] = undefined /*out*/;
            resourceInputs["role"] = undefined /*out*/;
            resourceInputs["rootCert"] = undefined /*out*/;
            resourceInputs["schema"] = undefined /*out*/;
            resourceInputs["script"] = undefined /*out*/;
            resourceInputs["secretAccessKey"] = undefined /*out*/;
            resourceInputs["secretId"] = undefined /*out*/;
            resourceInputs["serviceAccount"] = undefined /*out*/;
            resourceInputs["serviceAccountName"] = undefined /*out*/;
            resourceInputs["serviceName"] = undefined /*out*/;
            resourceInputs["sharedSecret"] = undefined /*out*/;
            resourceInputs["sslMode"] = undefined /*out*/;
            resourceInputs["storage"] = undefined /*out*/;
            resourceInputs["subSystemName"] = undefined /*out*/;
            resourceInputs["tags"] = undefined /*out*/;
            resourceInputs["targets"] = undefined /*out*/;
            resourceInputs["tenantId"] = undefined /*out*/;
            resourceInputs["tlsCaCert"] = undefined /*out*/;
            resourceInputs["tlsCertFile"] = undefined /*out*/;
            resourceInputs["tlsEnabled"] = undefined /*out*/;
            resourceInputs["tlsKeyFile"] = undefined /*out*/;
            resourceInputs["tlsRootCert"] = undefined /*out*/;
            resourceInputs["tlsSkipVerify"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["tokenId"] = undefined /*out*/;
            resourceInputs["tolerations"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["uri"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
            resourceInputs["urls"] = undefined /*out*/;
            resourceInputs["useConnectServer"] = undefined /*out*/;
            resourceInputs["useProxy"] = undefined /*out*/;
            resourceInputs["useServiceAccount"] = undefined /*out*/;
            resourceInputs["useTenant"] = undefined /*out*/;
            resourceInputs["useTls"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
            resourceInputs["value"] = undefined /*out*/;
            resourceInputs["version"] = undefined /*out*/;
            resourceInputs["warehouse"] = undefined /*out*/;
            resourceInputs["webhookUrl"] = undefined /*out*/;
            resourceInputs["webuiPort"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiClientSecret", "apiKey", "apiSecret", "apiToken", "appKey", "clientCert", "clientCertificate", "clientConfiguration", "clientKey", "clientSecret", "clientcert", "clusterToken", "credentialJson", "databasePassword", "ddApiKey", "key", "keyFile", "ldapSearchBindPassword", "password", "privateKey", "proxysqlAdminPassword", "secretAccessKey", "secretId", "sharedSecret", "targets", "tlsKeyFile", "token", "tokenId", "uri", "webhookUrl"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Resource.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Resource resource.
 */
export interface ResourceArgs {
    accessControlGroup?: pulumi.Input<string>;
    accessControlMethod?: pulumi.Input<string>;
    accessKeyId?: pulumi.Input<string>;
    annotations?: pulumi.Input<string>;
    apiClientId?: pulumi.Input<string>;
    apiClientSecret?: pulumi.Input<string>;
    apiKey?: pulumi.Input<string>;
    apiSecret?: pulumi.Input<string>;
    apiServer?: pulumi.Input<string>;
    apiToken?: pulumi.Input<string>;
    appId?: pulumi.Input<string>;
    appKey?: pulumi.Input<string>;
    applicationId?: pulumi.Input<string>;
    applicationName?: pulumi.Input<string>;
    arn?: pulumi.Input<string>;
    automationMode?: pulumi.Input<string>;
    awsArn?: pulumi.Input<string>;
    awsRegionName?: pulumi.Input<string>;
    clientCert?: pulumi.Input<string>;
    clientCertificate?: pulumi.Input<string>;
    clientConfiguration?: pulumi.Input<string>;
    clientId?: pulumi.Input<string>;
    clientKey?: pulumi.Input<string>;
    clientSecret?: pulumi.Input<string>;
    clientcert?: pulumi.Input<string>;
    clusterCert?: pulumi.Input<string>;
    clusterToken?: pulumi.Input<string>;
    connectServerUrl?: pulumi.Input<string>;
    cpu?: pulumi.Input<string>;
    createIfNotExists?: pulumi.Input<boolean>;
    credentialJson?: pulumi.Input<string>;
    databaseAccount?: pulumi.Input<string>;
    databaseName?: pulumi.Input<string>;
    databasePassword?: pulumi.Input<string>;
    databaseUsername?: pulumi.Input<string>;
    ddApiKey?: pulumi.Input<string>;
    ddSite?: pulumi.Input<string>;
    /**
     * The default cluster the resource is deployed to.
     */
    defaultCluster?: pulumi.Input<string>;
    defaultUser?: pulumi.Input<string>;
    domain?: pulumi.Input<string>;
    fields?: pulumi.Input<string>;
    host?: pulumi.Input<string>;
    hostname?: pulumi.Input<string>;
    hosts?: pulumi.Input<pulumi.Input<string>[]>;
    image?: pulumi.Input<string>;
    index?: pulumi.Input<string>;
    isRedisLabs?: pulumi.Input<boolean>;
    key?: pulumi.Input<string>;
    keyFile?: pulumi.Input<string>;
    ldapEncryptionMethod?: pulumi.Input<string>;
    ldapHostname?: pulumi.Input<string>;
    ldapPort?: pulumi.Input<string>;
    ldapSearchBindDn?: pulumi.Input<string>;
    ldapSearchBindPassword?: pulumi.Input<string>;
    ldapUserBaseDn?: pulumi.Input<string>;
    ldapUserNameAttribute?: pulumi.Input<string>;
    logGroupName?: pulumi.Input<string>;
    logStreamName?: pulumi.Input<string>;
    loginUrl?: pulumi.Input<string>;
    machine?: pulumi.Input<string>;
    memory?: pulumi.Input<string>;
    /**
     * Name of the Adaptive resource.
     */
    name: pulumi.Input<string>;
    namespace?: pulumi.Input<string>;
    networkId?: pulumi.Input<string>;
    nodeAffinity?: pulumi.Input<string>;
    nodeSelector?: pulumi.Input<string>;
    oldVersion?: pulumi.Input<boolean>;
    organizationId?: pulumi.Input<string>;
    password?: pulumi.Input<string>;
    port?: pulumi.Input<string>;
    prestart?: pulumi.Input<string>;
    privateKey?: pulumi.Input<string>;
    projectId?: pulumi.Input<string>;
    protocol?: pulumi.Input<string>;
    proxysqlAdminPassword?: pulumi.Input<string>;
    proxysqlAdminPort?: pulumi.Input<string>;
    proxysqlAdminUsername?: pulumi.Input<string>;
    proxysqlHostgroupId?: pulumi.Input<string>;
    publicKey?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    regionName?: pulumi.Input<string>;
    resource?: pulumi.Input<string>;
    role?: pulumi.Input<string>;
    rootCert?: pulumi.Input<string>;
    schema?: pulumi.Input<string>;
    script?: pulumi.Input<string>;
    secretAccessKey?: pulumi.Input<string>;
    secretId?: pulumi.Input<string>;
    serviceAccount?: pulumi.Input<string>;
    serviceAccountName?: pulumi.Input<string>;
    serviceName?: pulumi.Input<string>;
    sharedSecret?: pulumi.Input<string>;
    sslMode?: pulumi.Input<string>;
    storage?: pulumi.Input<string>;
    subSystemName?: pulumi.Input<string>;
    /**
     * Optional tags.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    targets?: pulumi.Input<string>;
    tenantId?: pulumi.Input<string>;
    tlsCaCert?: pulumi.Input<string>;
    tlsCertFile?: pulumi.Input<string>;
    tlsEnabled?: pulumi.Input<boolean>;
    tlsKeyFile?: pulumi.Input<string>;
    tlsRootCert?: pulumi.Input<string>;
    tlsSkipVerify?: pulumi.Input<boolean>;
    token?: pulumi.Input<string>;
    tokenId?: pulumi.Input<string>;
    tolerations?: pulumi.Input<string>;
    /**
     * Type of the Adaptive resource (integration), e.g. postgres, mysql, mongodb, ssh, kubernetes, aws, gcp, azure, snowflake.
     */
    type: pulumi.Input<string>;
    uri?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
    urls?: pulumi.Input<string>;
    useConnectServer?: pulumi.Input<boolean>;
    useProxy?: pulumi.Input<boolean>;
    useServiceAccount?: pulumi.Input<boolean>;
    useTenant?: pulumi.Input<boolean>;
    useTls?: pulumi.Input<boolean>;
    username?: pulumi.Input<string>;
    value?: pulumi.Input<string>;
    version?: pulumi.Input<string>;
    warehouse?: pulumi.Input<string>;
    webhookUrl?: pulumi.Input<string>;
    webuiPort?: pulumi.Input<string>;
}
