// *** WARNING: this file was generated by pulumi-adaptive-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Resource extends pulumi.CustomResource {
    /**
     * Get an existing Resource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Resource {
        return new Resource(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'adaptive:index:Resource';

    /**
     * Returns true if the given object is an instance of Resource.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Resource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Resource.__pulumiType;
    }

    declare public readonly accessKeyId: pulumi.Output<string | undefined>;
    declare public readonly annotations: pulumi.Output<string | undefined>;
    declare public readonly apiClientId: pulumi.Output<string | undefined>;
    declare public readonly apiClientSecret: pulumi.Output<string | undefined>;
    declare public readonly apiKey: pulumi.Output<string | undefined>;
    declare public readonly apiServer: pulumi.Output<string | undefined>;
    declare public readonly apiToken: pulumi.Output<string | undefined>;
    declare public readonly appId: pulumi.Output<string | undefined>;
    declare public readonly appKey: pulumi.Output<string | undefined>;
    declare public readonly applicationId: pulumi.Output<string | undefined>;
    declare public readonly applicationName: pulumi.Output<string | undefined>;
    declare public readonly arn: pulumi.Output<string | undefined>;
    declare public readonly awsAccessKeyId: pulumi.Output<string | undefined>;
    declare public readonly awsArn: pulumi.Output<string | undefined>;
    declare public readonly awsRegion: pulumi.Output<string | undefined>;
    declare public readonly awsRegionName: pulumi.Output<string | undefined>;
    declare public readonly awsRoleArn: pulumi.Output<string | undefined>;
    declare public readonly awsSecretAccessKey: pulumi.Output<string | undefined>;
    declare public readonly awsServiceAccount: pulumi.Output<string | undefined>;
    declare public readonly clientId: pulumi.Output<string | undefined>;
    declare public readonly clientSecret: pulumi.Output<string | undefined>;
    declare public readonly clientcert: pulumi.Output<string | undefined>;
    declare public readonly clusterCert: pulumi.Output<string | undefined>;
    declare public readonly clusterToken: pulumi.Output<string | undefined>;
    declare public readonly createIfNotExists: pulumi.Output<boolean | undefined>;
    declare public readonly databaseAccount: pulumi.Output<string | undefined>;
    declare public readonly databaseName: pulumi.Output<string | undefined>;
    declare public readonly databasePassword: pulumi.Output<string | undefined>;
    declare public readonly databaseUsername: pulumi.Output<string | undefined>;
    declare public readonly ddApiKey: pulumi.Output<string | undefined>;
    declare public readonly ddSite: pulumi.Output<string | undefined>;
    /**
     * The default cluster the resource is deployed to.
     */
    declare public readonly defaultCluster: pulumi.Output<string | undefined>;
    declare public readonly defaultUser: pulumi.Output<string | undefined>;
    declare public readonly domain: pulumi.Output<string | undefined>;
    declare public readonly host: pulumi.Output<string | undefined>;
    declare public readonly hostname: pulumi.Output<string | undefined>;
    declare public readonly hosts: pulumi.Output<string[] | undefined>;
    declare public readonly image: pulumi.Output<string | undefined>;
    declare public readonly index: pulumi.Output<string | undefined>;
    declare public readonly key: pulumi.Output<string | undefined>;
    declare public readonly keyFile: pulumi.Output<string | undefined>;
    declare public readonly loginUrl: pulumi.Output<string | undefined>;
    /**
     * Name of the Adaptive resource.
     */
    declare public readonly name: pulumi.Output<string>;
    declare public readonly namespace: pulumi.Output<string | undefined>;
    declare public readonly networkId: pulumi.Output<string | undefined>;
    declare public readonly nodeAffinity: pulumi.Output<string | undefined>;
    declare public readonly nodeSelector: pulumi.Output<string | undefined>;
    declare public readonly organizationId: pulumi.Output<string | undefined>;
    declare public readonly password: pulumi.Output<string | undefined>;
    declare public readonly port: pulumi.Output<string | undefined>;
    declare public readonly privateKey: pulumi.Output<string | undefined>;
    declare public readonly projectId: pulumi.Output<string | undefined>;
    declare public readonly protocol: pulumi.Output<string | undefined>;
    declare public readonly publicKey: pulumi.Output<string | undefined>;
    declare public readonly region: pulumi.Output<string | undefined>;
    declare public readonly regionName: pulumi.Output<string | undefined>;
    declare public readonly role: pulumi.Output<string | undefined>;
    declare public readonly rootCert: pulumi.Output<string | undefined>;
    declare public readonly schema: pulumi.Output<string | undefined>;
    declare public readonly secretAccessKey: pulumi.Output<string | undefined>;
    declare public readonly secretId: pulumi.Output<string | undefined>;
    declare public readonly serviceAccountName: pulumi.Output<string | undefined>;
    declare public readonly sharedSecret: pulumi.Output<string | undefined>;
    declare public readonly sslMode: pulumi.Output<string | undefined>;
    declare public readonly subSystemName: pulumi.Output<string | undefined>;
    /**
     * Optional tags.
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    declare public readonly tenantId: pulumi.Output<string | undefined>;
    declare public readonly tlsCertFile: pulumi.Output<string | undefined>;
    declare public readonly tlsKeyFile: pulumi.Output<string | undefined>;
    declare public readonly tlsRootCert: pulumi.Output<string | undefined>;
    declare public readonly tokenId: pulumi.Output<string | undefined>;
    declare public readonly tolerations: pulumi.Output<string | undefined>;
    /**
     * Type of the Adaptive resource (integration), e.g. postgres, mysql, mongodb, ssh, kubernetes, aws, gcp, azure, snowflake.
     */
    declare public readonly type: pulumi.Output<string>;
    declare public readonly uri: pulumi.Output<string | undefined>;
    declare public readonly url: pulumi.Output<string | undefined>;
    declare public readonly urls: pulumi.Output<string | undefined>;
    declare public readonly useIrsa: pulumi.Output<boolean | undefined>;
    declare public readonly useProxy: pulumi.Output<boolean | undefined>;
    declare public readonly useRdsIam: pulumi.Output<boolean | undefined>;
    declare public readonly useServiceAccount: pulumi.Output<boolean | undefined>;
    declare public readonly useTenant: pulumi.Output<boolean | undefined>;
    declare public readonly username: pulumi.Output<string | undefined>;
    declare public readonly version: pulumi.Output<string | undefined>;
    declare public readonly warehouse: pulumi.Output<string | undefined>;
    declare public readonly webhookUrl: pulumi.Output<string | undefined>;
    declare public readonly webuiPort: pulumi.Output<string | undefined>;

    /**
     * Create a Resource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ResourceArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["accessKeyId"] = args?.accessKeyId ? pulumi.secret(args.accessKeyId) : undefined;
            resourceInputs["annotations"] = args?.annotations;
            resourceInputs["apiClientId"] = args?.apiClientId;
            resourceInputs["apiClientSecret"] = args?.apiClientSecret ? pulumi.secret(args.apiClientSecret) : undefined;
            resourceInputs["apiKey"] = args?.apiKey ? pulumi.secret(args.apiKey) : undefined;
            resourceInputs["apiServer"] = args?.apiServer;
            resourceInputs["apiToken"] = args?.apiToken ? pulumi.secret(args.apiToken) : undefined;
            resourceInputs["appId"] = args?.appId;
            resourceInputs["appKey"] = args?.appKey ? pulumi.secret(args.appKey) : undefined;
            resourceInputs["applicationId"] = args?.applicationId;
            resourceInputs["applicationName"] = args?.applicationName;
            resourceInputs["arn"] = args?.arn;
            resourceInputs["awsAccessKeyId"] = args?.awsAccessKeyId;
            resourceInputs["awsArn"] = args?.awsArn;
            resourceInputs["awsRegion"] = args?.awsRegion;
            resourceInputs["awsRegionName"] = args?.awsRegionName;
            resourceInputs["awsRoleArn"] = args?.awsRoleArn;
            resourceInputs["awsSecretAccessKey"] = args?.awsSecretAccessKey ? pulumi.secret(args.awsSecretAccessKey) : undefined;
            resourceInputs["awsServiceAccount"] = args?.awsServiceAccount;
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["clientcert"] = args?.clientcert ? pulumi.secret(args.clientcert) : undefined;
            resourceInputs["clusterCert"] = args?.clusterCert ? pulumi.secret(args.clusterCert) : undefined;
            resourceInputs["clusterToken"] = args?.clusterToken ? pulumi.secret(args.clusterToken) : undefined;
            resourceInputs["createIfNotExists"] = args?.createIfNotExists;
            resourceInputs["databaseAccount"] = args?.databaseAccount;
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["databasePassword"] = args?.databasePassword ? pulumi.secret(args.databasePassword) : undefined;
            resourceInputs["databaseUsername"] = args?.databaseUsername;
            resourceInputs["ddApiKey"] = args?.ddApiKey ? pulumi.secret(args.ddApiKey) : undefined;
            resourceInputs["ddSite"] = args?.ddSite;
            resourceInputs["defaultCluster"] = args?.defaultCluster;
            resourceInputs["defaultUser"] = args?.defaultUser;
            resourceInputs["domain"] = args?.domain;
            resourceInputs["host"] = args?.host;
            resourceInputs["hostname"] = args?.hostname;
            resourceInputs["hosts"] = args?.hosts;
            resourceInputs["image"] = args?.image;
            resourceInputs["index"] = args?.index;
            resourceInputs["key"] = args?.key ? pulumi.secret(args.key) : undefined;
            resourceInputs["keyFile"] = args?.keyFile ? pulumi.secret(args.keyFile) : undefined;
            resourceInputs["loginUrl"] = args?.loginUrl;
            resourceInputs["name"] = args?.name;
            resourceInputs["namespace"] = args?.namespace;
            resourceInputs["networkId"] = args?.networkId;
            resourceInputs["nodeAffinity"] = args?.nodeAffinity;
            resourceInputs["nodeSelector"] = args?.nodeSelector;
            resourceInputs["organizationId"] = args?.organizationId;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["port"] = args?.port;
            resourceInputs["privateKey"] = args?.privateKey ? pulumi.secret(args.privateKey) : undefined;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["protocol"] = args?.protocol;
            resourceInputs["publicKey"] = args?.publicKey;
            resourceInputs["region"] = args?.region;
            resourceInputs["regionName"] = args?.regionName;
            resourceInputs["role"] = args?.role;
            resourceInputs["rootCert"] = args?.rootCert ? pulumi.secret(args.rootCert) : undefined;
            resourceInputs["schema"] = args?.schema;
            resourceInputs["secretAccessKey"] = args?.secretAccessKey ? pulumi.secret(args.secretAccessKey) : undefined;
            resourceInputs["secretId"] = args?.secretId;
            resourceInputs["serviceAccountName"] = args?.serviceAccountName;
            resourceInputs["sharedSecret"] = args?.sharedSecret ? pulumi.secret(args.sharedSecret) : undefined;
            resourceInputs["sslMode"] = args?.sslMode;
            resourceInputs["subSystemName"] = args?.subSystemName;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["tenantId"] = args?.tenantId;
            resourceInputs["tlsCertFile"] = args?.tlsCertFile ? pulumi.secret(args.tlsCertFile) : undefined;
            resourceInputs["tlsKeyFile"] = args?.tlsKeyFile ? pulumi.secret(args.tlsKeyFile) : undefined;
            resourceInputs["tlsRootCert"] = args?.tlsRootCert ? pulumi.secret(args.tlsRootCert) : undefined;
            resourceInputs["tokenId"] = args?.tokenId;
            resourceInputs["tolerations"] = args?.tolerations;
            resourceInputs["type"] = args?.type;
            resourceInputs["uri"] = args?.uri;
            resourceInputs["url"] = args?.url;
            resourceInputs["urls"] = args?.urls;
            resourceInputs["useIrsa"] = args?.useIrsa;
            resourceInputs["useProxy"] = args?.useProxy;
            resourceInputs["useRdsIam"] = args?.useRdsIam;
            resourceInputs["useServiceAccount"] = args?.useServiceAccount;
            resourceInputs["useTenant"] = args?.useTenant;
            resourceInputs["username"] = args?.username;
            resourceInputs["version"] = args?.version;
            resourceInputs["warehouse"] = args?.warehouse;
            resourceInputs["webhookUrl"] = args?.webhookUrl ? pulumi.secret(args.webhookUrl) : undefined;
            resourceInputs["webuiPort"] = args?.webuiPort;
        } else {
            resourceInputs["accessKeyId"] = undefined /*out*/;
            resourceInputs["annotations"] = undefined /*out*/;
            resourceInputs["apiClientId"] = undefined /*out*/;
            resourceInputs["apiClientSecret"] = undefined /*out*/;
            resourceInputs["apiKey"] = undefined /*out*/;
            resourceInputs["apiServer"] = undefined /*out*/;
            resourceInputs["apiToken"] = undefined /*out*/;
            resourceInputs["appId"] = undefined /*out*/;
            resourceInputs["appKey"] = undefined /*out*/;
            resourceInputs["applicationId"] = undefined /*out*/;
            resourceInputs["applicationName"] = undefined /*out*/;
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["awsAccessKeyId"] = undefined /*out*/;
            resourceInputs["awsArn"] = undefined /*out*/;
            resourceInputs["awsRegion"] = undefined /*out*/;
            resourceInputs["awsRegionName"] = undefined /*out*/;
            resourceInputs["awsRoleArn"] = undefined /*out*/;
            resourceInputs["awsSecretAccessKey"] = undefined /*out*/;
            resourceInputs["awsServiceAccount"] = undefined /*out*/;
            resourceInputs["clientId"] = undefined /*out*/;
            resourceInputs["clientSecret"] = undefined /*out*/;
            resourceInputs["clientcert"] = undefined /*out*/;
            resourceInputs["clusterCert"] = undefined /*out*/;
            resourceInputs["clusterToken"] = undefined /*out*/;
            resourceInputs["createIfNotExists"] = undefined /*out*/;
            resourceInputs["databaseAccount"] = undefined /*out*/;
            resourceInputs["databaseName"] = undefined /*out*/;
            resourceInputs["databasePassword"] = undefined /*out*/;
            resourceInputs["databaseUsername"] = undefined /*out*/;
            resourceInputs["ddApiKey"] = undefined /*out*/;
            resourceInputs["ddSite"] = undefined /*out*/;
            resourceInputs["defaultCluster"] = undefined /*out*/;
            resourceInputs["defaultUser"] = undefined /*out*/;
            resourceInputs["domain"] = undefined /*out*/;
            resourceInputs["host"] = undefined /*out*/;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["hosts"] = undefined /*out*/;
            resourceInputs["image"] = undefined /*out*/;
            resourceInputs["index"] = undefined /*out*/;
            resourceInputs["key"] = undefined /*out*/;
            resourceInputs["keyFile"] = undefined /*out*/;
            resourceInputs["loginUrl"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["namespace"] = undefined /*out*/;
            resourceInputs["networkId"] = undefined /*out*/;
            resourceInputs["nodeAffinity"] = undefined /*out*/;
            resourceInputs["nodeSelector"] = undefined /*out*/;
            resourceInputs["organizationId"] = undefined /*out*/;
            resourceInputs["password"] = undefined /*out*/;
            resourceInputs["port"] = undefined /*out*/;
            resourceInputs["privateKey"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["protocol"] = undefined /*out*/;
            resourceInputs["publicKey"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["regionName"] = undefined /*out*/;
            resourceInputs["role"] = undefined /*out*/;
            resourceInputs["rootCert"] = undefined /*out*/;
            resourceInputs["schema"] = undefined /*out*/;
            resourceInputs["secretAccessKey"] = undefined /*out*/;
            resourceInputs["secretId"] = undefined /*out*/;
            resourceInputs["serviceAccountName"] = undefined /*out*/;
            resourceInputs["sharedSecret"] = undefined /*out*/;
            resourceInputs["sslMode"] = undefined /*out*/;
            resourceInputs["subSystemName"] = undefined /*out*/;
            resourceInputs["tags"] = undefined /*out*/;
            resourceInputs["tenantId"] = undefined /*out*/;
            resourceInputs["tlsCertFile"] = undefined /*out*/;
            resourceInputs["tlsKeyFile"] = undefined /*out*/;
            resourceInputs["tlsRootCert"] = undefined /*out*/;
            resourceInputs["tokenId"] = undefined /*out*/;
            resourceInputs["tolerations"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["uri"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
            resourceInputs["urls"] = undefined /*out*/;
            resourceInputs["useIrsa"] = undefined /*out*/;
            resourceInputs["useProxy"] = undefined /*out*/;
            resourceInputs["useRdsIam"] = undefined /*out*/;
            resourceInputs["useServiceAccount"] = undefined /*out*/;
            resourceInputs["useTenant"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
            resourceInputs["version"] = undefined /*out*/;
            resourceInputs["warehouse"] = undefined /*out*/;
            resourceInputs["webhookUrl"] = undefined /*out*/;
            resourceInputs["webuiPort"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["accessKeyId", "apiClientSecret", "apiKey", "apiToken", "appKey", "awsSecretAccessKey", "clientSecret", "clientcert", "clusterCert", "clusterToken", "databasePassword", "ddApiKey", "key", "keyFile", "password", "privateKey", "rootCert", "secretAccessKey", "sharedSecret", "tlsCertFile", "tlsKeyFile", "tlsRootCert", "webhookUrl"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Resource.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Resource resource.
 */
export interface ResourceArgs {
    accessKeyId?: pulumi.Input<string>;
    annotations?: pulumi.Input<string>;
    apiClientId?: pulumi.Input<string>;
    apiClientSecret?: pulumi.Input<string>;
    apiKey?: pulumi.Input<string>;
    apiServer?: pulumi.Input<string>;
    apiToken?: pulumi.Input<string>;
    appId?: pulumi.Input<string>;
    appKey?: pulumi.Input<string>;
    applicationId?: pulumi.Input<string>;
    applicationName?: pulumi.Input<string>;
    arn?: pulumi.Input<string>;
    awsAccessKeyId?: pulumi.Input<string>;
    awsArn?: pulumi.Input<string>;
    awsRegion?: pulumi.Input<string>;
    awsRegionName?: pulumi.Input<string>;
    awsRoleArn?: pulumi.Input<string>;
    awsSecretAccessKey?: pulumi.Input<string>;
    awsServiceAccount?: pulumi.Input<string>;
    clientId?: pulumi.Input<string>;
    clientSecret?: pulumi.Input<string>;
    clientcert?: pulumi.Input<string>;
    clusterCert?: pulumi.Input<string>;
    clusterToken?: pulumi.Input<string>;
    createIfNotExists?: pulumi.Input<boolean>;
    databaseAccount?: pulumi.Input<string>;
    databaseName?: pulumi.Input<string>;
    databasePassword?: pulumi.Input<string>;
    databaseUsername?: pulumi.Input<string>;
    ddApiKey?: pulumi.Input<string>;
    ddSite?: pulumi.Input<string>;
    /**
     * The default cluster the resource is deployed to.
     */
    defaultCluster?: pulumi.Input<string>;
    defaultUser?: pulumi.Input<string>;
    domain?: pulumi.Input<string>;
    host?: pulumi.Input<string>;
    hostname?: pulumi.Input<string>;
    hosts?: pulumi.Input<pulumi.Input<string>[]>;
    image?: pulumi.Input<string>;
    index?: pulumi.Input<string>;
    key?: pulumi.Input<string>;
    keyFile?: pulumi.Input<string>;
    loginUrl?: pulumi.Input<string>;
    /**
     * Name of the Adaptive resource.
     */
    name: pulumi.Input<string>;
    namespace?: pulumi.Input<string>;
    networkId?: pulumi.Input<string>;
    nodeAffinity?: pulumi.Input<string>;
    nodeSelector?: pulumi.Input<string>;
    organizationId?: pulumi.Input<string>;
    password?: pulumi.Input<string>;
    port?: pulumi.Input<string>;
    privateKey?: pulumi.Input<string>;
    projectId?: pulumi.Input<string>;
    protocol?: pulumi.Input<string>;
    publicKey?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    regionName?: pulumi.Input<string>;
    role?: pulumi.Input<string>;
    rootCert?: pulumi.Input<string>;
    schema?: pulumi.Input<string>;
    secretAccessKey?: pulumi.Input<string>;
    secretId?: pulumi.Input<string>;
    serviceAccountName?: pulumi.Input<string>;
    sharedSecret?: pulumi.Input<string>;
    sslMode?: pulumi.Input<string>;
    subSystemName?: pulumi.Input<string>;
    /**
     * Optional tags.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    tenantId?: pulumi.Input<string>;
    tlsCertFile?: pulumi.Input<string>;
    tlsKeyFile?: pulumi.Input<string>;
    tlsRootCert?: pulumi.Input<string>;
    tokenId?: pulumi.Input<string>;
    tolerations?: pulumi.Input<string>;
    /**
     * Type of the Adaptive resource (integration), e.g. postgres, mysql, mongodb, ssh, kubernetes, aws, gcp, azure, snowflake.
     */
    type: pulumi.Input<string>;
    uri?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
    urls?: pulumi.Input<string>;
    useIrsa?: pulumi.Input<boolean>;
    useProxy?: pulumi.Input<boolean>;
    useRdsIam?: pulumi.Input<boolean>;
    useServiceAccount?: pulumi.Input<boolean>;
    useTenant?: pulumi.Input<boolean>;
    username?: pulumi.Input<string>;
    version?: pulumi.Input<string>;
    warehouse?: pulumi.Input<string>;
    webhookUrl?: pulumi.Input<string>;
    webuiPort?: pulumi.Input<string>;
}
