// *** WARNING: this file was generated by pulumi-adaptive-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Schedule extends pulumi.CustomResource {
    /**
     * Get an existing Schedule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Schedule {
        return new Schedule(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'adaptive:index:Schedule';

    /**
     * Returns true if the given object is an instance of Schedule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Schedule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Schedule.__pulumiType;
    }

    /**
     * Whether the schedule covers the whole day, ignoring the hour and minute bounds.
     */
    declare public readonly allDay: pulumi.Output<boolean | undefined>;
    /**
     * An optional description of the schedule.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Day of month the window closes. Used when scheduleType is monthly.
     */
    declare public readonly endDay: pulumi.Output<number | undefined>;
    /**
     * Hour the window closes (0-23). Ignored when allDay is set.
     */
    declare public readonly endHour: pulumi.Output<number | undefined>;
    /**
     * Minute the window closes (0-59). Ignored when allDay is set.
     */
    declare public readonly endMinute: pulumi.Output<number | undefined>;
    /**
     * Names of endpoints this schedule applies to.
     */
    declare public readonly endpoints: pulumi.Output<string[] | undefined>;
    /**
     * RFC3339 timestamp after which the schedule stops applying.
     */
    declare public readonly expiresAt: pulumi.Output<string | undefined>;
    /**
     * Whether the schedule is active.
     */
    declare public readonly isActive: pulumi.Output<boolean | undefined>;
    /**
     * Maximum granted access duration, in minutes.
     */
    declare public readonly maxAccessTime: pulumi.Output<number | undefined>;
    /**
     * Name of the schedule. Must be unique within the workspace.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Either autoapprove (default) or autoreject.
     */
    declare public readonly operationType: pulumi.Output<string | undefined>;
    /**
     * One of weekdays, weekends, everyday, monthly, specific, or custom.
     */
    declare public readonly scheduleType: pulumi.Output<string>;
    /**
     * RFC3339 dates the schedule applies to. Used when scheduleType is specific.
     */
    declare public readonly specificDates: pulumi.Output<string[] | undefined>;
    /**
     * Day of month the window opens. Used when scheduleType is monthly.
     */
    declare public readonly startDay: pulumi.Output<number | undefined>;
    /**
     * Hour the window opens (0-23). Ignored when allDay is set.
     */
    declare public readonly startHour: pulumi.Output<number | undefined>;
    /**
     * Minute the window opens (0-59). Ignored when allDay is set.
     */
    declare public readonly startMinute: pulumi.Output<number | undefined>;
    /**
     * Names of groups this schedule applies to.
     */
    declare public readonly teams: pulumi.Output<string[] | undefined>;
    /**
     * IANA timezone the window is evaluated in. Empty inherits the workspace default.
     */
    declare public readonly timezone: pulumi.Output<string | undefined>;
    /**
     * Emails of users this schedule applies to.
     */
    declare public readonly users: pulumi.Output<string[] | undefined>;
    /**
     * Weekday names the schedule applies to. Used when scheduleType is custom.
     */
    declare public readonly weekdays: pulumi.Output<string[] | undefined>;

    /**
     * Create a Schedule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ScheduleArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.scheduleType === undefined && !opts.urn) {
                throw new Error("Missing required property 'scheduleType'");
            }
            resourceInputs["allDay"] = (args?.allDay) ?? false;
            resourceInputs["description"] = args?.description;
            resourceInputs["endDay"] = args?.endDay;
            resourceInputs["endHour"] = args?.endHour;
            resourceInputs["endMinute"] = args?.endMinute;
            resourceInputs["endpoints"] = args?.endpoints;
            resourceInputs["expiresAt"] = args?.expiresAt;
            resourceInputs["isActive"] = (args?.isActive) ?? true;
            resourceInputs["maxAccessTime"] = args?.maxAccessTime;
            resourceInputs["name"] = args?.name;
            resourceInputs["operationType"] = (args?.operationType) ?? "autoapprove";
            resourceInputs["scheduleType"] = args?.scheduleType;
            resourceInputs["specificDates"] = args?.specificDates;
            resourceInputs["startDay"] = args?.startDay;
            resourceInputs["startHour"] = args?.startHour;
            resourceInputs["startMinute"] = args?.startMinute;
            resourceInputs["teams"] = args?.teams;
            resourceInputs["timezone"] = args?.timezone;
            resourceInputs["users"] = args?.users;
            resourceInputs["weekdays"] = args?.weekdays;
        } else {
            resourceInputs["allDay"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["endDay"] = undefined /*out*/;
            resourceInputs["endHour"] = undefined /*out*/;
            resourceInputs["endMinute"] = undefined /*out*/;
            resourceInputs["endpoints"] = undefined /*out*/;
            resourceInputs["expiresAt"] = undefined /*out*/;
            resourceInputs["isActive"] = undefined /*out*/;
            resourceInputs["maxAccessTime"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["operationType"] = undefined /*out*/;
            resourceInputs["scheduleType"] = undefined /*out*/;
            resourceInputs["specificDates"] = undefined /*out*/;
            resourceInputs["startDay"] = undefined /*out*/;
            resourceInputs["startHour"] = undefined /*out*/;
            resourceInputs["startMinute"] = undefined /*out*/;
            resourceInputs["teams"] = undefined /*out*/;
            resourceInputs["timezone"] = undefined /*out*/;
            resourceInputs["users"] = undefined /*out*/;
            resourceInputs["weekdays"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Schedule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Schedule resource.
 */
export interface ScheduleArgs {
    /**
     * Whether the schedule covers the whole day, ignoring the hour and minute bounds.
     */
    allDay?: pulumi.Input<boolean>;
    /**
     * An optional description of the schedule.
     */
    description?: pulumi.Input<string>;
    /**
     * Day of month the window closes. Used when scheduleType is monthly.
     */
    endDay?: pulumi.Input<number>;
    /**
     * Hour the window closes (0-23). Ignored when allDay is set.
     */
    endHour?: pulumi.Input<number>;
    /**
     * Minute the window closes (0-59). Ignored when allDay is set.
     */
    endMinute?: pulumi.Input<number>;
    /**
     * Names of endpoints this schedule applies to.
     */
    endpoints?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * RFC3339 timestamp after which the schedule stops applying.
     */
    expiresAt?: pulumi.Input<string>;
    /**
     * Whether the schedule is active.
     */
    isActive?: pulumi.Input<boolean>;
    /**
     * Maximum granted access duration, in minutes.
     */
    maxAccessTime?: pulumi.Input<number>;
    /**
     * Name of the schedule. Must be unique within the workspace.
     */
    name: pulumi.Input<string>;
    /**
     * Either autoapprove (default) or autoreject.
     */
    operationType?: pulumi.Input<string>;
    /**
     * One of weekdays, weekends, everyday, monthly, specific, or custom.
     */
    scheduleType: pulumi.Input<string>;
    /**
     * RFC3339 dates the schedule applies to. Used when scheduleType is specific.
     */
    specificDates?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Day of month the window opens. Used when scheduleType is monthly.
     */
    startDay?: pulumi.Input<number>;
    /**
     * Hour the window opens (0-23). Ignored when allDay is set.
     */
    startHour?: pulumi.Input<number>;
    /**
     * Minute the window opens (0-59). Ignored when allDay is set.
     */
    startMinute?: pulumi.Input<number>;
    /**
     * Names of groups this schedule applies to.
     */
    teams?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * IANA timezone the window is evaluated in. Empty inherits the workspace default.
     */
    timezone?: pulumi.Input<string>;
    /**
     * Emails of users this schedule applies to.
     */
    users?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Weekday names the schedule applies to. Used when scheduleType is custom.
     */
    weekdays?: pulumi.Input<pulumi.Input<string>[]>;
}
